# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'windows-latest'
  demands:
  - msbuild
  - visualstudio

steps:
- task: NuGetToolInstaller@1
  inputs:
    versionSpec: 
    checkLatest: true

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'

- task: VSBuild@1
  inputs:
    solution: '**\*.sln'
    
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(build.sourcesDirectory)\TSIS2.WebResources'
    Contents: |
      Webresources/html/**
      Webresources/css/**
      Webresources/js/**
    TargetFolder: '$(build.ArtifactStagingDirectory)'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(build.sourcesDirectory)\TSIS2.WebResources'
    Contents: |
      release.bat
      spkl.json
    TargetFolder: '$(build.ArtifactStagingDirectory)'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(build.ArtifactStagingDirectory)'
    artifact: 'drop'
    publishLocation: 'pipeline'
