declare namespace Form.appointment.TaskFlowForm {
  namespace AfterMeeting {
    namespace Tabs {
      interface Step_105 extends Xrm.SectionCollectionBase {
        get(name: "Step_105_section1"): Xrm.PageSection;
        get(name: "Step_105_section2"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface Step_19 extends Xrm.SectionCollectionBase {
        get(name: "Step_19_section1"): Xrm.PageSection;
        get(name: "step_2_section2_2"): Xrm.PageSection;
        get(name: "step_2_section3_3"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface Step_39 extends Xrm.SectionCollectionBase {
        get(name: "Step_39_section1"): Xrm.PageSection;
        get(name: "Step_39_section2"): Xrm.PageSection;
        get(name: "Step_39_section3"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface Step_55 extends Xrm.SectionCollectionBase {
        get(name: "Step_55_section1"): Xrm.PageSection;
        get(name: "Step_55_section2"): Xrm.PageSection;
        get(name: "Step_55_section3"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface Step_77 extends Xrm.SectionCollectionBase {
        get(name: "Step_77_section1"): Xrm.PageSection;
        get(name: "Step_77_section2"): Xrm.PageSection;
        get(name: "Step_77_section3"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface step_2 extends Xrm.SectionCollectionBase {
        get(name: "step_2_section1"): Xrm.PageSection;
        get(name: "step_2_section2"): Xrm.PageSection;
        get(name: "step_2_section3"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
    }
    interface Attributes extends Xrm.AttributeCollectionBase {
      get(name: "3b7a919d-1026-8192-2002-1e661ebc5186_back"): Xrm.Attribute<any>;
      get(name: "3b7a919d-1026-8192-2002-1e661ebc5186_next"): Xrm.Attribute<any>;
      get(name: "4287b58e-3ad0-a041-301b-1e16babd016a_back"): Xrm.Attribute<any>;
      get(name: "4287b58e-3ad0-a041-301b-1e16babd016a_next"): Xrm.Attribute<any>;
      get(name: "7d07e69e-2ccc-d0b3-8c99-6607691d1d08_back"): Xrm.Attribute<any>;
      get(name: "7d07e69e-2ccc-d0b3-8c99-6607691d1d08_next"): Xrm.Attribute<any>;
      get(name: "7e7288cc-d628-b81c-da38-ed2b33c5c86e_back"): Xrm.Attribute<any>;
      get(name: "7e7288cc-d628-b81c-da38-ed2b33c5c86e_next"): Xrm.Attribute<any>;
      get(name: "aef4ae7d-1d23-445c-a685-f99933e81b5a_next"): Xrm.Attribute<any>;
      get(name: "birthdate"): Xrm.DateAttribute;
      get(name: "budgetamount"): Xrm.NumberAttribute;
      get(name: "closeprobability"): Xrm.NumberAttribute;
      get(name: "companyname"): Xrm.Attribute<string>;
      get(name: "createdon"): Xrm.DateAttribute;
      get(name: "currentsituation"): Xrm.Attribute<string>;
      get(name: "customerneed"): Xrm.Attribute<string>;
      get(name: "decisionmaker"): Xrm.OptionSetAttribute<boolean>;
      get(name: "description"): Xrm.Attribute<string>;
      get(name: "e575e2e6-5c66-0528-1de1-968159bdc8a8_back"): Xrm.Attribute<any>;
      get(name: "e575e2e6-5c66-0528-1de1-968159bdc8a8_next"): Xrm.Attribute<any>;
      get(name: "emailaddress1"): Xrm.Attribute<string>;
      get(name: "estimatedclosedate"): Xrm.DateAttribute;
      get(name: "estimatedvalue"): Xrm.NumberAttribute;
      get(name: "familystatuscode"): Xrm.OptionSetAttribute<number>;
      get(name: "firstname"): Xrm.Attribute<string>;
      get(name: "jobtitle"): Xrm.Attribute<string>;
      get(name: "lastname"): Xrm.Attribute<string>;
      get(name: "location"): Xrm.Attribute<string>;
      get(name: "mobilephone"): Xrm.Attribute<string>;
      get(name: "name"): Xrm.Attribute<string>;
      get(name: "opportunityratingcode"): Xrm.OptionSetAttribute<number>;
      get(name: "optionalattendees"): Xrm.LookupAttribute<"account" | "contact" | "entitlement" | "equipment" | "knowledgearticle" | "lead" | "queue" | "systemuser" | "unresolvedaddress">;
      get(name: "ownerid"): Xrm.LookupAttribute<"incidents">;
      get(name: "parentaccountid"): Xrm.LookupAttribute<"accounts">;
      get(name: "parentcontactid"): Xrm.LookupAttribute<"opportunities">;
      get(name: "parentcustomerid"): Xrm.LookupAttribute<"contacts">;
      get(name: "primarycontactid"): Xrm.LookupAttribute<"accounts">;
      get(name: "prioritycode"): Xrm.OptionSetAttribute<appointment_prioritycode>;
      get(name: "proposedsolution"): Xrm.Attribute<string>;
      get(name: "purchaseprocess"): Xrm.OptionSetAttribute<number>;
      get(name: "purchasetimeframe"): Xrm.OptionSetAttribute<number>;
      get(name: "regardingobjectid"): Xrm.LookupAttribute<"account" | "bookableresourcebooking" | "bookableresourcebookingheader" | "bulkoperation" | "campaign" | "campaignactivity" | "contact" | "contract" | "entitlement" | "entitlementtemplate" | "ikl_a2d_securitytemplate" | "ikl_bulkmigrationjob" | "ikl_bulkmigrationjobstatus" | "ikl_inogiclicensedetails" | "incident" | "invoice" | "knowledgearticle" | "knowledgebaserecord" | "lead" | "msdyn_agreement" | "msdyn_agreementbookingdate" | "msdyn_agreementbookingincident" | "msdyn_agreementbookingproduct" | "msdyn_agreementbookingservice" | "msdyn_agreementbookingservicetask" | "msdyn_agreementbookingsetup" | "msdyn_agreementinvoicedate" | "msdyn_agreementinvoiceproduct" | "msdyn_agreementinvoicesetup" | "msdyn_bookingalertstatus" | "msdyn_bookingrule" | "msdyn_bookingtimestamp" | "msdyn_customerasset" | "msdyn_fieldservicesetting" | "msdyn_incidenttypecharacteristic" | "msdyn_incidenttypeproduct" | "msdyn_incidenttypeservice" | "msdyn_inventoryadjustment" | "msdyn_inventoryadjustmentproduct" | "msdyn_inventoryjournal" | "msdyn_inventorytransfer" | "msdyn_payment" | "msdyn_paymentdetail" | "msdyn_paymentmethod" | "msdyn_paymentterm" | "msdyn_playbookinstance" | "msdyn_postalbum" | "msdyn_postalcode" | "msdyn_productinventory" | "msdyn_purchaseorder" | "msdyn_purchaseorderbill" | "msdyn_purchaseorderproduct" | "msdyn_purchaseorderreceipt" | "msdyn_purchaseorderreceiptproduct" | "msdyn_purchaseordersubstatus" | "msdyn_quotebookingincident" | "msdyn_quotebookingproduct" | "msdyn_quotebookingservice" | "msdyn_quotebookingservicetask" | "msdyn_resourceterritory" | "msdyn_rma" | "msdyn_rmaproduct" | "msdyn_rmareceipt" | "msdyn_rmareceiptproduct" | "msdyn_rmasubstatus" | "msdyn_rtv" | "msdyn_rtvproduct" | "msdyn_rtvsubstatus" | "msdyn_shipvia" | "msdyn_systemuserschedulersetting" | "msdyn_timegroup" | "msdyn_timegroupdetail" | "msdyn_timeoffrequest" | "msdyn_warehouse" | "msdyn_workorder" | "msdyn_workordercharacteristic" | "msdyn_workorderincident" | "msdyn_workorderproduct" | "msdyn_workorderresourcerestriction" | "msdyn_workorderservice" | "msdyn_workorderservicetask" | "opportunity" | "ppp_traveller" | "quote" | "salesorder" | "site" | "ts_request">;
      get(name: "requiredattendees"): Xrm.LookupAttribute<"account" | "contact" | "entitlement" | "equipment" | "knowledgearticle" | "lead" | "queue" | "systemuser" | "unresolvedaddress">;
      get(name: "resolveby"): Xrm.DateAttribute;
      get(name: "responseby"): Xrm.DateAttribute;
      get(name: "scheduledend"): Xrm.DateAttribute;
      get(name: "scheduledstart"): Xrm.DateAttribute;
      get(name: "spousesname"): Xrm.Attribute<string>;
      get(name: "subject"): Xrm.Attribute<string>;
      get(name: "subjectid"): Xrm.LookupAttribute<"incidents">;
      get(name: "telephone1"): Xrm.Attribute<string>;
      get(name: "ticketnumber"): Xrm.Attribute<string>;
      get(name: "title"): Xrm.Attribute<string>;
      get(name: "websiteurl"): Xrm.Attribute<string>;
      get(name: string): undefined;
      get(): Xrm.Attribute<any>[];
      get(index: number): Xrm.Attribute<any>;
      get(chooser: (item: Xrm.Attribute<any>, index: number) => boolean): Xrm.Attribute<any>[];
    }
    interface Controls extends Xrm.ControlCollectionBase {
      get(name: "3b7a919d-1026-8192-2002-1e661ebc5186_back"): Xrm.Control<Xrm.Attribute<any>>;
      get(name: "3b7a919d-1026-8192-2002-1e661ebc5186_next"): Xrm.Control<Xrm.Attribute<any>>;
      get(name: "4287b58e-3ad0-a041-301b-1e16babd016a_back"): Xrm.Control<Xrm.Attribute<any>>;
      get(name: "4287b58e-3ad0-a041-301b-1e16babd016a_next"): Xrm.Control<Xrm.Attribute<any>>;
      get(name: "7d07e69e-2ccc-d0b3-8c99-6607691d1d08_back"): Xrm.Control<Xrm.Attribute<any>>;
      get(name: "7d07e69e-2ccc-d0b3-8c99-6607691d1d08_next"): Xrm.Control<Xrm.Attribute<any>>;
      get(name: "7e7288cc-d628-b81c-da38-ed2b33c5c86e_back"): Xrm.Control<Xrm.Attribute<any>>;
      get(name: "7e7288cc-d628-b81c-da38-ed2b33c5c86e_next"): Xrm.Control<Xrm.Attribute<any>>;
      get(name: "Account_Appointments:description"): Xrm.StringControl;
      get(name: "Account_Appointments:name"): Xrm.StringControl;
      get(name: "Account_Appointments:parentaccountid"): Xrm.LookupControl<"accounts">;
      get(name: "Account_Appointments:primarycontactid"): Xrm.LookupControl<"accounts">;
      get(name: "Account_Appointments:telephone1"): Xrm.StringControl;
      get(name: "Account_Appointments:websiteurl"): Xrm.StringControl;
      get(name: "Contact_Appointments:birthdate"): Xrm.DateControl;
      get(name: "Contact_Appointments:description"): Xrm.StringControl;
      get(name: "Contact_Appointments:emailaddress1"): Xrm.StringControl;
      get(name: "Contact_Appointments:familystatuscode"): Xrm.OptionSetControl<number>;
      get(name: "Contact_Appointments:firstname"): Xrm.StringControl;
      get(name: "Contact_Appointments:lastname"): Xrm.StringControl;
      get(name: "Contact_Appointments:mobilephone"): Xrm.StringControl;
      get(name: "Contact_Appointments:parentcustomerid"): Xrm.LookupControl<"contacts">;
      get(name: "Contact_Appointments:spousesname"): Xrm.StringControl;
      get(name: "Contact_Appointments:telephone1"): Xrm.StringControl;
      get(name: "Incident_Appointments:description"): Xrm.StringControl;
      get(name: "Incident_Appointments:ownerid"): Xrm.LookupControl<"incidents">;
      get(name: "Incident_Appointments:prioritycode"): Xrm.OptionSetControl<appointment_prioritycode>;
      get(name: "Incident_Appointments:resolveby"): Xrm.DateControl;
      get(name: "Incident_Appointments:responseby"): Xrm.DateControl;
      get(name: "Incident_Appointments:subjectid"): Xrm.LookupControl<"incidents">;
      get(name: "Incident_Appointments:ticketnumber"): Xrm.StringControl;
      get(name: "Incident_Appointments:title"): Xrm.StringControl;
      get(name: "Lead_Appointments:budgetamount"): Xrm.NumberControl;
      get(name: "Lead_Appointments:companyname"): Xrm.StringControl;
      get(name: "Lead_Appointments:createdon"): Xrm.DateControl;
      get(name: "Lead_Appointments:decisionmaker"): Xrm.OptionSetControl<boolean>;
      get(name: "Lead_Appointments:description"): Xrm.StringControl;
      get(name: "Lead_Appointments:emailaddress1"): Xrm.StringControl;
      get(name: "Lead_Appointments:firstname"): Xrm.StringControl;
      get(name: "Lead_Appointments:jobtitle"): Xrm.StringControl;
      get(name: "Lead_Appointments:lastname"): Xrm.StringControl;
      get(name: "Lead_Appointments:mobilephone1"): Xrm.StringControl;
      get(name: "Lead_Appointments:purchaseprocess"): Xrm.OptionSetControl<number>;
      get(name: "Lead_Appointments:purchasetimeframe"): Xrm.OptionSetControl<number>;
      get(name: "Lead_Appointments:subject"): Xrm.StringControl;
      get(name: "Opportunity_Appointments:budgetamount"): Xrm.NumberControl;
      get(name: "Opportunity_Appointments:closeprobability"): Xrm.NumberControl;
      get(name: "Opportunity_Appointments:currentsituation"): Xrm.StringControl;
      get(name: "Opportunity_Appointments:customerneed"): Xrm.StringControl;
      get(name: "Opportunity_Appointments:description4"): Xrm.StringControl;
      get(name: "Opportunity_Appointments:estimatedclosedate"): Xrm.DateControl;
      get(name: "Opportunity_Appointments:estimatedvalue"): Xrm.NumberControl;
      get(name: "Opportunity_Appointments:name1"): Xrm.StringControl;
      get(name: "Opportunity_Appointments:opportunityratingcode"): Xrm.OptionSetControl<number>;
      get(name: "Opportunity_Appointments:parentaccountid1"): Xrm.LookupControl<"opportunities">;
      get(name: "Opportunity_Appointments:parentcontactid"): Xrm.LookupControl<"opportunities">;
      get(name: "Opportunity_Appointments:proposedsolution"): Xrm.StringControl;
      get(name: "aef4ae7d-1d23-445c-a685-f99933e81b5a_next"): Xrm.Control<Xrm.Attribute<any>>;
      get(name: "description"): Xrm.StringControl;
      get(name: "e575e2e6-5c66-0528-1de1-968159bdc8a8_back"): Xrm.Control<Xrm.Attribute<any>>;
      get(name: "e575e2e6-5c66-0528-1de1-968159bdc8a8_next"): Xrm.Control<Xrm.Attribute<any>>;
      get(name: "header_process_birthdate"): Xrm.DateControl | null;
      get(name: "header_process_budgetamount"): Xrm.NumberControl | null;
      get(name: "header_process_budgetamount_1"): Xrm.NumberControl | null;
      get(name: "header_process_closeprobability"): Xrm.NumberControl | null;
      get(name: "header_process_companyname"): Xrm.StringControl | null;
      get(name: "header_process_createdon"): Xrm.DateControl | null;
      get(name: "header_process_currentsituation"): Xrm.StringControl | null;
      get(name: "header_process_customerneed"): Xrm.StringControl | null;
      get(name: "header_process_decisionmaker"): Xrm.OptionSetControl<boolean> | null;
      get(name: "header_process_description"): Xrm.StringControl | null;
      get(name: "header_process_description_1"): Xrm.StringControl | null;
      get(name: "header_process_description_2"): Xrm.StringControl | null;
      get(name: "header_process_description_3"): Xrm.StringControl | null;
      get(name: "header_process_description_4"): Xrm.StringControl | null;
      get(name: "header_process_description_5"): Xrm.StringControl | null;
      get(name: "header_process_emailaddress1"): Xrm.StringControl | null;
      get(name: "header_process_emailaddress1_1"): Xrm.StringControl | null;
      get(name: "header_process_estimatedclosedate"): Xrm.DateControl | null;
      get(name: "header_process_estimatedvalue"): Xrm.NumberControl | null;
      get(name: "header_process_familystatuscode"): Xrm.OptionSetControl<number> | null;
      get(name: "header_process_firstname"): Xrm.StringControl | null;
      get(name: "header_process_firstname_1"): Xrm.StringControl | null;
      get(name: "header_process_jobtitle"): Xrm.StringControl | null;
      get(name: "header_process_lastname"): Xrm.StringControl | null;
      get(name: "header_process_lastname_1"): Xrm.StringControl | null;
      get(name: "header_process_location"): Xrm.StringControl | null;
      get(name: "header_process_mobilephone"): Xrm.StringControl | null;
      get(name: "header_process_mobilephone_1"): Xrm.StringControl | null;
      get(name: "header_process_name"): Xrm.StringControl | null;
      get(name: "header_process_name_1"): Xrm.StringControl | null;
      get(name: "header_process_opportunityratingcode"): Xrm.OptionSetControl<number> | null;
      get(name: "header_process_optionalattendees"): Xrm.LookupControl<"account" | "contact" | "entitlement" | "equipment" | "knowledgearticle" | "lead" | "queue" | "systemuser" | "unresolvedaddress"> | null;
      get(name: "header_process_ownerid"): Xrm.LookupControl<"incident"> | null;
      get(name: "header_process_parentaccountid"): Xrm.LookupControl<"account"> | null;
      get(name: "header_process_parentaccountid_1"): Xrm.LookupControl<"opportunity"> | null;
      get(name: "header_process_parentcontactid"): Xrm.LookupControl<"opportunity"> | null;
      get(name: "header_process_parentcustomerid"): Xrm.LookupControl<"contact"> | null;
      get(name: "header_process_primarycontactid"): Xrm.LookupControl<"account"> | null;
      get(name: "header_process_prioritycode"): Xrm.OptionSetControl<appointment_prioritycode> | null;
      get(name: "header_process_proposedsolution"): Xrm.StringControl | null;
      get(name: "header_process_purchaseprocess"): Xrm.OptionSetControl<number> | null;
      get(name: "header_process_purchasetimeframe"): Xrm.OptionSetControl<number> | null;
      get(name: "header_process_regardingobjectid"): Xrm.LookupControl<"account" | "bookableresourcebooking" | "bookableresourcebookingheader" | "bulkoperation" | "campaign" | "campaignactivity" | "contact" | "contract" | "entitlement" | "entitlementtemplate" | "ikl_a2d_securitytemplate" | "ikl_bulkmigrationjob" | "ikl_bulkmigrationjobstatus" | "ikl_inogiclicensedetails" | "incident" | "invoice" | "knowledgearticle" | "knowledgebaserecord" | "lead" | "msdyn_agreement" | "msdyn_agreementbookingdate" | "msdyn_agreementbookingincident" | "msdyn_agreementbookingproduct" | "msdyn_agreementbookingservice" | "msdyn_agreementbookingservicetask" | "msdyn_agreementbookingsetup" | "msdyn_agreementinvoicedate" | "msdyn_agreementinvoiceproduct" | "msdyn_agreementinvoicesetup" | "msdyn_bookingalertstatus" | "msdyn_bookingrule" | "msdyn_bookingtimestamp" | "msdyn_customerasset" | "msdyn_fieldservicesetting" | "msdyn_incidenttypecharacteristic" | "msdyn_incidenttypeproduct" | "msdyn_incidenttypeservice" | "msdyn_inventoryadjustment" | "msdyn_inventoryadjustmentproduct" | "msdyn_inventoryjournal" | "msdyn_inventorytransfer" | "msdyn_payment" | "msdyn_paymentdetail" | "msdyn_paymentmethod" | "msdyn_paymentterm" | "msdyn_playbookinstance" | "msdyn_postalbum" | "msdyn_postalcode" | "msdyn_productinventory" | "msdyn_purchaseorder" | "msdyn_purchaseorderbill" | "msdyn_purchaseorderproduct" | "msdyn_purchaseorderreceipt" | "msdyn_purchaseorderreceiptproduct" | "msdyn_purchaseordersubstatus" | "msdyn_quotebookingincident" | "msdyn_quotebookingproduct" | "msdyn_quotebookingservice" | "msdyn_quotebookingservicetask" | "msdyn_resourceterritory" | "msdyn_rma" | "msdyn_rmaproduct" | "msdyn_rmareceipt" | "msdyn_rmareceiptproduct" | "msdyn_rmasubstatus" | "msdyn_rtv" | "msdyn_rtvproduct" | "msdyn_rtvsubstatus" | "msdyn_shipvia" | "msdyn_systemuserschedulersetting" | "msdyn_timegroup" | "msdyn_timegroupdetail" | "msdyn_timeoffrequest" | "msdyn_warehouse" | "msdyn_workorder" | "msdyn_workordercharacteristic" | "msdyn_workorderincident" | "msdyn_workorderproduct" | "msdyn_workorderresourcerestriction" | "msdyn_workorderservice" | "msdyn_workorderservicetask" | "opportunity" | "ppp_traveller" | "quote" | "salesorder" | "site" | "ts_request"> | null;
      get(name: "header_process_requiredattendees"): Xrm.LookupControl<"account" | "contact" | "entitlement" | "equipment" | "knowledgearticle" | "lead" | "queue" | "systemuser" | "unresolvedaddress"> | null;
      get(name: "header_process_resolveby"): Xrm.DateControl | null;
      get(name: "header_process_responseby"): Xrm.DateControl | null;
      get(name: "header_process_scheduledend"): Xrm.DateControl | null;
      get(name: "header_process_scheduledstart"): Xrm.DateControl | null;
      get(name: "header_process_spousesname"): Xrm.StringControl | null;
      get(name: "header_process_subject"): Xrm.StringControl | null;
      get(name: "header_process_subject_1"): Xrm.StringControl | null;
      get(name: "header_process_subjectid"): Xrm.LookupControl<"incident"> | null;
      get(name: "header_process_telephone1"): Xrm.StringControl | null;
      get(name: "header_process_telephone1_1"): Xrm.StringControl | null;
      get(name: "header_process_ticketnumber"): Xrm.StringControl | null;
      get(name: "header_process_title"): Xrm.StringControl | null;
      get(name: "header_process_websiteurl"): Xrm.StringControl | null;
      get(name: "location"): Xrm.StringControl;
      get(name: "optionalattendees"): Xrm.LookupControl<"account" | "contact" | "entitlement" | "equipment" | "knowledgearticle" | "lead" | "queue" | "systemuser" | "unresolvedaddress">;
      get(name: "regardingobjectid"): Xrm.LookupControl<"account" | "bookableresourcebooking" | "bookableresourcebookingheader" | "bulkoperation" | "campaign" | "campaignactivity" | "contact" | "contract" | "entitlement" | "entitlementtemplate" | "ikl_a2d_securitytemplate" | "ikl_bulkmigrationjob" | "ikl_bulkmigrationjobstatus" | "ikl_inogiclicensedetails" | "incident" | "invoice" | "knowledgearticle" | "knowledgebaserecord" | "lead" | "msdyn_agreement" | "msdyn_agreementbookingdate" | "msdyn_agreementbookingincident" | "msdyn_agreementbookingproduct" | "msdyn_agreementbookingservice" | "msdyn_agreementbookingservicetask" | "msdyn_agreementbookingsetup" | "msdyn_agreementinvoicedate" | "msdyn_agreementinvoiceproduct" | "msdyn_agreementinvoicesetup" | "msdyn_bookingalertstatus" | "msdyn_bookingrule" | "msdyn_bookingtimestamp" | "msdyn_customerasset" | "msdyn_fieldservicesetting" | "msdyn_incidenttypecharacteristic" | "msdyn_incidenttypeproduct" | "msdyn_incidenttypeservice" | "msdyn_inventoryadjustment" | "msdyn_inventoryadjustmentproduct" | "msdyn_inventoryjournal" | "msdyn_inventorytransfer" | "msdyn_payment" | "msdyn_paymentdetail" | "msdyn_paymentmethod" | "msdyn_paymentterm" | "msdyn_playbookinstance" | "msdyn_postalbum" | "msdyn_postalcode" | "msdyn_productinventory" | "msdyn_purchaseorder" | "msdyn_purchaseorderbill" | "msdyn_purchaseorderproduct" | "msdyn_purchaseorderreceipt" | "msdyn_purchaseorderreceiptproduct" | "msdyn_purchaseordersubstatus" | "msdyn_quotebookingincident" | "msdyn_quotebookingproduct" | "msdyn_quotebookingservice" | "msdyn_quotebookingservicetask" | "msdyn_resourceterritory" | "msdyn_rma" | "msdyn_rmaproduct" | "msdyn_rmareceipt" | "msdyn_rmareceiptproduct" | "msdyn_rmasubstatus" | "msdyn_rtv" | "msdyn_rtvproduct" | "msdyn_rtvsubstatus" | "msdyn_shipvia" | "msdyn_systemuserschedulersetting" | "msdyn_timegroup" | "msdyn_timegroupdetail" | "msdyn_timeoffrequest" | "msdyn_warehouse" | "msdyn_workorder" | "msdyn_workordercharacteristic" | "msdyn_workorderincident" | "msdyn_workorderproduct" | "msdyn_workorderresourcerestriction" | "msdyn_workorderservice" | "msdyn_workorderservicetask" | "opportunity" | "ppp_traveller" | "quote" | "salesorder" | "site" | "ts_request">;
      get(name: "requiredattendees"): Xrm.LookupControl<"account" | "contact" | "entitlement" | "equipment" | "knowledgearticle" | "lead" | "queue" | "systemuser" | "unresolvedaddress">;
      get(name: "scheduledend"): Xrm.DateControl;
      get(name: "scheduledstart"): Xrm.DateControl;
      get(name: "subject"): Xrm.StringControl;
      get(name: string): undefined;
      get(): Xrm.BaseControl[];
      get(index: number): Xrm.BaseControl;
      get(chooser: (item: Xrm.BaseControl, index: number) => boolean): Xrm.BaseControl[];
    }
    interface Tabs extends Xrm.TabCollectionBase {
      get(name: "Step_105"): Xrm.PageTab<Tabs.Step_105>;
      get(name: "Step_19"): Xrm.PageTab<Tabs.Step_19>;
      get(name: "Step_39"): Xrm.PageTab<Tabs.Step_39>;
      get(name: "Step_55"): Xrm.PageTab<Tabs.Step_55>;
      get(name: "Step_77"): Xrm.PageTab<Tabs.Step_77>;
      get(name: "step_2"): Xrm.PageTab<Tabs.step_2>;
      get(name: string): undefined;
      get(): Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>[];
      get(index: number): Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>;
      get(chooser: (item: Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>, index: number) => boolean): Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>[];
    }
  }
  interface AfterMeeting extends Xrm.PageBase<AfterMeeting.Attributes,AfterMeeting.Tabs,AfterMeeting.Controls> {
    getAttribute(attributeName: "3b7a919d-1026-8192-2002-1e661ebc5186_back"): Xrm.Attribute<any>;
    getAttribute(attributeName: "3b7a919d-1026-8192-2002-1e661ebc5186_next"): Xrm.Attribute<any>;
    getAttribute(attributeName: "4287b58e-3ad0-a041-301b-1e16babd016a_back"): Xrm.Attribute<any>;
    getAttribute(attributeName: "4287b58e-3ad0-a041-301b-1e16babd016a_next"): Xrm.Attribute<any>;
    getAttribute(attributeName: "7d07e69e-2ccc-d0b3-8c99-6607691d1d08_back"): Xrm.Attribute<any>;
    getAttribute(attributeName: "7d07e69e-2ccc-d0b3-8c99-6607691d1d08_next"): Xrm.Attribute<any>;
    getAttribute(attributeName: "7e7288cc-d628-b81c-da38-ed2b33c5c86e_back"): Xrm.Attribute<any>;
    getAttribute(attributeName: "7e7288cc-d628-b81c-da38-ed2b33c5c86e_next"): Xrm.Attribute<any>;
    getAttribute(attributeName: "aef4ae7d-1d23-445c-a685-f99933e81b5a_next"): Xrm.Attribute<any>;
    getAttribute(attributeName: "birthdate"): Xrm.DateAttribute;
    getAttribute(attributeName: "budgetamount"): Xrm.NumberAttribute;
    getAttribute(attributeName: "closeprobability"): Xrm.NumberAttribute;
    getAttribute(attributeName: "companyname"): Xrm.Attribute<string>;
    getAttribute(attributeName: "createdon"): Xrm.DateAttribute;
    getAttribute(attributeName: "currentsituation"): Xrm.Attribute<string>;
    getAttribute(attributeName: "customerneed"): Xrm.Attribute<string>;
    getAttribute(attributeName: "decisionmaker"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "description"): Xrm.Attribute<string>;
    getAttribute(attributeName: "e575e2e6-5c66-0528-1de1-968159bdc8a8_back"): Xrm.Attribute<any>;
    getAttribute(attributeName: "e575e2e6-5c66-0528-1de1-968159bdc8a8_next"): Xrm.Attribute<any>;
    getAttribute(attributeName: "emailaddress1"): Xrm.Attribute<string>;
    getAttribute(attributeName: "estimatedclosedate"): Xrm.DateAttribute;
    getAttribute(attributeName: "estimatedvalue"): Xrm.NumberAttribute;
    getAttribute(attributeName: "familystatuscode"): Xrm.OptionSetAttribute<number>;
    getAttribute(attributeName: "firstname"): Xrm.Attribute<string>;
    getAttribute(attributeName: "jobtitle"): Xrm.Attribute<string>;
    getAttribute(attributeName: "lastname"): Xrm.Attribute<string>;
    getAttribute(attributeName: "location"): Xrm.Attribute<string>;
    getAttribute(attributeName: "mobilephone"): Xrm.Attribute<string>;
    getAttribute(attributeName: "name"): Xrm.Attribute<string>;
    getAttribute(attributeName: "opportunityratingcode"): Xrm.OptionSetAttribute<number>;
    getAttribute(attributeName: "optionalattendees"): Xrm.LookupAttribute<"account" | "contact" | "entitlement" | "equipment" | "knowledgearticle" | "lead" | "queue" | "systemuser" | "unresolvedaddress">;
    getAttribute(attributeName: "ownerid"): Xrm.LookupAttribute<"incidents">;
    getAttribute(attributeName: "parentaccountid"): Xrm.LookupAttribute<"accounts">;
    getAttribute(attributeName: "parentcontactid"): Xrm.LookupAttribute<"opportunities">;
    getAttribute(attributeName: "parentcustomerid"): Xrm.LookupAttribute<"contacts">;
    getAttribute(attributeName: "primarycontactid"): Xrm.LookupAttribute<"accounts">;
    getAttribute(attributeName: "prioritycode"): Xrm.OptionSetAttribute<appointment_prioritycode>;
    getAttribute(attributeName: "proposedsolution"): Xrm.Attribute<string>;
    getAttribute(attributeName: "purchaseprocess"): Xrm.OptionSetAttribute<number>;
    getAttribute(attributeName: "purchasetimeframe"): Xrm.OptionSetAttribute<number>;
    getAttribute(attributeName: "regardingobjectid"): Xrm.LookupAttribute<"account" | "bookableresourcebooking" | "bookableresourcebookingheader" | "bulkoperation" | "campaign" | "campaignactivity" | "contact" | "contract" | "entitlement" | "entitlementtemplate" | "ikl_a2d_securitytemplate" | "ikl_bulkmigrationjob" | "ikl_bulkmigrationjobstatus" | "ikl_inogiclicensedetails" | "incident" | "invoice" | "knowledgearticle" | "knowledgebaserecord" | "lead" | "msdyn_agreement" | "msdyn_agreementbookingdate" | "msdyn_agreementbookingincident" | "msdyn_agreementbookingproduct" | "msdyn_agreementbookingservice" | "msdyn_agreementbookingservicetask" | "msdyn_agreementbookingsetup" | "msdyn_agreementinvoicedate" | "msdyn_agreementinvoiceproduct" | "msdyn_agreementinvoicesetup" | "msdyn_bookingalertstatus" | "msdyn_bookingrule" | "msdyn_bookingtimestamp" | "msdyn_customerasset" | "msdyn_fieldservicesetting" | "msdyn_incidenttypecharacteristic" | "msdyn_incidenttypeproduct" | "msdyn_incidenttypeservice" | "msdyn_inventoryadjustment" | "msdyn_inventoryadjustmentproduct" | "msdyn_inventoryjournal" | "msdyn_inventorytransfer" | "msdyn_payment" | "msdyn_paymentdetail" | "msdyn_paymentmethod" | "msdyn_paymentterm" | "msdyn_playbookinstance" | "msdyn_postalbum" | "msdyn_postalcode" | "msdyn_productinventory" | "msdyn_purchaseorder" | "msdyn_purchaseorderbill" | "msdyn_purchaseorderproduct" | "msdyn_purchaseorderreceipt" | "msdyn_purchaseorderreceiptproduct" | "msdyn_purchaseordersubstatus" | "msdyn_quotebookingincident" | "msdyn_quotebookingproduct" | "msdyn_quotebookingservice" | "msdyn_quotebookingservicetask" | "msdyn_resourceterritory" | "msdyn_rma" | "msdyn_rmaproduct" | "msdyn_rmareceipt" | "msdyn_rmareceiptproduct" | "msdyn_rmasubstatus" | "msdyn_rtv" | "msdyn_rtvproduct" | "msdyn_rtvsubstatus" | "msdyn_shipvia" | "msdyn_systemuserschedulersetting" | "msdyn_timegroup" | "msdyn_timegroupdetail" | "msdyn_timeoffrequest" | "msdyn_warehouse" | "msdyn_workorder" | "msdyn_workordercharacteristic" | "msdyn_workorderincident" | "msdyn_workorderproduct" | "msdyn_workorderresourcerestriction" | "msdyn_workorderservice" | "msdyn_workorderservicetask" | "opportunity" | "ppp_traveller" | "quote" | "salesorder" | "site" | "ts_request">;
    getAttribute(attributeName: "requiredattendees"): Xrm.LookupAttribute<"account" | "contact" | "entitlement" | "equipment" | "knowledgearticle" | "lead" | "queue" | "systemuser" | "unresolvedaddress">;
    getAttribute(attributeName: "resolveby"): Xrm.DateAttribute;
    getAttribute(attributeName: "responseby"): Xrm.DateAttribute;
    getAttribute(attributeName: "scheduledend"): Xrm.DateAttribute;
    getAttribute(attributeName: "scheduledstart"): Xrm.DateAttribute;
    getAttribute(attributeName: "spousesname"): Xrm.Attribute<string>;
    getAttribute(attributeName: "subject"): Xrm.Attribute<string>;
    getAttribute(attributeName: "subjectid"): Xrm.LookupAttribute<"incidents">;
    getAttribute(attributeName: "telephone1"): Xrm.Attribute<string>;
    getAttribute(attributeName: "ticketnumber"): Xrm.Attribute<string>;
    getAttribute(attributeName: "title"): Xrm.Attribute<string>;
    getAttribute(attributeName: "websiteurl"): Xrm.Attribute<string>;
    getAttribute(attributeName: string): undefined;
    getControl(controlName: "3b7a919d-1026-8192-2002-1e661ebc5186_back"): Xrm.Control<Xrm.Attribute<any>>;
    getControl(controlName: "3b7a919d-1026-8192-2002-1e661ebc5186_next"): Xrm.Control<Xrm.Attribute<any>>;
    getControl(controlName: "4287b58e-3ad0-a041-301b-1e16babd016a_back"): Xrm.Control<Xrm.Attribute<any>>;
    getControl(controlName: "4287b58e-3ad0-a041-301b-1e16babd016a_next"): Xrm.Control<Xrm.Attribute<any>>;
    getControl(controlName: "7d07e69e-2ccc-d0b3-8c99-6607691d1d08_back"): Xrm.Control<Xrm.Attribute<any>>;
    getControl(controlName: "7d07e69e-2ccc-d0b3-8c99-6607691d1d08_next"): Xrm.Control<Xrm.Attribute<any>>;
    getControl(controlName: "7e7288cc-d628-b81c-da38-ed2b33c5c86e_back"): Xrm.Control<Xrm.Attribute<any>>;
    getControl(controlName: "7e7288cc-d628-b81c-da38-ed2b33c5c86e_next"): Xrm.Control<Xrm.Attribute<any>>;
    getControl(controlName: "Account_Appointments:description"): Xrm.StringControl;
    getControl(controlName: "Account_Appointments:name"): Xrm.StringControl;
    getControl(controlName: "Account_Appointments:parentaccountid"): Xrm.LookupControl<"accounts">;
    getControl(controlName: "Account_Appointments:primarycontactid"): Xrm.LookupControl<"accounts">;
    getControl(controlName: "Account_Appointments:telephone1"): Xrm.StringControl;
    getControl(controlName: "Account_Appointments:websiteurl"): Xrm.StringControl;
    getControl(controlName: "Contact_Appointments:birthdate"): Xrm.DateControl;
    getControl(controlName: "Contact_Appointments:description"): Xrm.StringControl;
    getControl(controlName: "Contact_Appointments:emailaddress1"): Xrm.StringControl;
    getControl(controlName: "Contact_Appointments:familystatuscode"): Xrm.OptionSetControl<number>;
    getControl(controlName: "Contact_Appointments:firstname"): Xrm.StringControl;
    getControl(controlName: "Contact_Appointments:lastname"): Xrm.StringControl;
    getControl(controlName: "Contact_Appointments:mobilephone"): Xrm.StringControl;
    getControl(controlName: "Contact_Appointments:parentcustomerid"): Xrm.LookupControl<"contacts">;
    getControl(controlName: "Contact_Appointments:spousesname"): Xrm.StringControl;
    getControl(controlName: "Contact_Appointments:telephone1"): Xrm.StringControl;
    getControl(controlName: "Incident_Appointments:description"): Xrm.StringControl;
    getControl(controlName: "Incident_Appointments:ownerid"): Xrm.LookupControl<"incidents">;
    getControl(controlName: "Incident_Appointments:prioritycode"): Xrm.OptionSetControl<appointment_prioritycode>;
    getControl(controlName: "Incident_Appointments:resolveby"): Xrm.DateControl;
    getControl(controlName: "Incident_Appointments:responseby"): Xrm.DateControl;
    getControl(controlName: "Incident_Appointments:subjectid"): Xrm.LookupControl<"incidents">;
    getControl(controlName: "Incident_Appointments:ticketnumber"): Xrm.StringControl;
    getControl(controlName: "Incident_Appointments:title"): Xrm.StringControl;
    getControl(controlName: "Lead_Appointments:budgetamount"): Xrm.NumberControl;
    getControl(controlName: "Lead_Appointments:companyname"): Xrm.StringControl;
    getControl(controlName: "Lead_Appointments:createdon"): Xrm.DateControl;
    getControl(controlName: "Lead_Appointments:decisionmaker"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "Lead_Appointments:description"): Xrm.StringControl;
    getControl(controlName: "Lead_Appointments:emailaddress1"): Xrm.StringControl;
    getControl(controlName: "Lead_Appointments:firstname"): Xrm.StringControl;
    getControl(controlName: "Lead_Appointments:jobtitle"): Xrm.StringControl;
    getControl(controlName: "Lead_Appointments:lastname"): Xrm.StringControl;
    getControl(controlName: "Lead_Appointments:mobilephone1"): Xrm.StringControl;
    getControl(controlName: "Lead_Appointments:purchaseprocess"): Xrm.OptionSetControl<number>;
    getControl(controlName: "Lead_Appointments:purchasetimeframe"): Xrm.OptionSetControl<number>;
    getControl(controlName: "Lead_Appointments:subject"): Xrm.StringControl;
    getControl(controlName: "Opportunity_Appointments:budgetamount"): Xrm.NumberControl;
    getControl(controlName: "Opportunity_Appointments:closeprobability"): Xrm.NumberControl;
    getControl(controlName: "Opportunity_Appointments:currentsituation"): Xrm.StringControl;
    getControl(controlName: "Opportunity_Appointments:customerneed"): Xrm.StringControl;
    getControl(controlName: "Opportunity_Appointments:description4"): Xrm.StringControl;
    getControl(controlName: "Opportunity_Appointments:estimatedclosedate"): Xrm.DateControl;
    getControl(controlName: "Opportunity_Appointments:estimatedvalue"): Xrm.NumberControl;
    getControl(controlName: "Opportunity_Appointments:name1"): Xrm.StringControl;
    getControl(controlName: "Opportunity_Appointments:opportunityratingcode"): Xrm.OptionSetControl<number>;
    getControl(controlName: "Opportunity_Appointments:parentaccountid1"): Xrm.LookupControl<"opportunities">;
    getControl(controlName: "Opportunity_Appointments:parentcontactid"): Xrm.LookupControl<"opportunities">;
    getControl(controlName: "Opportunity_Appointments:proposedsolution"): Xrm.StringControl;
    getControl(controlName: "aef4ae7d-1d23-445c-a685-f99933e81b5a_next"): Xrm.Control<Xrm.Attribute<any>>;
    getControl(controlName: "description"): Xrm.StringControl;
    getControl(controlName: "e575e2e6-5c66-0528-1de1-968159bdc8a8_back"): Xrm.Control<Xrm.Attribute<any>>;
    getControl(controlName: "e575e2e6-5c66-0528-1de1-968159bdc8a8_next"): Xrm.Control<Xrm.Attribute<any>>;
    getControl(controlName: "header_process_birthdate"): Xrm.DateControl | null;
    getControl(controlName: "header_process_budgetamount"): Xrm.NumberControl | null;
    getControl(controlName: "header_process_budgetamount_1"): Xrm.NumberControl | null;
    getControl(controlName: "header_process_closeprobability"): Xrm.NumberControl | null;
    getControl(controlName: "header_process_companyname"): Xrm.StringControl | null;
    getControl(controlName: "header_process_createdon"): Xrm.DateControl | null;
    getControl(controlName: "header_process_currentsituation"): Xrm.StringControl | null;
    getControl(controlName: "header_process_customerneed"): Xrm.StringControl | null;
    getControl(controlName: "header_process_decisionmaker"): Xrm.OptionSetControl<boolean> | null;
    getControl(controlName: "header_process_description"): Xrm.StringControl | null;
    getControl(controlName: "header_process_description_1"): Xrm.StringControl | null;
    getControl(controlName: "header_process_description_2"): Xrm.StringControl | null;
    getControl(controlName: "header_process_description_3"): Xrm.StringControl | null;
    getControl(controlName: "header_process_description_4"): Xrm.StringControl | null;
    getControl(controlName: "header_process_description_5"): Xrm.StringControl | null;
    getControl(controlName: "header_process_emailaddress1"): Xrm.StringControl | null;
    getControl(controlName: "header_process_emailaddress1_1"): Xrm.StringControl | null;
    getControl(controlName: "header_process_estimatedclosedate"): Xrm.DateControl | null;
    getControl(controlName: "header_process_estimatedvalue"): Xrm.NumberControl | null;
    getControl(controlName: "header_process_familystatuscode"): Xrm.OptionSetControl<number> | null;
    getControl(controlName: "header_process_firstname"): Xrm.StringControl | null;
    getControl(controlName: "header_process_firstname_1"): Xrm.StringControl | null;
    getControl(controlName: "header_process_jobtitle"): Xrm.StringControl | null;
    getControl(controlName: "header_process_lastname"): Xrm.StringControl | null;
    getControl(controlName: "header_process_lastname_1"): Xrm.StringControl | null;
    getControl(controlName: "header_process_location"): Xrm.StringControl | null;
    getControl(controlName: "header_process_mobilephone"): Xrm.StringControl | null;
    getControl(controlName: "header_process_mobilephone_1"): Xrm.StringControl | null;
    getControl(controlName: "header_process_name"): Xrm.StringControl | null;
    getControl(controlName: "header_process_name_1"): Xrm.StringControl | null;
    getControl(controlName: "header_process_opportunityratingcode"): Xrm.OptionSetControl<number> | null;
    getControl(controlName: "header_process_optionalattendees"): Xrm.LookupControl<"account" | "contact" | "entitlement" | "equipment" | "knowledgearticle" | "lead" | "queue" | "systemuser" | "unresolvedaddress"> | null;
    getControl(controlName: "header_process_ownerid"): Xrm.LookupControl<"incident"> | null;
    getControl(controlName: "header_process_parentaccountid"): Xrm.LookupControl<"account"> | null;
    getControl(controlName: "header_process_parentaccountid_1"): Xrm.LookupControl<"opportunity"> | null;
    getControl(controlName: "header_process_parentcontactid"): Xrm.LookupControl<"opportunity"> | null;
    getControl(controlName: "header_process_parentcustomerid"): Xrm.LookupControl<"contact"> | null;
    getControl(controlName: "header_process_primarycontactid"): Xrm.LookupControl<"account"> | null;
    getControl(controlName: "header_process_prioritycode"): Xrm.OptionSetControl<appointment_prioritycode> | null;
    getControl(controlName: "header_process_proposedsolution"): Xrm.StringControl | null;
    getControl(controlName: "header_process_purchaseprocess"): Xrm.OptionSetControl<number> | null;
    getControl(controlName: "header_process_purchasetimeframe"): Xrm.OptionSetControl<number> | null;
    getControl(controlName: "header_process_regardingobjectid"): Xrm.LookupControl<"account" | "bookableresourcebooking" | "bookableresourcebookingheader" | "bulkoperation" | "campaign" | "campaignactivity" | "contact" | "contract" | "entitlement" | "entitlementtemplate" | "ikl_a2d_securitytemplate" | "ikl_bulkmigrationjob" | "ikl_bulkmigrationjobstatus" | "ikl_inogiclicensedetails" | "incident" | "invoice" | "knowledgearticle" | "knowledgebaserecord" | "lead" | "msdyn_agreement" | "msdyn_agreementbookingdate" | "msdyn_agreementbookingincident" | "msdyn_agreementbookingproduct" | "msdyn_agreementbookingservice" | "msdyn_agreementbookingservicetask" | "msdyn_agreementbookingsetup" | "msdyn_agreementinvoicedate" | "msdyn_agreementinvoiceproduct" | "msdyn_agreementinvoicesetup" | "msdyn_bookingalertstatus" | "msdyn_bookingrule" | "msdyn_bookingtimestamp" | "msdyn_customerasset" | "msdyn_fieldservicesetting" | "msdyn_incidenttypecharacteristic" | "msdyn_incidenttypeproduct" | "msdyn_incidenttypeservice" | "msdyn_inventoryadjustment" | "msdyn_inventoryadjustmentproduct" | "msdyn_inventoryjournal" | "msdyn_inventorytransfer" | "msdyn_payment" | "msdyn_paymentdetail" | "msdyn_paymentmethod" | "msdyn_paymentterm" | "msdyn_playbookinstance" | "msdyn_postalbum" | "msdyn_postalcode" | "msdyn_productinventory" | "msdyn_purchaseorder" | "msdyn_purchaseorderbill" | "msdyn_purchaseorderproduct" | "msdyn_purchaseorderreceipt" | "msdyn_purchaseorderreceiptproduct" | "msdyn_purchaseordersubstatus" | "msdyn_quotebookingincident" | "msdyn_quotebookingproduct" | "msdyn_quotebookingservice" | "msdyn_quotebookingservicetask" | "msdyn_resourceterritory" | "msdyn_rma" | "msdyn_rmaproduct" | "msdyn_rmareceipt" | "msdyn_rmareceiptproduct" | "msdyn_rmasubstatus" | "msdyn_rtv" | "msdyn_rtvproduct" | "msdyn_rtvsubstatus" | "msdyn_shipvia" | "msdyn_systemuserschedulersetting" | "msdyn_timegroup" | "msdyn_timegroupdetail" | "msdyn_timeoffrequest" | "msdyn_warehouse" | "msdyn_workorder" | "msdyn_workordercharacteristic" | "msdyn_workorderincident" | "msdyn_workorderproduct" | "msdyn_workorderresourcerestriction" | "msdyn_workorderservice" | "msdyn_workorderservicetask" | "opportunity" | "ppp_traveller" | "quote" | "salesorder" | "site" | "ts_request"> | null;
    getControl(controlName: "header_process_requiredattendees"): Xrm.LookupControl<"account" | "contact" | "entitlement" | "equipment" | "knowledgearticle" | "lead" | "queue" | "systemuser" | "unresolvedaddress"> | null;
    getControl(controlName: "header_process_resolveby"): Xrm.DateControl | null;
    getControl(controlName: "header_process_responseby"): Xrm.DateControl | null;
    getControl(controlName: "header_process_scheduledend"): Xrm.DateControl | null;
    getControl(controlName: "header_process_scheduledstart"): Xrm.DateControl | null;
    getControl(controlName: "header_process_spousesname"): Xrm.StringControl | null;
    getControl(controlName: "header_process_subject"): Xrm.StringControl | null;
    getControl(controlName: "header_process_subject_1"): Xrm.StringControl | null;
    getControl(controlName: "header_process_subjectid"): Xrm.LookupControl<"incident"> | null;
    getControl(controlName: "header_process_telephone1"): Xrm.StringControl | null;
    getControl(controlName: "header_process_telephone1_1"): Xrm.StringControl | null;
    getControl(controlName: "header_process_ticketnumber"): Xrm.StringControl | null;
    getControl(controlName: "header_process_title"): Xrm.StringControl | null;
    getControl(controlName: "header_process_websiteurl"): Xrm.StringControl | null;
    getControl(controlName: "location"): Xrm.StringControl;
    getControl(controlName: "optionalattendees"): Xrm.LookupControl<"account" | "contact" | "entitlement" | "equipment" | "knowledgearticle" | "lead" | "queue" | "systemuser" | "unresolvedaddress">;
    getControl(controlName: "regardingobjectid"): Xrm.LookupControl<"account" | "bookableresourcebooking" | "bookableresourcebookingheader" | "bulkoperation" | "campaign" | "campaignactivity" | "contact" | "contract" | "entitlement" | "entitlementtemplate" | "ikl_a2d_securitytemplate" | "ikl_bulkmigrationjob" | "ikl_bulkmigrationjobstatus" | "ikl_inogiclicensedetails" | "incident" | "invoice" | "knowledgearticle" | "knowledgebaserecord" | "lead" | "msdyn_agreement" | "msdyn_agreementbookingdate" | "msdyn_agreementbookingincident" | "msdyn_agreementbookingproduct" | "msdyn_agreementbookingservice" | "msdyn_agreementbookingservicetask" | "msdyn_agreementbookingsetup" | "msdyn_agreementinvoicedate" | "msdyn_agreementinvoiceproduct" | "msdyn_agreementinvoicesetup" | "msdyn_bookingalertstatus" | "msdyn_bookingrule" | "msdyn_bookingtimestamp" | "msdyn_customerasset" | "msdyn_fieldservicesetting" | "msdyn_incidenttypecharacteristic" | "msdyn_incidenttypeproduct" | "msdyn_incidenttypeservice" | "msdyn_inventoryadjustment" | "msdyn_inventoryadjustmentproduct" | "msdyn_inventoryjournal" | "msdyn_inventorytransfer" | "msdyn_payment" | "msdyn_paymentdetail" | "msdyn_paymentmethod" | "msdyn_paymentterm" | "msdyn_playbookinstance" | "msdyn_postalbum" | "msdyn_postalcode" | "msdyn_productinventory" | "msdyn_purchaseorder" | "msdyn_purchaseorderbill" | "msdyn_purchaseorderproduct" | "msdyn_purchaseorderreceipt" | "msdyn_purchaseorderreceiptproduct" | "msdyn_purchaseordersubstatus" | "msdyn_quotebookingincident" | "msdyn_quotebookingproduct" | "msdyn_quotebookingservice" | "msdyn_quotebookingservicetask" | "msdyn_resourceterritory" | "msdyn_rma" | "msdyn_rmaproduct" | "msdyn_rmareceipt" | "msdyn_rmareceiptproduct" | "msdyn_rmasubstatus" | "msdyn_rtv" | "msdyn_rtvproduct" | "msdyn_rtvsubstatus" | "msdyn_shipvia" | "msdyn_systemuserschedulersetting" | "msdyn_timegroup" | "msdyn_timegroupdetail" | "msdyn_timeoffrequest" | "msdyn_warehouse" | "msdyn_workorder" | "msdyn_workordercharacteristic" | "msdyn_workorderincident" | "msdyn_workorderproduct" | "msdyn_workorderresourcerestriction" | "msdyn_workorderservice" | "msdyn_workorderservicetask" | "opportunity" | "ppp_traveller" | "quote" | "salesorder" | "site" | "ts_request">;
    getControl(controlName: "requiredattendees"): Xrm.LookupControl<"account" | "contact" | "entitlement" | "equipment" | "knowledgearticle" | "lead" | "queue" | "systemuser" | "unresolvedaddress">;
    getControl(controlName: "scheduledend"): Xrm.DateControl;
    getControl(controlName: "scheduledstart"): Xrm.DateControl;
    getControl(controlName: "subject"): Xrm.StringControl;
    getControl(controlName: string): undefined;
  }
}
