interface BusinessUnit_Base extends WebEntity {
  address1_addressid?: string | null;
  address1_addresstypecode?: businessunit_address1_addresstypecode | null;
  address1_city?: string | null;
  address1_country?: string | null;
  address1_county?: string | null;
  address1_fax?: string | null;
  address1_latitude?: number | null;
  address1_line1?: string | null;
  address1_line2?: string | null;
  address1_line3?: string | null;
  address1_longitude?: number | null;
  address1_name?: string | null;
  address1_postalcode?: string | null;
  address1_postofficebox?: string | null;
  address1_shippingmethodcode?: businessunit_address1_shippingmethodcode | null;
  address1_stateorprovince?: string | null;
  address1_telephone1?: string | null;
  address1_telephone2?: string | null;
  address1_telephone3?: string | null;
  address1_upszone?: string | null;
  address1_utcoffset?: number | null;
  address2_addressid?: string | null;
  address2_addresstypecode?: businessunit_address2_addresstypecode | null;
  address2_city?: string | null;
  address2_country?: string | null;
  address2_county?: string | null;
  address2_fax?: string | null;
  address2_latitude?: number | null;
  address2_line1?: string | null;
  address2_line2?: string | null;
  address2_line3?: string | null;
  address2_longitude?: number | null;
  address2_name?: string | null;
  address2_postalcode?: string | null;
  address2_postofficebox?: string | null;
  address2_shippingmethodcode?: businessunit_address2_shippingmethodcode | null;
  address2_stateorprovince?: string | null;
  address2_telephone1?: string | null;
  address2_telephone2?: string | null;
  address2_telephone3?: string | null;
  address2_upszone?: string | null;
  address2_utcoffset?: number | null;
  businessunitid?: string | null;
  costcenter?: string | null;
  createdon?: Date | null;
  creditlimit?: number | null;
  description?: string | null;
  disabledreason?: string | null;
  divisionname?: string | null;
  emailaddress?: string | null;
  exchangerate?: number | null;
  fileasname?: string | null;
  ftpsiteurl?: string | null;
  importsequencenumber?: number | null;
  inheritancemask?: number | null;
  isdisabled?: boolean | null;
  modifiedon?: Date | null;
  name?: string | null;
  overriddencreatedon?: Date | null;
  picture?: string | null;
  stockexchange?: string | null;
  tickersymbol?: string | null;
  usergroupid?: string | null;
  utcoffset?: number | null;
  versionnumber?: number | null;
  websiteurl?: string | null;
  workflowsuspended?: boolean | null;
}
interface BusinessUnit_Relationships {
  business_unit_accounts?: Account_Result[] | null;
  business_unit_appointment_activities?: Appointment_Result[] | null;
  business_unit_bookableresource?: BookableResource_Result[] | null;
  business_unit_bookableresourcebooking?: BookableResourceBooking_Result[] | null;
  business_unit_bookingstatus?: BookingStatus_Result[] | null;
  business_unit_connections?: Connection_Result[] | null;
  business_unit_contacts?: Contact_Result[] | null;
  business_unit_email_activities?: Email_Result[] | null;
  business_unit_incident_resolution_activities?: IncidentResolution_Result[] | null;
  business_unit_incidents?: Incident_Result[] | null;
  business_unit_msdyn_customerasset?: msdyn_customerasset_Result[] | null;
  business_unit_msdyn_customerassetcategory?: msdyn_customerassetcategory_Result[] | null;
  business_unit_msdyn_functionallocation?: msdyn_FunctionalLocation_Result[] | null;
  business_unit_msdyn_incidenttype?: msdyn_incidenttype_Result[] | null;
  business_unit_msdyn_incidenttypeservicetask?: msdyn_incidenttypeservicetask_Result[] | null;
  business_unit_msdyn_servicetasktype?: msdyn_servicetasktype_Result[] | null;
  business_unit_msdyn_workorder?: msdyn_workorder_Result[] | null;
  business_unit_msdyn_workorderservicetask?: msdyn_workorderservicetask_Result[] | null;
  business_unit_ovs_finding?: ovs_Finding_Result[] | null;
  business_unit_ovs_operation?: ovs_operation_Result[] | null;
  business_unit_ovs_operationtype?: ovs_operationtype_Result[] | null;
  business_unit_ovs_questionnaire?: ovs_Questionnaire_Result[] | null;
  business_unit_parent_business_unit?: BusinessUnit_Result[] | null;
  business_unit_postfollows?: PostFollow_Result[] | null;
  business_unit_service_appointments?: ServiceAppointment_Result[] | null;
  business_unit_system_users?: SystemUser_Result[] | null;
  business_unit_tc_tcfiscalquarter?: tc_TCFiscalQuarter_Result[] | null;
  business_unit_tc_tcfiscalyear?: tc_TCFiscalYear_Result[] | null;
  business_unit_teams?: Team_Result[] | null;
  business_unit_ts_action?: ts_action_Result[] | null;
  business_unit_ts_actionfinding?: ts_ActionFinding_Result[] | null;
  business_unit_ts_aircraft?: ts_aircraft_Result[] | null;
  business_unit_ts_assessmentscorethredshots?: ts_assessmentscorethredshots_Result[] | null;
  business_unit_ts_canceledinspectionjustification?: ts_canceledinspectionjustification_Result[] | null;
  business_unit_ts_case?: ts_case_Result[] | null;
  business_unit_ts_causefinding?: ts_causefinding_Result[] | null;
  business_unit_ts_entityrisk?: ts_EntityRisk_Result[] | null;
  business_unit_ts_entityriskfrequency?: ts_EntityRiskFrequency_Result[] | null;
  business_unit_ts_incompleteworkorderreason?: ts_IncompleteWorkOrderReason_Result[] | null;
  business_unit_ts_infraction?: ts_infraction_Result[] | null;
  business_unit_ts_inspectionhours?: ts_InspectionHours_Result[] | null;
  business_unit_ts_nonoversightactivity?: ts_nonoversightactivity_Result[] | null;
  business_unit_ts_operationactivity?: ts_OperationActivity_Result[] | null;
  business_unit_ts_operationactivityriskscores?: ts_OperationActivityRiskScores_Result[] | null;
  business_unit_ts_operationcontact?: ts_operationcontact_Result[] | null;
  business_unit_ts_operationriskassessment?: ts_operationriskassessment_Result[] | null;
  business_unit_ts_plan?: ts_Plan_Result[] | null;
  business_unit_ts_planningdata?: ts_PlanningData_Result[] | null;
  business_unit_ts_planningsettings?: ts_planningsettings_Result[] | null;
  business_unit_ts_questionnaireresponse?: ts_questionnaireresponse_Result[] | null;
  business_unit_ts_questionnaireversion?: ts_questionnaireversion_Result[] | null;
  business_unit_ts_riskcategory?: ts_RiskCategory_Result[] | null;
  business_unit_ts_role?: ts_role_Result[] | null;
  business_unit_ts_securityincident?: ts_securityincident_Result[] | null;
  business_unit_ts_securityincidenttype?: ts_securityincidenttype_Result[] | null;
  business_unit_ts_site?: ts_site_Result[] | null;
  business_unit_ts_suggestedinspection?: ts_SuggestedInspection_Result[] | null;
  business_unit_ts_teamplanningdata?: ts_TeamPlanningData_Result[] | null;
  business_unit_ts_teamplanninginspectorhours?: ts_TeamPlanningInspectorHours_Result[] | null;
  business_unit_ts_trip?: ts_trip_Result[] | null;
  business_unit_ts_userregistration?: ts_UserRegistration_Result[] | null;
  business_unit_ts_workordercreationwizard?: ts_workordercreationwizard_Result[] | null;
  business_unit_ts_workordertimetracking?: ts_workordertimetracking_Result[] | null;
  msdyn_Team?: Team_Result | null;
  ts_UserRegistration_BusinessUnit_Business?: ts_UserRegistration_Result[] | null;
  ts_businessunit_ts_nonoversightactivity_Program?: ts_nonoversightactivity_Result[] | null;
  ts_enforcementaction_businessunit_owningbusinessunit?: ts_enforcementaction_Result[] | null;
}
interface BusinessUnit extends BusinessUnit_Base, BusinessUnit_Relationships {
  calendarid_bind$calendars?: string | null;
  msdyn_Team_bind$teams?: string | null;
  msdyn_warehouse_bind$msdyn_warehouses?: string | null;
  parentbusinessunitid_bind$businessunits?: string | null;
  transactioncurrencyid_bind$transactioncurrencies?: string | null;
}
interface BusinessUnit_Create extends BusinessUnit {
}
interface BusinessUnit_Update extends BusinessUnit {
}
interface BusinessUnit_Select {
  address1_addressid: WebAttribute<BusinessUnit_Select, { address1_addressid: string | null }, {  }>;
  address1_addresstypecode: WebAttribute<BusinessUnit_Select, { address1_addresstypecode: businessunit_address1_addresstypecode | null }, { address1_addresstypecode_formatted?: string }>;
  address1_city: WebAttribute<BusinessUnit_Select, { address1_city: string | null }, {  }>;
  address1_country: WebAttribute<BusinessUnit_Select, { address1_country: string | null }, {  }>;
  address1_county: WebAttribute<BusinessUnit_Select, { address1_county: string | null }, {  }>;
  address1_fax: WebAttribute<BusinessUnit_Select, { address1_fax: string | null }, {  }>;
  address1_latitude: WebAttribute<BusinessUnit_Select, { address1_latitude: number | null }, {  }>;
  address1_line1: WebAttribute<BusinessUnit_Select, { address1_line1: string | null }, {  }>;
  address1_line2: WebAttribute<BusinessUnit_Select, { address1_line2: string | null }, {  }>;
  address1_line3: WebAttribute<BusinessUnit_Select, { address1_line3: string | null }, {  }>;
  address1_longitude: WebAttribute<BusinessUnit_Select, { address1_longitude: number | null }, {  }>;
  address1_name: WebAttribute<BusinessUnit_Select, { address1_name: string | null }, {  }>;
  address1_postalcode: WebAttribute<BusinessUnit_Select, { address1_postalcode: string | null }, {  }>;
  address1_postofficebox: WebAttribute<BusinessUnit_Select, { address1_postofficebox: string | null }, {  }>;
  address1_shippingmethodcode: WebAttribute<BusinessUnit_Select, { address1_shippingmethodcode: businessunit_address1_shippingmethodcode | null }, { address1_shippingmethodcode_formatted?: string }>;
  address1_stateorprovince: WebAttribute<BusinessUnit_Select, { address1_stateorprovince: string | null }, {  }>;
  address1_telephone1: WebAttribute<BusinessUnit_Select, { address1_telephone1: string | null }, {  }>;
  address1_telephone2: WebAttribute<BusinessUnit_Select, { address1_telephone2: string | null }, {  }>;
  address1_telephone3: WebAttribute<BusinessUnit_Select, { address1_telephone3: string | null }, {  }>;
  address1_upszone: WebAttribute<BusinessUnit_Select, { address1_upszone: string | null }, {  }>;
  address1_utcoffset: WebAttribute<BusinessUnit_Select, { address1_utcoffset: number | null }, {  }>;
  address2_addressid: WebAttribute<BusinessUnit_Select, { address2_addressid: string | null }, {  }>;
  address2_addresstypecode: WebAttribute<BusinessUnit_Select, { address2_addresstypecode: businessunit_address2_addresstypecode | null }, { address2_addresstypecode_formatted?: string }>;
  address2_city: WebAttribute<BusinessUnit_Select, { address2_city: string | null }, {  }>;
  address2_country: WebAttribute<BusinessUnit_Select, { address2_country: string | null }, {  }>;
  address2_county: WebAttribute<BusinessUnit_Select, { address2_county: string | null }, {  }>;
  address2_fax: WebAttribute<BusinessUnit_Select, { address2_fax: string | null }, {  }>;
  address2_latitude: WebAttribute<BusinessUnit_Select, { address2_latitude: number | null }, {  }>;
  address2_line1: WebAttribute<BusinessUnit_Select, { address2_line1: string | null }, {  }>;
  address2_line2: WebAttribute<BusinessUnit_Select, { address2_line2: string | null }, {  }>;
  address2_line3: WebAttribute<BusinessUnit_Select, { address2_line3: string | null }, {  }>;
  address2_longitude: WebAttribute<BusinessUnit_Select, { address2_longitude: number | null }, {  }>;
  address2_name: WebAttribute<BusinessUnit_Select, { address2_name: string | null }, {  }>;
  address2_postalcode: WebAttribute<BusinessUnit_Select, { address2_postalcode: string | null }, {  }>;
  address2_postofficebox: WebAttribute<BusinessUnit_Select, { address2_postofficebox: string | null }, {  }>;
  address2_shippingmethodcode: WebAttribute<BusinessUnit_Select, { address2_shippingmethodcode: businessunit_address2_shippingmethodcode | null }, { address2_shippingmethodcode_formatted?: string }>;
  address2_stateorprovince: WebAttribute<BusinessUnit_Select, { address2_stateorprovince: string | null }, {  }>;
  address2_telephone1: WebAttribute<BusinessUnit_Select, { address2_telephone1: string | null }, {  }>;
  address2_telephone2: WebAttribute<BusinessUnit_Select, { address2_telephone2: string | null }, {  }>;
  address2_telephone3: WebAttribute<BusinessUnit_Select, { address2_telephone3: string | null }, {  }>;
  address2_upszone: WebAttribute<BusinessUnit_Select, { address2_upszone: string | null }, {  }>;
  address2_utcoffset: WebAttribute<BusinessUnit_Select, { address2_utcoffset: number | null }, {  }>;
  businessunitid: WebAttribute<BusinessUnit_Select, { businessunitid: string | null }, {  }>;
  calendarid_guid: WebAttribute<BusinessUnit_Select, { calendarid_guid: string | null }, { calendarid_formatted?: string }>;
  costcenter: WebAttribute<BusinessUnit_Select, { costcenter: string | null }, {  }>;
  createdby_guid: WebAttribute<BusinessUnit_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
  createdon: WebAttribute<BusinessUnit_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
  createdonbehalfby_guid: WebAttribute<BusinessUnit_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
  creditlimit: WebAttribute<BusinessUnit_Select, { creditlimit: number | null }, {  }>;
  description: WebAttribute<BusinessUnit_Select, { description: string | null }, {  }>;
  disabledreason: WebAttribute<BusinessUnit_Select, { disabledreason: string | null }, {  }>;
  divisionname: WebAttribute<BusinessUnit_Select, { divisionname: string | null }, {  }>;
  emailaddress: WebAttribute<BusinessUnit_Select, { emailaddress: string | null }, {  }>;
  exchangerate: WebAttribute<BusinessUnit_Select, { exchangerate: number | null }, {  }>;
  fileasname: WebAttribute<BusinessUnit_Select, { fileasname: string | null }, {  }>;
  ftpsiteurl: WebAttribute<BusinessUnit_Select, { ftpsiteurl: string | null }, {  }>;
  importsequencenumber: WebAttribute<BusinessUnit_Select, { importsequencenumber: number | null }, {  }>;
  inheritancemask: WebAttribute<BusinessUnit_Select, { inheritancemask: number | null }, {  }>;
  isdisabled: WebAttribute<BusinessUnit_Select, { isdisabled: boolean | null }, {  }>;
  modifiedby_guid: WebAttribute<BusinessUnit_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
  modifiedon: WebAttribute<BusinessUnit_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
  modifiedonbehalfby_guid: WebAttribute<BusinessUnit_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
  msdyn_team_guid: WebAttribute<BusinessUnit_Select, { msdyn_team_guid: string | null }, { msdyn_team_formatted?: string }>;
  msdyn_warehouse_guid: WebAttribute<BusinessUnit_Select, { msdyn_warehouse_guid: string | null }, { msdyn_warehouse_formatted?: string }>;
  name: WebAttribute<BusinessUnit_Select, { name: string | null }, {  }>;
  organizationid_guid: WebAttribute<BusinessUnit_Select, { organizationid_guid: string | null }, { organizationid_formatted?: string }>;
  overriddencreatedon: WebAttribute<BusinessUnit_Select, { overriddencreatedon: Date | null }, { overriddencreatedon_formatted?: string }>;
  parentbusinessunitid_guid: WebAttribute<BusinessUnit_Select, { parentbusinessunitid_guid: string | null }, { parentbusinessunitid_formatted?: string }>;
  picture: WebAttribute<BusinessUnit_Select, { picture: string | null }, {  }>;
  stockexchange: WebAttribute<BusinessUnit_Select, { stockexchange: string | null }, {  }>;
  tickersymbol: WebAttribute<BusinessUnit_Select, { tickersymbol: string | null }, {  }>;
  transactioncurrencyid_guid: WebAttribute<BusinessUnit_Select, { transactioncurrencyid_guid: string | null }, { transactioncurrencyid_formatted?: string }>;
  usergroupid: WebAttribute<BusinessUnit_Select, { usergroupid: string | null }, {  }>;
  utcoffset: WebAttribute<BusinessUnit_Select, { utcoffset: number | null }, {  }>;
  versionnumber: WebAttribute<BusinessUnit_Select, { versionnumber: number | null }, {  }>;
  websiteurl: WebAttribute<BusinessUnit_Select, { websiteurl: string | null }, {  }>;
  workflowsuspended: WebAttribute<BusinessUnit_Select, { workflowsuspended: boolean | null }, {  }>;
}
interface BusinessUnit_Filter {
  address1_addressid: XQW.Guid;
  address1_addresstypecode: businessunit_address1_addresstypecode;
  address1_city: string;
  address1_country: string;
  address1_county: string;
  address1_fax: string;
  address1_latitude: number;
  address1_line1: string;
  address1_line2: string;
  address1_line3: string;
  address1_longitude: number;
  address1_name: string;
  address1_postalcode: string;
  address1_postofficebox: string;
  address1_shippingmethodcode: businessunit_address1_shippingmethodcode;
  address1_stateorprovince: string;
  address1_telephone1: string;
  address1_telephone2: string;
  address1_telephone3: string;
  address1_upszone: string;
  address1_utcoffset: number;
  address2_addressid: XQW.Guid;
  address2_addresstypecode: businessunit_address2_addresstypecode;
  address2_city: string;
  address2_country: string;
  address2_county: string;
  address2_fax: string;
  address2_latitude: number;
  address2_line1: string;
  address2_line2: string;
  address2_line3: string;
  address2_longitude: number;
  address2_name: string;
  address2_postalcode: string;
  address2_postofficebox: string;
  address2_shippingmethodcode: businessunit_address2_shippingmethodcode;
  address2_stateorprovince: string;
  address2_telephone1: string;
  address2_telephone2: string;
  address2_telephone3: string;
  address2_upszone: string;
  address2_utcoffset: number;
  businessunitid: XQW.Guid;
  calendarid_guid: XQW.Guid;
  costcenter: string;
  createdby_guid: XQW.Guid;
  createdon: Date;
  createdonbehalfby_guid: XQW.Guid;
  creditlimit: number;
  description: string;
  disabledreason: string;
  divisionname: string;
  emailaddress: string;
  exchangerate: any;
  fileasname: string;
  ftpsiteurl: string;
  importsequencenumber: number;
  inheritancemask: number;
  isdisabled: boolean;
  modifiedby_guid: XQW.Guid;
  modifiedon: Date;
  modifiedonbehalfby_guid: XQW.Guid;
  msdyn_team_guid: XQW.Guid;
  msdyn_warehouse_guid: XQW.Guid;
  name: string;
  organizationid_guid: XQW.Guid;
  overriddencreatedon: Date;
  parentbusinessunitid_guid: XQW.Guid;
  picture: string;
  stockexchange: string;
  tickersymbol: string;
  transactioncurrencyid_guid: XQW.Guid;
  usergroupid: XQW.Guid;
  utcoffset: number;
  versionnumber: number;
  websiteurl: string;
  workflowsuspended: boolean;
}
interface BusinessUnit_Expand {
  business_unit_accounts: WebExpand<BusinessUnit_Expand, Account_Select, Account_Filter, { business_unit_accounts: Account_Result[] }>;
  business_unit_appointment_activities: WebExpand<BusinessUnit_Expand, Appointment_Select, Appointment_Filter, { business_unit_appointment_activities: Appointment_Result[] }>;
  business_unit_bookableresource: WebExpand<BusinessUnit_Expand, BookableResource_Select, BookableResource_Filter, { business_unit_bookableresource: BookableResource_Result[] }>;
  business_unit_bookableresourcebooking: WebExpand<BusinessUnit_Expand, BookableResourceBooking_Select, BookableResourceBooking_Filter, { business_unit_bookableresourcebooking: BookableResourceBooking_Result[] }>;
  business_unit_bookingstatus: WebExpand<BusinessUnit_Expand, BookingStatus_Select, BookingStatus_Filter, { business_unit_bookingstatus: BookingStatus_Result[] }>;
  business_unit_connections: WebExpand<BusinessUnit_Expand, Connection_Select, Connection_Filter, { business_unit_connections: Connection_Result[] }>;
  business_unit_contacts: WebExpand<BusinessUnit_Expand, Contact_Select, Contact_Filter, { business_unit_contacts: Contact_Result[] }>;
  business_unit_email_activities: WebExpand<BusinessUnit_Expand, Email_Select, Email_Filter, { business_unit_email_activities: Email_Result[] }>;
  business_unit_incident_resolution_activities: WebExpand<BusinessUnit_Expand, IncidentResolution_Select, IncidentResolution_Filter, { business_unit_incident_resolution_activities: IncidentResolution_Result[] }>;
  business_unit_incidents: WebExpand<BusinessUnit_Expand, Incident_Select, Incident_Filter, { business_unit_incidents: Incident_Result[] }>;
  business_unit_msdyn_customerasset: WebExpand<BusinessUnit_Expand, msdyn_customerasset_Select, msdyn_customerasset_Filter, { business_unit_msdyn_customerasset: msdyn_customerasset_Result[] }>;
  business_unit_msdyn_customerassetcategory: WebExpand<BusinessUnit_Expand, msdyn_customerassetcategory_Select, msdyn_customerassetcategory_Filter, { business_unit_msdyn_customerassetcategory: msdyn_customerassetcategory_Result[] }>;
  business_unit_msdyn_functionallocation: WebExpand<BusinessUnit_Expand, msdyn_FunctionalLocation_Select, msdyn_FunctionalLocation_Filter, { business_unit_msdyn_functionallocation: msdyn_FunctionalLocation_Result[] }>;
  business_unit_msdyn_incidenttype: WebExpand<BusinessUnit_Expand, msdyn_incidenttype_Select, msdyn_incidenttype_Filter, { business_unit_msdyn_incidenttype: msdyn_incidenttype_Result[] }>;
  business_unit_msdyn_incidenttypeservicetask: WebExpand<BusinessUnit_Expand, msdyn_incidenttypeservicetask_Select, msdyn_incidenttypeservicetask_Filter, { business_unit_msdyn_incidenttypeservicetask: msdyn_incidenttypeservicetask_Result[] }>;
  business_unit_msdyn_servicetasktype: WebExpand<BusinessUnit_Expand, msdyn_servicetasktype_Select, msdyn_servicetasktype_Filter, { business_unit_msdyn_servicetasktype: msdyn_servicetasktype_Result[] }>;
  business_unit_msdyn_workorder: WebExpand<BusinessUnit_Expand, msdyn_workorder_Select, msdyn_workorder_Filter, { business_unit_msdyn_workorder: msdyn_workorder_Result[] }>;
  business_unit_msdyn_workorderservicetask: WebExpand<BusinessUnit_Expand, msdyn_workorderservicetask_Select, msdyn_workorderservicetask_Filter, { business_unit_msdyn_workorderservicetask: msdyn_workorderservicetask_Result[] }>;
  business_unit_ovs_finding: WebExpand<BusinessUnit_Expand, ovs_Finding_Select, ovs_Finding_Filter, { business_unit_ovs_finding: ovs_Finding_Result[] }>;
  business_unit_ovs_operation: WebExpand<BusinessUnit_Expand, ovs_operation_Select, ovs_operation_Filter, { business_unit_ovs_operation: ovs_operation_Result[] }>;
  business_unit_ovs_operationtype: WebExpand<BusinessUnit_Expand, ovs_operationtype_Select, ovs_operationtype_Filter, { business_unit_ovs_operationtype: ovs_operationtype_Result[] }>;
  business_unit_ovs_questionnaire: WebExpand<BusinessUnit_Expand, ovs_Questionnaire_Select, ovs_Questionnaire_Filter, { business_unit_ovs_questionnaire: ovs_Questionnaire_Result[] }>;
  business_unit_parent_business_unit: WebExpand<BusinessUnit_Expand, BusinessUnit_Select, BusinessUnit_Filter, { business_unit_parent_business_unit: BusinessUnit_Result[] }>;
  business_unit_postfollows: WebExpand<BusinessUnit_Expand, PostFollow_Select, PostFollow_Filter, { business_unit_postfollows: PostFollow_Result[] }>;
  business_unit_service_appointments: WebExpand<BusinessUnit_Expand, ServiceAppointment_Select, ServiceAppointment_Filter, { business_unit_service_appointments: ServiceAppointment_Result[] }>;
  business_unit_system_users: WebExpand<BusinessUnit_Expand, SystemUser_Select, SystemUser_Filter, { business_unit_system_users: SystemUser_Result[] }>;
  business_unit_tc_tcfiscalquarter: WebExpand<BusinessUnit_Expand, tc_TCFiscalQuarter_Select, tc_TCFiscalQuarter_Filter, { business_unit_tc_tcfiscalquarter: tc_TCFiscalQuarter_Result[] }>;
  business_unit_tc_tcfiscalyear: WebExpand<BusinessUnit_Expand, tc_TCFiscalYear_Select, tc_TCFiscalYear_Filter, { business_unit_tc_tcfiscalyear: tc_TCFiscalYear_Result[] }>;
  business_unit_teams: WebExpand<BusinessUnit_Expand, Team_Select, Team_Filter, { business_unit_teams: Team_Result[] }>;
  business_unit_ts_action: WebExpand<BusinessUnit_Expand, ts_action_Select, ts_action_Filter, { business_unit_ts_action: ts_action_Result[] }>;
  business_unit_ts_actionfinding: WebExpand<BusinessUnit_Expand, ts_ActionFinding_Select, ts_ActionFinding_Filter, { business_unit_ts_actionfinding: ts_ActionFinding_Result[] }>;
  business_unit_ts_aircraft: WebExpand<BusinessUnit_Expand, ts_aircraft_Select, ts_aircraft_Filter, { business_unit_ts_aircraft: ts_aircraft_Result[] }>;
  business_unit_ts_assessmentscorethredshots: WebExpand<BusinessUnit_Expand, ts_assessmentscorethredshots_Select, ts_assessmentscorethredshots_Filter, { business_unit_ts_assessmentscorethredshots: ts_assessmentscorethredshots_Result[] }>;
  business_unit_ts_canceledinspectionjustification: WebExpand<BusinessUnit_Expand, ts_canceledinspectionjustification_Select, ts_canceledinspectionjustification_Filter, { business_unit_ts_canceledinspectionjustification: ts_canceledinspectionjustification_Result[] }>;
  business_unit_ts_case: WebExpand<BusinessUnit_Expand, ts_case_Select, ts_case_Filter, { business_unit_ts_case: ts_case_Result[] }>;
  business_unit_ts_causefinding: WebExpand<BusinessUnit_Expand, ts_causefinding_Select, ts_causefinding_Filter, { business_unit_ts_causefinding: ts_causefinding_Result[] }>;
  business_unit_ts_entityrisk: WebExpand<BusinessUnit_Expand, ts_EntityRisk_Select, ts_EntityRisk_Filter, { business_unit_ts_entityrisk: ts_EntityRisk_Result[] }>;
  business_unit_ts_entityriskfrequency: WebExpand<BusinessUnit_Expand, ts_EntityRiskFrequency_Select, ts_EntityRiskFrequency_Filter, { business_unit_ts_entityriskfrequency: ts_EntityRiskFrequency_Result[] }>;
  business_unit_ts_incompleteworkorderreason: WebExpand<BusinessUnit_Expand, ts_IncompleteWorkOrderReason_Select, ts_IncompleteWorkOrderReason_Filter, { business_unit_ts_incompleteworkorderreason: ts_IncompleteWorkOrderReason_Result[] }>;
  business_unit_ts_infraction: WebExpand<BusinessUnit_Expand, ts_infraction_Select, ts_infraction_Filter, { business_unit_ts_infraction: ts_infraction_Result[] }>;
  business_unit_ts_inspectionhours: WebExpand<BusinessUnit_Expand, ts_InspectionHours_Select, ts_InspectionHours_Filter, { business_unit_ts_inspectionhours: ts_InspectionHours_Result[] }>;
  business_unit_ts_nonoversightactivity: WebExpand<BusinessUnit_Expand, ts_nonoversightactivity_Select, ts_nonoversightactivity_Filter, { business_unit_ts_nonoversightactivity: ts_nonoversightactivity_Result[] }>;
  business_unit_ts_operationactivity: WebExpand<BusinessUnit_Expand, ts_OperationActivity_Select, ts_OperationActivity_Filter, { business_unit_ts_operationactivity: ts_OperationActivity_Result[] }>;
  business_unit_ts_operationactivityriskscores: WebExpand<BusinessUnit_Expand, ts_OperationActivityRiskScores_Select, ts_OperationActivityRiskScores_Filter, { business_unit_ts_operationactivityriskscores: ts_OperationActivityRiskScores_Result[] }>;
  business_unit_ts_operationcontact: WebExpand<BusinessUnit_Expand, ts_operationcontact_Select, ts_operationcontact_Filter, { business_unit_ts_operationcontact: ts_operationcontact_Result[] }>;
  business_unit_ts_operationriskassessment: WebExpand<BusinessUnit_Expand, ts_operationriskassessment_Select, ts_operationriskassessment_Filter, { business_unit_ts_operationriskassessment: ts_operationriskassessment_Result[] }>;
  business_unit_ts_plan: WebExpand<BusinessUnit_Expand, ts_Plan_Select, ts_Plan_Filter, { business_unit_ts_plan: ts_Plan_Result[] }>;
  business_unit_ts_planningdata: WebExpand<BusinessUnit_Expand, ts_PlanningData_Select, ts_PlanningData_Filter, { business_unit_ts_planningdata: ts_PlanningData_Result[] }>;
  business_unit_ts_planningsettings: WebExpand<BusinessUnit_Expand, ts_planningsettings_Select, ts_planningsettings_Filter, { business_unit_ts_planningsettings: ts_planningsettings_Result[] }>;
  business_unit_ts_questionnaireresponse: WebExpand<BusinessUnit_Expand, ts_questionnaireresponse_Select, ts_questionnaireresponse_Filter, { business_unit_ts_questionnaireresponse: ts_questionnaireresponse_Result[] }>;
  business_unit_ts_questionnaireversion: WebExpand<BusinessUnit_Expand, ts_questionnaireversion_Select, ts_questionnaireversion_Filter, { business_unit_ts_questionnaireversion: ts_questionnaireversion_Result[] }>;
  business_unit_ts_riskcategory: WebExpand<BusinessUnit_Expand, ts_RiskCategory_Select, ts_RiskCategory_Filter, { business_unit_ts_riskcategory: ts_RiskCategory_Result[] }>;
  business_unit_ts_role: WebExpand<BusinessUnit_Expand, ts_role_Select, ts_role_Filter, { business_unit_ts_role: ts_role_Result[] }>;
  business_unit_ts_securityincident: WebExpand<BusinessUnit_Expand, ts_securityincident_Select, ts_securityincident_Filter, { business_unit_ts_securityincident: ts_securityincident_Result[] }>;
  business_unit_ts_securityincidenttype: WebExpand<BusinessUnit_Expand, ts_securityincidenttype_Select, ts_securityincidenttype_Filter, { business_unit_ts_securityincidenttype: ts_securityincidenttype_Result[] }>;
  business_unit_ts_site: WebExpand<BusinessUnit_Expand, ts_site_Select, ts_site_Filter, { business_unit_ts_site: ts_site_Result[] }>;
  business_unit_ts_suggestedinspection: WebExpand<BusinessUnit_Expand, ts_SuggestedInspection_Select, ts_SuggestedInspection_Filter, { business_unit_ts_suggestedinspection: ts_SuggestedInspection_Result[] }>;
  business_unit_ts_teamplanningdata: WebExpand<BusinessUnit_Expand, ts_TeamPlanningData_Select, ts_TeamPlanningData_Filter, { business_unit_ts_teamplanningdata: ts_TeamPlanningData_Result[] }>;
  business_unit_ts_teamplanninginspectorhours: WebExpand<BusinessUnit_Expand, ts_TeamPlanningInspectorHours_Select, ts_TeamPlanningInspectorHours_Filter, { business_unit_ts_teamplanninginspectorhours: ts_TeamPlanningInspectorHours_Result[] }>;
  business_unit_ts_trip: WebExpand<BusinessUnit_Expand, ts_trip_Select, ts_trip_Filter, { business_unit_ts_trip: ts_trip_Result[] }>;
  business_unit_ts_userregistration: WebExpand<BusinessUnit_Expand, ts_UserRegistration_Select, ts_UserRegistration_Filter, { business_unit_ts_userregistration: ts_UserRegistration_Result[] }>;
  business_unit_ts_workordercreationwizard: WebExpand<BusinessUnit_Expand, ts_workordercreationwizard_Select, ts_workordercreationwizard_Filter, { business_unit_ts_workordercreationwizard: ts_workordercreationwizard_Result[] }>;
  business_unit_ts_workordertimetracking: WebExpand<BusinessUnit_Expand, ts_workordertimetracking_Select, ts_workordertimetracking_Filter, { business_unit_ts_workordertimetracking: ts_workordertimetracking_Result[] }>;
  createdby: WebExpand<BusinessUnit_Expand, SystemUser_Select, SystemUser_Filter, { createdby: SystemUser_Result }>;
  createdonbehalfby: WebExpand<BusinessUnit_Expand, SystemUser_Select, SystemUser_Filter, { createdonbehalfby: SystemUser_Result }>;
  modifiedby: WebExpand<BusinessUnit_Expand, SystemUser_Select, SystemUser_Filter, { modifiedby: SystemUser_Result }>;
  modifiedonbehalfby: WebExpand<BusinessUnit_Expand, SystemUser_Select, SystemUser_Filter, { modifiedonbehalfby: SystemUser_Result }>;
  msdyn_Team: WebExpand<BusinessUnit_Expand, Team_Select, Team_Filter, { msdyn_Team: Team_Result }>;
  parentbusinessunitid: WebExpand<BusinessUnit_Expand, BusinessUnit_Select, BusinessUnit_Filter, { parentbusinessunitid: BusinessUnit_Result }>;
  ts_UserRegistration_BusinessUnit_Business: WebExpand<BusinessUnit_Expand, ts_UserRegistration_Select, ts_UserRegistration_Filter, { ts_UserRegistration_BusinessUnit_Business: ts_UserRegistration_Result[] }>;
  ts_businessunit_ts_nonoversightactivity_Program: WebExpand<BusinessUnit_Expand, ts_nonoversightactivity_Select, ts_nonoversightactivity_Filter, { ts_businessunit_ts_nonoversightactivity_Program: ts_nonoversightactivity_Result[] }>;
  ts_enforcementaction_businessunit_owningbusinessunit: WebExpand<BusinessUnit_Expand, ts_enforcementaction_Select, ts_enforcementaction_Filter, { ts_enforcementaction_businessunit_owningbusinessunit: ts_enforcementaction_Result[] }>;
}
interface BusinessUnit_FormattedResult {
  address1_addresstypecode_formatted?: string;
  address1_shippingmethodcode_formatted?: string;
  address2_addresstypecode_formatted?: string;
  address2_shippingmethodcode_formatted?: string;
  calendarid_formatted?: string;
  createdby_formatted?: string;
  createdon_formatted?: string;
  createdonbehalfby_formatted?: string;
  modifiedby_formatted?: string;
  modifiedon_formatted?: string;
  modifiedonbehalfby_formatted?: string;
  msdyn_team_formatted?: string;
  msdyn_warehouse_formatted?: string;
  organizationid_formatted?: string;
  overriddencreatedon_formatted?: string;
  parentbusinessunitid_formatted?: string;
  transactioncurrencyid_formatted?: string;
}
interface BusinessUnit_Result extends BusinessUnit_Base, BusinessUnit_Relationships {
  "@odata.etag": string;
  calendarid_guid: string | null;
  createdby_guid: string | null;
  createdonbehalfby_guid: string | null;
  modifiedby_guid: string | null;
  modifiedonbehalfby_guid: string | null;
  msdyn_team_guid: string | null;
  msdyn_warehouse_guid: string | null;
  organizationid_guid: string | null;
  parentbusinessunitid_guid: string | null;
  transactioncurrencyid_guid: string | null;
}
interface BusinessUnit_RelatedOne {
  createdby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  createdonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  msdyn_Team: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  parentbusinessunitid: WebMappingRetrieve<BusinessUnit_Select,BusinessUnit_Expand,BusinessUnit_Filter,BusinessUnit_Fixed,BusinessUnit_Result,BusinessUnit_FormattedResult>;
}
interface BusinessUnit_RelatedMany {
  business_unit_accounts: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  business_unit_appointment_activities: WebMappingRetrieve<Appointment_Select,Appointment_Expand,Appointment_Filter,Appointment_Fixed,Appointment_Result,Appointment_FormattedResult>;
  business_unit_bookableresource: WebMappingRetrieve<BookableResource_Select,BookableResource_Expand,BookableResource_Filter,BookableResource_Fixed,BookableResource_Result,BookableResource_FormattedResult>;
  business_unit_bookableresourcebooking: WebMappingRetrieve<BookableResourceBooking_Select,BookableResourceBooking_Expand,BookableResourceBooking_Filter,BookableResourceBooking_Fixed,BookableResourceBooking_Result,BookableResourceBooking_FormattedResult>;
  business_unit_bookingstatus: WebMappingRetrieve<BookingStatus_Select,BookingStatus_Expand,BookingStatus_Filter,BookingStatus_Fixed,BookingStatus_Result,BookingStatus_FormattedResult>;
  business_unit_connections: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  business_unit_contacts: WebMappingRetrieve<Contact_Select,Contact_Expand,Contact_Filter,Contact_Fixed,Contact_Result,Contact_FormattedResult>;
  business_unit_email_activities: WebMappingRetrieve<Email_Select,Email_Expand,Email_Filter,Email_Fixed,Email_Result,Email_FormattedResult>;
  business_unit_incident_resolution_activities: WebMappingRetrieve<IncidentResolution_Select,IncidentResolution_Expand,IncidentResolution_Filter,IncidentResolution_Fixed,IncidentResolution_Result,IncidentResolution_FormattedResult>;
  business_unit_incidents: WebMappingRetrieve<Incident_Select,Incident_Expand,Incident_Filter,Incident_Fixed,Incident_Result,Incident_FormattedResult>;
  business_unit_msdyn_customerasset: WebMappingRetrieve<msdyn_customerasset_Select,msdyn_customerasset_Expand,msdyn_customerasset_Filter,msdyn_customerasset_Fixed,msdyn_customerasset_Result,msdyn_customerasset_FormattedResult>;
  business_unit_msdyn_customerassetcategory: WebMappingRetrieve<msdyn_customerassetcategory_Select,msdyn_customerassetcategory_Expand,msdyn_customerassetcategory_Filter,msdyn_customerassetcategory_Fixed,msdyn_customerassetcategory_Result,msdyn_customerassetcategory_FormattedResult>;
  business_unit_msdyn_functionallocation: WebMappingRetrieve<msdyn_FunctionalLocation_Select,msdyn_FunctionalLocation_Expand,msdyn_FunctionalLocation_Filter,msdyn_FunctionalLocation_Fixed,msdyn_FunctionalLocation_Result,msdyn_FunctionalLocation_FormattedResult>;
  business_unit_msdyn_incidenttype: WebMappingRetrieve<msdyn_incidenttype_Select,msdyn_incidenttype_Expand,msdyn_incidenttype_Filter,msdyn_incidenttype_Fixed,msdyn_incidenttype_Result,msdyn_incidenttype_FormattedResult>;
  business_unit_msdyn_incidenttypeservicetask: WebMappingRetrieve<msdyn_incidenttypeservicetask_Select,msdyn_incidenttypeservicetask_Expand,msdyn_incidenttypeservicetask_Filter,msdyn_incidenttypeservicetask_Fixed,msdyn_incidenttypeservicetask_Result,msdyn_incidenttypeservicetask_FormattedResult>;
  business_unit_msdyn_servicetasktype: WebMappingRetrieve<msdyn_servicetasktype_Select,msdyn_servicetasktype_Expand,msdyn_servicetasktype_Filter,msdyn_servicetasktype_Fixed,msdyn_servicetasktype_Result,msdyn_servicetasktype_FormattedResult>;
  business_unit_msdyn_workorder: WebMappingRetrieve<msdyn_workorder_Select,msdyn_workorder_Expand,msdyn_workorder_Filter,msdyn_workorder_Fixed,msdyn_workorder_Result,msdyn_workorder_FormattedResult>;
  business_unit_msdyn_workorderservicetask: WebMappingRetrieve<msdyn_workorderservicetask_Select,msdyn_workorderservicetask_Expand,msdyn_workorderservicetask_Filter,msdyn_workorderservicetask_Fixed,msdyn_workorderservicetask_Result,msdyn_workorderservicetask_FormattedResult>;
  business_unit_ovs_finding: WebMappingRetrieve<ovs_Finding_Select,ovs_Finding_Expand,ovs_Finding_Filter,ovs_Finding_Fixed,ovs_Finding_Result,ovs_Finding_FormattedResult>;
  business_unit_ovs_operation: WebMappingRetrieve<ovs_operation_Select,ovs_operation_Expand,ovs_operation_Filter,ovs_operation_Fixed,ovs_operation_Result,ovs_operation_FormattedResult>;
  business_unit_ovs_operationtype: WebMappingRetrieve<ovs_operationtype_Select,ovs_operationtype_Expand,ovs_operationtype_Filter,ovs_operationtype_Fixed,ovs_operationtype_Result,ovs_operationtype_FormattedResult>;
  business_unit_ovs_questionnaire: WebMappingRetrieve<ovs_Questionnaire_Select,ovs_Questionnaire_Expand,ovs_Questionnaire_Filter,ovs_Questionnaire_Fixed,ovs_Questionnaire_Result,ovs_Questionnaire_FormattedResult>;
  business_unit_parent_business_unit: WebMappingRetrieve<BusinessUnit_Select,BusinessUnit_Expand,BusinessUnit_Filter,BusinessUnit_Fixed,BusinessUnit_Result,BusinessUnit_FormattedResult>;
  business_unit_postfollows: WebMappingRetrieve<PostFollow_Select,PostFollow_Expand,PostFollow_Filter,PostFollow_Fixed,PostFollow_Result,PostFollow_FormattedResult>;
  business_unit_service_appointments: WebMappingRetrieve<ServiceAppointment_Select,ServiceAppointment_Expand,ServiceAppointment_Filter,ServiceAppointment_Fixed,ServiceAppointment_Result,ServiceAppointment_FormattedResult>;
  business_unit_system_users: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  business_unit_tc_tcfiscalquarter: WebMappingRetrieve<tc_TCFiscalQuarter_Select,tc_TCFiscalQuarter_Expand,tc_TCFiscalQuarter_Filter,tc_TCFiscalQuarter_Fixed,tc_TCFiscalQuarter_Result,tc_TCFiscalQuarter_FormattedResult>;
  business_unit_tc_tcfiscalyear: WebMappingRetrieve<tc_TCFiscalYear_Select,tc_TCFiscalYear_Expand,tc_TCFiscalYear_Filter,tc_TCFiscalYear_Fixed,tc_TCFiscalYear_Result,tc_TCFiscalYear_FormattedResult>;
  business_unit_teams: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  business_unit_ts_action: WebMappingRetrieve<ts_action_Select,ts_action_Expand,ts_action_Filter,ts_action_Fixed,ts_action_Result,ts_action_FormattedResult>;
  business_unit_ts_actionfinding: WebMappingRetrieve<ts_ActionFinding_Select,ts_ActionFinding_Expand,ts_ActionFinding_Filter,ts_ActionFinding_Fixed,ts_ActionFinding_Result,ts_ActionFinding_FormattedResult>;
  business_unit_ts_aircraft: WebMappingRetrieve<ts_aircraft_Select,ts_aircraft_Expand,ts_aircraft_Filter,ts_aircraft_Fixed,ts_aircraft_Result,ts_aircraft_FormattedResult>;
  business_unit_ts_assessmentscorethredshots: WebMappingRetrieve<ts_assessmentscorethredshots_Select,ts_assessmentscorethredshots_Expand,ts_assessmentscorethredshots_Filter,ts_assessmentscorethredshots_Fixed,ts_assessmentscorethredshots_Result,ts_assessmentscorethredshots_FormattedResult>;
  business_unit_ts_canceledinspectionjustification: WebMappingRetrieve<ts_canceledinspectionjustification_Select,ts_canceledinspectionjustification_Expand,ts_canceledinspectionjustification_Filter,ts_canceledinspectionjustification_Fixed,ts_canceledinspectionjustification_Result,ts_canceledinspectionjustification_FormattedResult>;
  business_unit_ts_case: WebMappingRetrieve<ts_case_Select,ts_case_Expand,ts_case_Filter,ts_case_Fixed,ts_case_Result,ts_case_FormattedResult>;
  business_unit_ts_causefinding: WebMappingRetrieve<ts_causefinding_Select,ts_causefinding_Expand,ts_causefinding_Filter,ts_causefinding_Fixed,ts_causefinding_Result,ts_causefinding_FormattedResult>;
  business_unit_ts_entityrisk: WebMappingRetrieve<ts_EntityRisk_Select,ts_EntityRisk_Expand,ts_EntityRisk_Filter,ts_EntityRisk_Fixed,ts_EntityRisk_Result,ts_EntityRisk_FormattedResult>;
  business_unit_ts_entityriskfrequency: WebMappingRetrieve<ts_EntityRiskFrequency_Select,ts_EntityRiskFrequency_Expand,ts_EntityRiskFrequency_Filter,ts_EntityRiskFrequency_Fixed,ts_EntityRiskFrequency_Result,ts_EntityRiskFrequency_FormattedResult>;
  business_unit_ts_incompleteworkorderreason: WebMappingRetrieve<ts_IncompleteWorkOrderReason_Select,ts_IncompleteWorkOrderReason_Expand,ts_IncompleteWorkOrderReason_Filter,ts_IncompleteWorkOrderReason_Fixed,ts_IncompleteWorkOrderReason_Result,ts_IncompleteWorkOrderReason_FormattedResult>;
  business_unit_ts_infraction: WebMappingRetrieve<ts_infraction_Select,ts_infraction_Expand,ts_infraction_Filter,ts_infraction_Fixed,ts_infraction_Result,ts_infraction_FormattedResult>;
  business_unit_ts_inspectionhours: WebMappingRetrieve<ts_InspectionHours_Select,ts_InspectionHours_Expand,ts_InspectionHours_Filter,ts_InspectionHours_Fixed,ts_InspectionHours_Result,ts_InspectionHours_FormattedResult>;
  business_unit_ts_nonoversightactivity: WebMappingRetrieve<ts_nonoversightactivity_Select,ts_nonoversightactivity_Expand,ts_nonoversightactivity_Filter,ts_nonoversightactivity_Fixed,ts_nonoversightactivity_Result,ts_nonoversightactivity_FormattedResult>;
  business_unit_ts_operationactivity: WebMappingRetrieve<ts_OperationActivity_Select,ts_OperationActivity_Expand,ts_OperationActivity_Filter,ts_OperationActivity_Fixed,ts_OperationActivity_Result,ts_OperationActivity_FormattedResult>;
  business_unit_ts_operationactivityriskscores: WebMappingRetrieve<ts_OperationActivityRiskScores_Select,ts_OperationActivityRiskScores_Expand,ts_OperationActivityRiskScores_Filter,ts_OperationActivityRiskScores_Fixed,ts_OperationActivityRiskScores_Result,ts_OperationActivityRiskScores_FormattedResult>;
  business_unit_ts_operationcontact: WebMappingRetrieve<ts_operationcontact_Select,ts_operationcontact_Expand,ts_operationcontact_Filter,ts_operationcontact_Fixed,ts_operationcontact_Result,ts_operationcontact_FormattedResult>;
  business_unit_ts_operationriskassessment: WebMappingRetrieve<ts_operationriskassessment_Select,ts_operationriskassessment_Expand,ts_operationriskassessment_Filter,ts_operationriskassessment_Fixed,ts_operationriskassessment_Result,ts_operationriskassessment_FormattedResult>;
  business_unit_ts_plan: WebMappingRetrieve<ts_Plan_Select,ts_Plan_Expand,ts_Plan_Filter,ts_Plan_Fixed,ts_Plan_Result,ts_Plan_FormattedResult>;
  business_unit_ts_planningdata: WebMappingRetrieve<ts_PlanningData_Select,ts_PlanningData_Expand,ts_PlanningData_Filter,ts_PlanningData_Fixed,ts_PlanningData_Result,ts_PlanningData_FormattedResult>;
  business_unit_ts_planningsettings: WebMappingRetrieve<ts_planningsettings_Select,ts_planningsettings_Expand,ts_planningsettings_Filter,ts_planningsettings_Fixed,ts_planningsettings_Result,ts_planningsettings_FormattedResult>;
  business_unit_ts_questionnaireresponse: WebMappingRetrieve<ts_questionnaireresponse_Select,ts_questionnaireresponse_Expand,ts_questionnaireresponse_Filter,ts_questionnaireresponse_Fixed,ts_questionnaireresponse_Result,ts_questionnaireresponse_FormattedResult>;
  business_unit_ts_questionnaireversion: WebMappingRetrieve<ts_questionnaireversion_Select,ts_questionnaireversion_Expand,ts_questionnaireversion_Filter,ts_questionnaireversion_Fixed,ts_questionnaireversion_Result,ts_questionnaireversion_FormattedResult>;
  business_unit_ts_riskcategory: WebMappingRetrieve<ts_RiskCategory_Select,ts_RiskCategory_Expand,ts_RiskCategory_Filter,ts_RiskCategory_Fixed,ts_RiskCategory_Result,ts_RiskCategory_FormattedResult>;
  business_unit_ts_role: WebMappingRetrieve<ts_role_Select,ts_role_Expand,ts_role_Filter,ts_role_Fixed,ts_role_Result,ts_role_FormattedResult>;
  business_unit_ts_securityincident: WebMappingRetrieve<ts_securityincident_Select,ts_securityincident_Expand,ts_securityincident_Filter,ts_securityincident_Fixed,ts_securityincident_Result,ts_securityincident_FormattedResult>;
  business_unit_ts_securityincidenttype: WebMappingRetrieve<ts_securityincidenttype_Select,ts_securityincidenttype_Expand,ts_securityincidenttype_Filter,ts_securityincidenttype_Fixed,ts_securityincidenttype_Result,ts_securityincidenttype_FormattedResult>;
  business_unit_ts_site: WebMappingRetrieve<ts_site_Select,ts_site_Expand,ts_site_Filter,ts_site_Fixed,ts_site_Result,ts_site_FormattedResult>;
  business_unit_ts_suggestedinspection: WebMappingRetrieve<ts_SuggestedInspection_Select,ts_SuggestedInspection_Expand,ts_SuggestedInspection_Filter,ts_SuggestedInspection_Fixed,ts_SuggestedInspection_Result,ts_SuggestedInspection_FormattedResult>;
  business_unit_ts_teamplanningdata: WebMappingRetrieve<ts_TeamPlanningData_Select,ts_TeamPlanningData_Expand,ts_TeamPlanningData_Filter,ts_TeamPlanningData_Fixed,ts_TeamPlanningData_Result,ts_TeamPlanningData_FormattedResult>;
  business_unit_ts_teamplanninginspectorhours: WebMappingRetrieve<ts_TeamPlanningInspectorHours_Select,ts_TeamPlanningInspectorHours_Expand,ts_TeamPlanningInspectorHours_Filter,ts_TeamPlanningInspectorHours_Fixed,ts_TeamPlanningInspectorHours_Result,ts_TeamPlanningInspectorHours_FormattedResult>;
  business_unit_ts_trip: WebMappingRetrieve<ts_trip_Select,ts_trip_Expand,ts_trip_Filter,ts_trip_Fixed,ts_trip_Result,ts_trip_FormattedResult>;
  business_unit_ts_userregistration: WebMappingRetrieve<ts_UserRegistration_Select,ts_UserRegistration_Expand,ts_UserRegistration_Filter,ts_UserRegistration_Fixed,ts_UserRegistration_Result,ts_UserRegistration_FormattedResult>;
  business_unit_ts_workordercreationwizard: WebMappingRetrieve<ts_workordercreationwizard_Select,ts_workordercreationwizard_Expand,ts_workordercreationwizard_Filter,ts_workordercreationwizard_Fixed,ts_workordercreationwizard_Result,ts_workordercreationwizard_FormattedResult>;
  business_unit_ts_workordertimetracking: WebMappingRetrieve<ts_workordertimetracking_Select,ts_workordertimetracking_Expand,ts_workordertimetracking_Filter,ts_workordertimetracking_Fixed,ts_workordertimetracking_Result,ts_workordertimetracking_FormattedResult>;
  ts_UserRegistration_BusinessUnit_Business: WebMappingRetrieve<ts_UserRegistration_Select,ts_UserRegistration_Expand,ts_UserRegistration_Filter,ts_UserRegistration_Fixed,ts_UserRegistration_Result,ts_UserRegistration_FormattedResult>;
  ts_businessunit_ts_nonoversightactivity_Program: WebMappingRetrieve<ts_nonoversightactivity_Select,ts_nonoversightactivity_Expand,ts_nonoversightactivity_Filter,ts_nonoversightactivity_Fixed,ts_nonoversightactivity_Result,ts_nonoversightactivity_FormattedResult>;
  ts_enforcementaction_businessunit_owningbusinessunit: WebMappingRetrieve<ts_enforcementaction_Select,ts_enforcementaction_Expand,ts_enforcementaction_Filter,ts_enforcementaction_Fixed,ts_enforcementaction_Result,ts_enforcementaction_FormattedResult>;
}
interface WebEntitiesRetrieve {
  businessunits: WebMappingRetrieve<BusinessUnit_Select,BusinessUnit_Expand,BusinessUnit_Filter,BusinessUnit_Fixed,BusinessUnit_Result,BusinessUnit_FormattedResult>;
}
interface WebEntitiesRelated {
  businessunits: WebMappingRelated<BusinessUnit_RelatedOne,BusinessUnit_RelatedMany>;
}
interface WebEntitiesCUDA {
  businessunits: WebMappingCUDA<BusinessUnit_Create,BusinessUnit_Update,BusinessUnit_Select>;
}
