interface IncidentResolution_Base extends WebEntity {
  activityadditionalparams?: string | null;
  activityid?: string | null;
  activitytypecode?: string | null;
  actualdurationminutes?: number | null;
  actualend?: Date | null;
  actualstart?: Date | null;
  category?: string | null;
  community?: socialprofile_community | null;
  createdon?: Date | null;
  deliverylastattemptedon?: Date | null;
  deliveryprioritycode?: activitypointer_deliveryprioritycode | null;
  description?: string | null;
  exchangeitemid?: string | null;
  exchangerate?: number | null;
  exchangeweblink?: string | null;
  importsequencenumber?: number | null;
  instancetypecode?: _incidentresolution_instancetypecode | null;
  isbilled?: boolean | null;
  ismapiprivate?: boolean | null;
  isregularactivity?: boolean | null;
  isworkflowcreated?: boolean | null;
  lastonholdtime?: Date | null;
  leftvoicemail?: boolean | null;
  modifiedon?: Date | null;
  msft_datastate?: msft_datastate | null;
  onholdtime?: number | null;
  overriddencreatedon?: Date | null;
  postponeactivityprocessinguntil?: Date | null;
  prioritycode?: _incidentresolution_prioritycode | null;
  processid?: string | null;
  resolutiontypecode?: incidentresolution_incident_statuscode | null;
  scheduleddurationminutes?: number | null;
  scheduledend?: Date | null;
  scheduledstart?: Date | null;
  senton?: Date | null;
  seriesid?: string | null;
  sortdate?: Date | null;
  stageid?: string | null;
  statecode?: incidentresolution_statecode | null;
  statuscode?: incidentresolution_statuscode | null;
  subcategory?: string | null;
  subject?: string | null;
  timespent?: number | null;
  timezoneruleversionnumber?: number | null;
  totaltimespent?: number | null;
  traversedpath?: string | null;
  utcconversiontimezonecode?: number | null;
  versionnumber?: number | null;
}
interface IncidentResolution_Relationships {
  createdby_incidentresolution?: SystemUser_Result | null;
  createdonbehalfby_incidentresolution?: SystemUser_Result | null;
  incidentresolution_activity_parties?: ActivityParty_Result[] | null;
  modifiedby_incidentresolution?: SystemUser_Result | null;
  modifiedonbehalfby_incidentresolution?: SystemUser_Result | null;
  ownerid_incidentresolution?: Team_Result | null;
  ownerid_incidentresolution1?: SystemUser_Result | null;
  owningbusinessunit_incidentresolution?: BusinessUnit_Result | null;
  owningteam_incidentresolution?: Team_Result | null;
  owninguser_incidentresolution?: SystemUser_Result | null;
  regardingobjectid_account_incidentresolution?: Account_Result | null;
  regardingobjectid_bookableresourcebooking_incidentresolution?: BookableResourceBooking_Result | null;
}
interface IncidentResolution extends IncidentResolution_Base, IncidentResolution_Relationships {
  incidentid_bind$incidents?: string | null;
  ownerid_incidentresolution_bind$systemusers?: string | null;
  ownerid_incidentresolution_bind$teams?: string | null;
  regardingobjectid_account_incidentresolution_bind$accounts?: string | null;
  regardingobjectid_bookableresourcebooking_incidentresolution_bind$bookableresourcebookings?: string | null;
  regardingobjectid_bookableresourcebookingheader_incidentresolution_bind$bookableresourcebookingheaders?: string | null;
  regardingobjectid_bulkoperation_incidentresolution_bind$bulkoperations?: string | null;
  regardingobjectid_campaign_incidentresolution_bind$campaigns?: string | null;
  regardingobjectid_campaignactivity_incidentresolution_bind$campaignactivities?: string | null;
  regardingobjectid_entitlement_incidentresolution_bind$entitlements?: string | null;
  regardingobjectid_entitlementtemplate_incidentresolution_bind$entitlementtemplates?: string | null;
  regardingobjectid_knowledgearticle_incidentresolution_bind$knowledgearticles?: string | null;
  regardingobjectid_knowledgebaserecord_incidentresolution_bind$knowledgebaserecords?: string | null;
  regardingobjectid_lead_incidentresolution_bind$leads?: string | null;
  regardingobjectid_new_interactionforemail_incidentresolution_bind$interactionforemails?: string | null;
  serviceid_incidentresolution_bind$services?: string | null;
  sla_activitypointer_sla_incidentresolution_bind$slas?: string | null;
  transactioncurrencyid_incidentresolution_bind$transactioncurrencies?: string | null;
}
interface IncidentResolution_Create extends IncidentResolution {
  activityid_activitypointer_bind$activitypointers?: string | null;
}
interface IncidentResolution_Update extends IncidentResolution {
}
interface IncidentResolution_Select {
  activityadditionalparams: WebAttribute<IncidentResolution_Select, { activityadditionalparams: string | null }, {  }>;
  activityid: WebAttribute<IncidentResolution_Select, { activityid: string | null }, {  }>;
  activitytypecode: WebAttribute<IncidentResolution_Select, { activitytypecode: string | null }, {  }>;
  actualdurationminutes: WebAttribute<IncidentResolution_Select, { actualdurationminutes: number | null }, {  }>;
  actualend: WebAttribute<IncidentResolution_Select, { actualend: Date | null }, { actualend_formatted?: string }>;
  actualstart: WebAttribute<IncidentResolution_Select, { actualstart: Date | null }, { actualstart_formatted?: string }>;
  bcc_guid: WebAttribute<IncidentResolution_Select, { bcc_guid: string | null }, { bcc_formatted?: string }>;
  category: WebAttribute<IncidentResolution_Select, { category: string | null }, {  }>;
  cc_guid: WebAttribute<IncidentResolution_Select, { cc_guid: string | null }, { cc_formatted?: string }>;
  community: WebAttribute<IncidentResolution_Select, { community: socialprofile_community | null }, { community_formatted?: string }>;
  createdby_guid: WebAttribute<IncidentResolution_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
  createdbyexternalparty_guid: WebAttribute<IncidentResolution_Select, { createdbyexternalparty_guid: string | null }, { createdbyexternalparty_formatted?: string }>;
  createdon: WebAttribute<IncidentResolution_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
  createdonbehalfby_guid: WebAttribute<IncidentResolution_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
  customers_guid: WebAttribute<IncidentResolution_Select, { customers_guid: string | null }, { customers_formatted?: string }>;
  deliverylastattemptedon: WebAttribute<IncidentResolution_Select, { deliverylastattemptedon: Date | null }, { deliverylastattemptedon_formatted?: string }>;
  deliveryprioritycode: WebAttribute<IncidentResolution_Select, { deliveryprioritycode: activitypointer_deliveryprioritycode | null }, { deliveryprioritycode_formatted?: string }>;
  description: WebAttribute<IncidentResolution_Select, { description: string | null }, {  }>;
  exchangeitemid: WebAttribute<IncidentResolution_Select, { exchangeitemid: string | null }, {  }>;
  exchangerate: WebAttribute<IncidentResolution_Select, { exchangerate: number | null }, {  }>;
  exchangeweblink: WebAttribute<IncidentResolution_Select, { exchangeweblink: string | null }, {  }>;
  from_guid: WebAttribute<IncidentResolution_Select, { from_guid: string | null }, { from_formatted?: string }>;
  importsequencenumber: WebAttribute<IncidentResolution_Select, { importsequencenumber: number | null }, {  }>;
  incidentid_guid: WebAttribute<IncidentResolution_Select, { incidentid_guid: string | null }, { incidentid_formatted?: string }>;
  instancetypecode: WebAttribute<IncidentResolution_Select, { instancetypecode: _incidentresolution_instancetypecode | null }, { instancetypecode_formatted?: string }>;
  isbilled: WebAttribute<IncidentResolution_Select, { isbilled: boolean | null }, {  }>;
  ismapiprivate: WebAttribute<IncidentResolution_Select, { ismapiprivate: boolean | null }, {  }>;
  isregularactivity: WebAttribute<IncidentResolution_Select, { isregularactivity: boolean | null }, {  }>;
  isworkflowcreated: WebAttribute<IncidentResolution_Select, { isworkflowcreated: boolean | null }, {  }>;
  lastonholdtime: WebAttribute<IncidentResolution_Select, { lastonholdtime: Date | null }, { lastonholdtime_formatted?: string }>;
  leftvoicemail: WebAttribute<IncidentResolution_Select, { leftvoicemail: boolean | null }, {  }>;
  modifiedby_guid: WebAttribute<IncidentResolution_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
  modifiedbyexternalparty_guid: WebAttribute<IncidentResolution_Select, { modifiedbyexternalparty_guid: string | null }, { modifiedbyexternalparty_formatted?: string }>;
  modifiedon: WebAttribute<IncidentResolution_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
  modifiedonbehalfby_guid: WebAttribute<IncidentResolution_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
  msft_datastate: WebAttribute<IncidentResolution_Select, { msft_datastate: msft_datastate | null }, { msft_datastate_formatted?: string }>;
  onholdtime: WebAttribute<IncidentResolution_Select, { onholdtime: number | null }, {  }>;
  optionalattendees_guid: WebAttribute<IncidentResolution_Select, { optionalattendees_guid: string | null }, { optionalattendees_formatted?: string }>;
  organizer_guid: WebAttribute<IncidentResolution_Select, { organizer_guid: string | null }, { organizer_formatted?: string }>;
  overriddencreatedon: WebAttribute<IncidentResolution_Select, { overriddencreatedon: Date | null }, { overriddencreatedon_formatted?: string }>;
  ownerid_guid: WebAttribute<IncidentResolution_Select, { ownerid_guid: string | null }, { ownerid_formatted?: string }>;
  owningbusinessunit_guid: WebAttribute<IncidentResolution_Select, { owningbusinessunit_guid: string | null }, { owningbusinessunit_formatted?: string }>;
  owningteam_guid: WebAttribute<IncidentResolution_Select, { owningteam_guid: string | null }, { owningteam_formatted?: string }>;
  owninguser_guid: WebAttribute<IncidentResolution_Select, { owninguser_guid: string | null }, { owninguser_formatted?: string }>;
  partners_guid: WebAttribute<IncidentResolution_Select, { partners_guid: string | null }, { partners_formatted?: string }>;
  postponeactivityprocessinguntil: WebAttribute<IncidentResolution_Select, { postponeactivityprocessinguntil: Date | null }, { postponeactivityprocessinguntil_formatted?: string }>;
  prioritycode: WebAttribute<IncidentResolution_Select, { prioritycode: _incidentresolution_prioritycode | null }, { prioritycode_formatted?: string }>;
  processid: WebAttribute<IncidentResolution_Select, { processid: string | null }, {  }>;
  regardingobjectid_guid: WebAttribute<IncidentResolution_Select, { regardingobjectid_guid: string | null }, { regardingobjectid_formatted?: string }>;
  requiredattendees_guid: WebAttribute<IncidentResolution_Select, { requiredattendees_guid: string | null }, { requiredattendees_formatted?: string }>;
  resolutiontypecode: WebAttribute<IncidentResolution_Select, { resolutiontypecode: incidentresolution_incident_statuscode | null }, { resolutiontypecode_formatted?: string }>;
  resources_guid: WebAttribute<IncidentResolution_Select, { resources_guid: string | null }, { resources_formatted?: string }>;
  scheduleddurationminutes: WebAttribute<IncidentResolution_Select, { scheduleddurationminutes: number | null }, {  }>;
  scheduledend: WebAttribute<IncidentResolution_Select, { scheduledend: Date | null }, { scheduledend_formatted?: string }>;
  scheduledstart: WebAttribute<IncidentResolution_Select, { scheduledstart: Date | null }, { scheduledstart_formatted?: string }>;
  sendermailboxid_guid: WebAttribute<IncidentResolution_Select, { sendermailboxid_guid: string | null }, { sendermailboxid_formatted?: string }>;
  senton: WebAttribute<IncidentResolution_Select, { senton: Date | null }, { senton_formatted?: string }>;
  seriesid: WebAttribute<IncidentResolution_Select, { seriesid: string | null }, {  }>;
  serviceid_guid: WebAttribute<IncidentResolution_Select, { serviceid_guid: string | null }, { serviceid_formatted?: string }>;
  slaid_guid: WebAttribute<IncidentResolution_Select, { slaid_guid: string | null }, { slaid_formatted?: string }>;
  slainvokedid_guid: WebAttribute<IncidentResolution_Select, { slainvokedid_guid: string | null }, { slainvokedid_formatted?: string }>;
  sortdate: WebAttribute<IncidentResolution_Select, { sortdate: Date | null }, { sortdate_formatted?: string }>;
  stageid: WebAttribute<IncidentResolution_Select, { stageid: string | null }, {  }>;
  statecode: WebAttribute<IncidentResolution_Select, { statecode: incidentresolution_statecode | null }, { statecode_formatted?: string }>;
  statuscode: WebAttribute<IncidentResolution_Select, { statuscode: incidentresolution_statuscode | null }, { statuscode_formatted?: string }>;
  subcategory: WebAttribute<IncidentResolution_Select, { subcategory: string | null }, {  }>;
  subject: WebAttribute<IncidentResolution_Select, { subject: string | null }, {  }>;
  timespent: WebAttribute<IncidentResolution_Select, { timespent: number | null }, {  }>;
  timezoneruleversionnumber: WebAttribute<IncidentResolution_Select, { timezoneruleversionnumber: number | null }, {  }>;
  to_guid: WebAttribute<IncidentResolution_Select, { to_guid: string | null }, { to_formatted?: string }>;
  totaltimespent: WebAttribute<IncidentResolution_Select, { totaltimespent: number | null }, {  }>;
  transactioncurrencyid_guid: WebAttribute<IncidentResolution_Select, { transactioncurrencyid_guid: string | null }, { transactioncurrencyid_formatted?: string }>;
  traversedpath: WebAttribute<IncidentResolution_Select, { traversedpath: string | null }, {  }>;
  utcconversiontimezonecode: WebAttribute<IncidentResolution_Select, { utcconversiontimezonecode: number | null }, {  }>;
  versionnumber: WebAttribute<IncidentResolution_Select, { versionnumber: number | null }, {  }>;
}
interface IncidentResolution_Filter {
  activityadditionalparams: string;
  activityid: XQW.Guid;
  activitytypecode: string;
  actualdurationminutes: number;
  actualend: Date;
  actualstart: Date;
  bcc_guid: XQW.Guid;
  category: string;
  cc_guid: XQW.Guid;
  community: socialprofile_community;
  createdby_guid: XQW.Guid;
  createdbyexternalparty_guid: XQW.Guid;
  createdon: Date;
  createdonbehalfby_guid: XQW.Guid;
  customers_guid: XQW.Guid;
  deliverylastattemptedon: Date;
  deliveryprioritycode: activitypointer_deliveryprioritycode;
  description: string;
  exchangeitemid: string;
  exchangerate: any;
  exchangeweblink: string;
  from_guid: XQW.Guid;
  importsequencenumber: number;
  incidentid_guid: XQW.Guid;
  instancetypecode: _incidentresolution_instancetypecode;
  isbilled: boolean;
  ismapiprivate: boolean;
  isregularactivity: boolean;
  isworkflowcreated: boolean;
  lastonholdtime: Date;
  leftvoicemail: boolean;
  modifiedby_guid: XQW.Guid;
  modifiedbyexternalparty_guid: XQW.Guid;
  modifiedon: Date;
  modifiedonbehalfby_guid: XQW.Guid;
  msft_datastate: msft_datastate;
  onholdtime: number;
  optionalattendees_guid: XQW.Guid;
  organizer_guid: XQW.Guid;
  overriddencreatedon: Date;
  ownerid_guid: XQW.Guid;
  owningbusinessunit_guid: XQW.Guid;
  owningteam_guid: XQW.Guid;
  owninguser_guid: XQW.Guid;
  partners_guid: XQW.Guid;
  postponeactivityprocessinguntil: Date;
  prioritycode: _incidentresolution_prioritycode;
  processid: XQW.Guid;
  regardingobjectid_guid: XQW.Guid;
  requiredattendees_guid: XQW.Guid;
  resolutiontypecode: incidentresolution_incident_statuscode;
  resources_guid: XQW.Guid;
  scheduleddurationminutes: number;
  scheduledend: Date;
  scheduledstart: Date;
  sendermailboxid_guid: XQW.Guid;
  senton: Date;
  seriesid: XQW.Guid;
  serviceid_guid: XQW.Guid;
  slaid_guid: XQW.Guid;
  slainvokedid_guid: XQW.Guid;
  sortdate: Date;
  stageid: XQW.Guid;
  statecode: incidentresolution_statecode;
  statuscode: incidentresolution_statuscode;
  subcategory: string;
  subject: string;
  timespent: number;
  timezoneruleversionnumber: number;
  to_guid: XQW.Guid;
  totaltimespent: number;
  transactioncurrencyid_guid: XQW.Guid;
  traversedpath: string;
  utcconversiontimezonecode: number;
  versionnumber: number;
}
interface IncidentResolution_Expand {
  createdby_incidentresolution: WebExpand<IncidentResolution_Expand, SystemUser_Select, SystemUser_Filter, { createdby_incidentresolution: SystemUser_Result }>;
  createdonbehalfby_incidentresolution: WebExpand<IncidentResolution_Expand, SystemUser_Select, SystemUser_Filter, { createdonbehalfby_incidentresolution: SystemUser_Result }>;
  incidentid: WebExpand<IncidentResolution_Expand, Incident_Select, Incident_Filter, { incidentid: Incident_Result }>;
  incidentresolution_activity_parties: WebExpand<IncidentResolution_Expand, ActivityParty_Select, ActivityParty_Filter, { incidentresolution_activity_parties: ActivityParty_Result[] }>;
  modifiedby_incidentresolution: WebExpand<IncidentResolution_Expand, SystemUser_Select, SystemUser_Filter, { modifiedby_incidentresolution: SystemUser_Result }>;
  modifiedonbehalfby_incidentresolution: WebExpand<IncidentResolution_Expand, SystemUser_Select, SystemUser_Filter, { modifiedonbehalfby_incidentresolution: SystemUser_Result }>;
  ownerid_incidentresolution: WebExpand<IncidentResolution_Expand, SystemUser_Select & Team_Select, SystemUser_Filter & Team_Filter, { ownerid_incidentresolution: SystemUser_Result } & { ownerid_incidentresolution: Team_Result }>;
  owningbusinessunit_incidentresolution: WebExpand<IncidentResolution_Expand, BusinessUnit_Select, BusinessUnit_Filter, { owningbusinessunit_incidentresolution: BusinessUnit_Result }>;
  owningteam_incidentresolution: WebExpand<IncidentResolution_Expand, Team_Select, Team_Filter, { owningteam_incidentresolution: Team_Result }>;
  owninguser_incidentresolution: WebExpand<IncidentResolution_Expand, SystemUser_Select, SystemUser_Filter, { owninguser_incidentresolution: SystemUser_Result }>;
  regardingobjectid_account_incidentresolution: WebExpand<IncidentResolution_Expand, Account_Select, Account_Filter, { regardingobjectid_account_incidentresolution: Account_Result }>;
  regardingobjectid_bookableresourcebooking_incidentresolution: WebExpand<IncidentResolution_Expand, BookableResourceBooking_Select, BookableResourceBooking_Filter, { regardingobjectid_bookableresourcebooking_incidentresolution: BookableResourceBooking_Result }>;
}
interface IncidentResolution_FormattedResult {
  actualend_formatted?: string;
  actualstart_formatted?: string;
  bcc_formatted?: string;
  cc_formatted?: string;
  community_formatted?: string;
  createdby_formatted?: string;
  createdbyexternalparty_formatted?: string;
  createdon_formatted?: string;
  createdonbehalfby_formatted?: string;
  customers_formatted?: string;
  deliverylastattemptedon_formatted?: string;
  deliveryprioritycode_formatted?: string;
  from_formatted?: string;
  incidentid_formatted?: string;
  instancetypecode_formatted?: string;
  lastonholdtime_formatted?: string;
  modifiedby_formatted?: string;
  modifiedbyexternalparty_formatted?: string;
  modifiedon_formatted?: string;
  modifiedonbehalfby_formatted?: string;
  msft_datastate_formatted?: string;
  optionalattendees_formatted?: string;
  organizer_formatted?: string;
  overriddencreatedon_formatted?: string;
  ownerid_formatted?: string;
  owningbusinessunit_formatted?: string;
  owningteam_formatted?: string;
  owninguser_formatted?: string;
  partners_formatted?: string;
  postponeactivityprocessinguntil_formatted?: string;
  prioritycode_formatted?: string;
  regardingobjectid_formatted?: string;
  requiredattendees_formatted?: string;
  resolutiontypecode_formatted?: string;
  resources_formatted?: string;
  scheduledend_formatted?: string;
  scheduledstart_formatted?: string;
  sendermailboxid_formatted?: string;
  senton_formatted?: string;
  serviceid_formatted?: string;
  slaid_formatted?: string;
  slainvokedid_formatted?: string;
  sortdate_formatted?: string;
  statecode_formatted?: string;
  statuscode_formatted?: string;
  to_formatted?: string;
  transactioncurrencyid_formatted?: string;
}
interface IncidentResolution_Result extends IncidentResolution_Base, IncidentResolution_Relationships {
  "@odata.etag": string;
  bcc_guid: string | null;
  cc_guid: string | null;
  createdby_guid: string | null;
  createdbyexternalparty_guid: string | null;
  createdonbehalfby_guid: string | null;
  customers_guid: string | null;
  from_guid: string | null;
  incidentid_guid: string | null;
  modifiedby_guid: string | null;
  modifiedbyexternalparty_guid: string | null;
  modifiedonbehalfby_guid: string | null;
  optionalattendees_guid: string | null;
  organizer_guid: string | null;
  ownerid_guid: string | null;
  owningbusinessunit_guid: string | null;
  owningteam_guid: string | null;
  owninguser_guid: string | null;
  partners_guid: string | null;
  regardingobjectid_guid: string | null;
  requiredattendees_guid: string | null;
  resources_guid: string | null;
  sendermailboxid_guid: string | null;
  serviceid_guid: string | null;
  slaid_guid: string | null;
  slainvokedid_guid: string | null;
  to_guid: string | null;
  transactioncurrencyid_guid: string | null;
}
interface IncidentResolution_RelatedOne {
  createdby_incidentresolution: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  createdonbehalfby_incidentresolution: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  incidentid: WebMappingRetrieve<Incident_Select,Incident_Expand,Incident_Filter,Incident_Fixed,Incident_Result,Incident_FormattedResult>;
  modifiedby_incidentresolution: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedonbehalfby_incidentresolution: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  ownerid_incidentresolution: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  ownerid_incidentresolution1: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  owningbusinessunit_incidentresolution: WebMappingRetrieve<BusinessUnit_Select,BusinessUnit_Expand,BusinessUnit_Filter,BusinessUnit_Fixed,BusinessUnit_Result,BusinessUnit_FormattedResult>;
  owningteam_incidentresolution: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owninguser_incidentresolution: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  regardingobjectid_account_incidentresolution: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  regardingobjectid_bookableresourcebooking_incidentresolution: WebMappingRetrieve<BookableResourceBooking_Select,BookableResourceBooking_Expand,BookableResourceBooking_Filter,BookableResourceBooking_Fixed,BookableResourceBooking_Result,BookableResourceBooking_FormattedResult>;
}
interface IncidentResolution_RelatedMany {
  incidentresolution_activity_parties: WebMappingRetrieve<ActivityParty_Select,ActivityParty_Expand,ActivityParty_Filter,ActivityParty_Fixed,ActivityParty_Result,ActivityParty_FormattedResult>;
}
interface WebEntitiesRetrieve {
  incidentresolutions: WebMappingRetrieve<IncidentResolution_Select,IncidentResolution_Expand,IncidentResolution_Filter,IncidentResolution_Fixed,IncidentResolution_Result,IncidentResolution_FormattedResult>;
}
interface WebEntitiesRelated {
  incidentresolutions: WebMappingRelated<IncidentResolution_RelatedOne,IncidentResolution_RelatedMany>;
}
interface WebEntitiesCUDA {
  incidentresolutions: WebMappingCUDA<IncidentResolution_Create,IncidentResolution_Update,IncidentResolution_Select>;
}
