interface msdyn_workorder_Base extends WebEntity {
  createdon?: Date | null;
  exchangerate?: number | null;
  importsequencenumber?: number | null;
  modifiedon?: Date | null;
  msdyn_address1?: string | null;
  msdyn_address2?: string | null;
  msdyn_address3?: string | null;
  msdyn_addressname?: string | null;
  msdyn_autonumbering?: string | null;
  msdyn_bookingsummary?: string | null;
  msdyn_childindex?: number | null;
  msdyn_city?: string | null;
  msdyn_completedon?: Date | null;
  msdyn_costntepercent?: number | null;
  msdyn_country?: string | null;
  msdyn_datewindowend?: Date | null;
  msdyn_datewindowstart?: Date | null;
  msdyn_displayaddress?: string | null;
  msdyn_estimatesubtotalamount?: number | null;
  msdyn_estimatesubtotalamount_base?: number | null;
  msdyn_firstarrivedon?: Date | null;
  msdyn_followupnote?: string | null;
  msdyn_followuprequired?: boolean | null;
  msdyn_instructions?: string | null;
  msdyn_internalflags?: string | null;
  msdyn_isfollowup?: boolean | null;
  msdyn_ismobile?: boolean | null;
  msdyn_latitude?: number | null;
  msdyn_longitude?: number | null;
  msdyn_mapcontrol?: string | null;
  msdyn_name?: string | null;
  msdyn_nottoexceedcostamount?: number | null;
  msdyn_nottoexceedcostamount_base?: number | null;
  msdyn_nottoexceedpriceamount?: number | null;
  msdyn_nottoexceedpriceamount_base?: number | null;
  msdyn_phoneNumber?: string | null;
  msdyn_postalcode?: string | null;
  msdyn_pricentepercent?: number | null;
  msdyn_primaryincidentdescription?: string | null;
  msdyn_primaryincidentestimatedduration?: number | null;
  msdyn_productsservicescost?: number | null;
  msdyn_productsservicescost_base?: number | null;
  msdyn_productsservicesestimatedcost?: number | null;
  msdyn_productsservicesestimatedcost_base?: number | null;
  msdyn_stateorprovince?: string | null;
  msdyn_subtotalamount?: number | null;
  msdyn_subtotalamount_base?: number | null;
  msdyn_systemstatus?: msdyn_wosystemstatus | null;
  msdyn_taxable?: boolean | null;
  msdyn_timeclosed?: Date | null;
  msdyn_timefrompromised?: Date | null;
  msdyn_timetopromised?: Date | null;
  msdyn_timewindowend?: Date | null;
  msdyn_timewindowstart?: Date | null;
  msdyn_totalamount?: number | null;
  msdyn_totalamount_base?: number | null;
  msdyn_totalestimatedaftertaxprice?: number | null;
  msdyn_totalestimatedaftertaxprice_base?: number | null;
  msdyn_totalestimatedduration?: number | null;
  msdyn_totalsalestax?: number | null;
  msdyn_totalsalestax_base?: number | null;
  msdyn_worklocation?: msdyn_worklocation | null;
  msdyn_workorderid?: string | null;
  msdyn_workordersummary?: string | null;
  overriddencreatedon?: Date | null;
  ovs_iisid?: string | null;
  ovs_mocid?: string | null;
  processid?: string | null;
  qm_blobpath?: string | null;
  qm_remote?: boolean | null;
  stageid?: string | null;
  statecode?: msdyn_workorder_statecode | null;
  statuscode?: msdyn_workorder_statuscode | null;
  timezoneruleversionnumber?: number | null;
  transactioncurrencyid_guid?: string | null;
  traversedpath?: string | null;
  ts_actualcost?: number | null;
  ts_actualcost_base?: number | null;
  ts_actualtimeofarrival?: Date | null;
  ts_actualtimeofdeparture?: Date | null;
  ts_aircraftclassification?: ts_aircraftclassification | null;
  ts_aircraftregistration?: string | null;
  ts_airserviceclassification?: ts_airserviceclassification | null;
  ts_alternateoperatingcarrier?: ts_yesno | null;
  ts_cantcompleteinspection?: boolean | null;
  ts_canvasappnumber?: string | null;
  ts_cargoonlyflight?: boolean | null;
  ts_checkedbagsboarded?: number | null;
  ts_checkedbagscheckedin?: number | null;
  ts_comments?: string | null;
  ts_completedquarter?: ts_msdyn_workorder_ts_completedquarter | null;
  ts_conductingoversight?: number | null;
  ts_costexplanation?: string | null;
  ts_details?: string | null;
  ts_documenteddate?: Date | null;
  ts_flightnumber?: string | null;
  ts_flighttype?: ts_flighttype | null;
  ts_incident?: ts_yesno | null;
  ts_incompleteworkorderreasonforother?: string | null;
  ts_isisso?: number | null;
  ts_justificationcomment?: string | null;
  ts_notes?: string | null;
  ts_numberoffindings?: number | null;
  ts_numberoffindings_date?: Date | null;
  ts_numberoffindings_state?: number | null;
  ts_origin?: string | null;
  ts_othercanceledjustification?: string | null;
  ts_overtime?: number | null;
  ts_overtimerequired?: boolean | null;
  ts_paxboarded?: number | null;
  ts_paxcheckedin?: number | null;
  ts_plannedcost?: number | null;
  ts_plannedcost_base?: number | null;
  ts_preparationtime?: number | null;
  ts_quarterofconductingoversight?: ts_quarter | null;
  ts_quarterofpreparationtime?: ts_quarter | null;
  ts_quarterofreportinganddocumentation?: ts_quarter | null;
  ts_quarteroftraveltime?: ts_quarter | null;
  ts_reasontext?: string | null;
  ts_reportdetails?: string | null;
  ts_riskscore?: number | null;
  ts_scheduledtimeofarrival?: Date | null;
  ts_scheduledtimeofdeparture?: Date | null;
  ts_state?: ts_planningstate | null;
  ts_totalconductoversight?: number | null;
  ts_totalconductoversight_date?: Date | null;
  ts_totalconductoversight_state?: number | null;
  ts_totalpreparationtime?: number | null;
  ts_totalpreparationtime_date?: Date | null;
  ts_totalpreparationtime_state?: number | null;
  ts_totalrepanddoctime?: number | null;
  ts_totalrepanddoctime_date?: Date | null;
  ts_totalrepanddoctime_state?: number | null;
  ts_totaltraveltime?: number | null;
  ts_totaltraveltime_date?: Date | null;
  ts_totaltraveltime_state?: number | null;
  ts_traveltime?: number | null;
  ts_woreportinganddocumentation?: number | null;
  ts_workorderenddate?: Date | null;
  ts_workorderstartdate?: Date | null;
  utcconversiontimezonecode?: number | null;
  versionnumber?: number | null;
}
interface msdyn_workorder_Relationships {
  msdyn_FunctionalLocation?: msdyn_FunctionalLocation_Result | null;
  msdyn_SupportContact?: BookableResource_Result | null;
  msdyn_msdyn_workorder_bookableresourcebooking_WorkOrder?: BookableResourceBooking_Result[] | null;
  msdyn_msdyn_workorder_msdyn_workorder_ParentWorkOrder?: msdyn_workorder_Result[] | null;
  msdyn_msdyn_workorder_msdyn_workorderservicetask_WorkOrder?: msdyn_workorderservicetask_Result[] | null;
  msdyn_parentworkorder_msdyn_workorder?: msdyn_workorder_Result | null;
  msdyn_workorder_Appointments?: Appointment_Result[] | null;
  msdyn_workorder_Emails?: Email_Result[] | null;
  msdyn_workorder_PostFollows?: PostFollow_Result[] | null;
  msdyn_workorder_ServiceAppointments?: ServiceAppointment_Result[] | null;
  msdyn_workorder_Teams?: Team_Result[] | null;
  msdyn_workorder_connections1?: Connection_Result[] | null;
  msdyn_workorder_connections2?: Connection_Result[] | null;
  msdyn_workorder_ts_enforcementactions?: ts_enforcementaction_Result[] | null;
  ovs_AssetCategory?: msdyn_customerassetcategory_Result | null;
  ovs_CurrentFiscalQuarter?: tc_TCFiscalQuarter_Result | null;
  ovs_FiscalQuarter?: tc_TCFiscalQuarter_Result | null;
  ovs_FiscalYear?: tc_TCFiscalYear_Result | null;
  ovs_OperationId?: ovs_operation_Result | null;
  ovs_PrimaryInspector?: BookableResource_Result | null;
  ovs_RevisedQuarterId?: tc_TCFiscalQuarter_Result | null;
  ovs_SecondaryInspector?: BookableResource_Result | null;
  qm_ReportContactId?: Contact_Result | null;
  ts_AccountableTeam?: Team_Result | null;
  ts_CaseTimeTracking?: Incident_Result | null;
  ts_Contact?: Contact_Result | null;
  ts_Contact_msdyn_workorder_msdyn_workorder?: Contact_Result[] | null;
  ts_IncompleteWorkOrderReason?: ts_IncompleteWorkOrderReason_Result | null;
  ts_PlanningData?: ts_PlanningData_Result | null;
  ts_SecurityIncident?: ts_securityincident_Result | null;
  ts_Site?: msdyn_FunctionalLocation_Result | null;
  ts_Subsubsite?: msdyn_FunctionalLocation_Result | null;
  ts_TeamPlanningData?: ts_TeamPlanningData_Result | null;
  ts_WorkOrderCreationWizardId?: ts_workordercreationwizard_Result | null;
  ts_incident_WorkOrder1_msdyn_workorder?: Incident_Result[] | null;
  ts_incident_WorkOrder2_msdyn_workorder?: Incident_Result[] | null;
  ts_msdyn_customerasset_msdyn_workorder_msdyn?: msdyn_customerasset_Result[] | null;
  ts_msdyn_workorder_msdyn_workorder_Account?: Account_Result[] | null;
  ts_msdyn_workorder_ovs_operation_ovs_operati?: ovs_operation_Result[] | null;
  ts_msdyn_workorder_ts_operationcontact?: ts_operationcontact_Result[] | null;
  ts_operationcontact_workorder_msdyn_worko?: ts_operationcontact_Result[] | null;
  ts_ovs_Finding_WorkOrder_msdyn_workorder?: ovs_Finding_Result[] | null;
}
interface msdyn_workorder extends msdyn_workorder_Base, msdyn_workorder_Relationships {
  msdyn_FunctionalLocation_bind$msdyn_functionallocations?: string | null;
  msdyn_IoTAlert_bind$msdyn_iotalerts?: string | null;
  msdyn_PrimaryResolution_bind$msdyn_resolutions?: string | null;
  msdyn_SupportContact_bind$bookableresources?: string | null;
  msdyn_Trade_bind$msdyn_trades?: string | null;
  msdyn_agreement_bind$msdyn_agreements?: string | null;
  msdyn_billingaccount_bind$accounts?: string | null;
  msdyn_closedby_bind$systemusers?: string | null;
  msdyn_customerasset_bind$msdyn_customerassets?: string | null;
  msdyn_opportunityid_bind$opportunities?: string | null;
  msdyn_parentworkorder_msdyn_workorder_bind$msdyn_workorders?: string | null;
  msdyn_preferredresource_bind$bookableresources?: string | null;
  msdyn_pricelist_bind$pricelevels?: string | null;
  msdyn_primaryincidenttype_bind$msdyn_incidenttypes?: string | null;
  msdyn_priority_bind$msdyn_priorities?: string | null;
  msdyn_reportedbycontact_bind$contacts?: string | null;
  msdyn_serviceaccount_bind$accounts?: string | null;
  msdyn_servicerequest_bind$incidents?: string | null;
  msdyn_serviceterritory_bind$territories?: string | null;
  msdyn_substatus_bind$msdyn_workordersubstatuses?: string | null;
  msdyn_taxcode_bind$msdyn_taxcodes?: string | null;
  msdyn_timegroup_bind$msdyn_timegroups?: string | null;
  msdyn_timegroupdetailselected_bind$msdyn_timegroupdetails?: string | null;
  msdyn_workhourtemplate_bind$msdyn_workhourtemplates?: string | null;
  msdyn_workorderarrivaltimekpiid_bind$slakpiinstances?: string | null;
  msdyn_workorderresolutionkpiid_bind$slakpiinstances?: string | null;
  msdyn_workordertype_bind$msdyn_workordertypes?: string | null;
  ovs_AssetCategory_bind$msdyn_customerassetcategories?: string | null;
  ovs_CurrentFiscalQuarter_bind$tc_tcfiscalquarters?: string | null;
  ovs_FiscalQuarter_bind$tc_tcfiscalquarters?: string | null;
  ovs_FiscalYear_bind$tc_tcfiscalyears?: string | null;
  ovs_OperationId_bind$ovs_operations?: string | null;
  ovs_PrimaryInspector_bind$bookableresources?: string | null;
  ovs_Rational_bind$ovs_tyrationals?: string | null;
  ovs_RevisedQuarterId_bind$tc_tcfiscalquarters?: string | null;
  ovs_SecondaryInspector_bind$bookableresources?: string | null;
  ovs_TYRational_bind$ovs_tyrationals?: string | null;
  ovs_asset_bind$msdyn_customerassets?: string | null;
  ovs_operationtypeid_bind$ovs_operationtypes?: string | null;
  ownerid_bind$systemusers?: string | null;
  ownerid_bind$teams?: string | null;
  qm_ReportContactId_bind$contacts?: string | null;
  stageid_bind$processstages?: string | null;
  transactioncurrencyid_bind$transactioncurrencies?: string | null;
  ts_AccountableTeam_bind$teams?: string | null;
  ts_CaseTimeTracking_bind$incidents?: string | null;
  ts_Contact_bind$contacts?: string | null;
  ts_Country_bind$tc_countries?: string | null;
  ts_IncompleteWorkOrderReason_bind$ts_incompleteworkorderreasons?: string | null;
  ts_PlanningData_bind$ts_planningdatas?: string | null;
  ts_Region_bind$territories?: string | null;
  ts_ScheduledQuarterJustification_bind$ts_justifications?: string | null;
  ts_SecurityIncident_bind$ts_securityincidents?: string | null;
  ts_Site_bind$msdyn_functionallocations?: string | null;
  ts_Subsubsite_bind$msdyn_functionallocations?: string | null;
  ts_TeamPlanningData_bind$ts_teamplanningdatas?: string | null;
  ts_WorkOrderCreationWizardId_bind$ts_workordercreationwizards?: string | null;
  ts_arrivalaerodrome_bind$msdyn_functionallocations?: string | null;
  ts_canceledinspectionjustification_bind$ts_canceledinspectionjustifications?: string | null;
  ts_departureaerodrome_bind$msdyn_functionallocations?: string | null;
  ts_operatingcarrier_bind$accounts?: string | null;
  ts_operatingname_bind$accounts?: string | null;
  ts_plan_bind$ts_plans?: string | null;
  ts_reason_bind$ts_planningreasons?: string | null;
  ts_registration_bind$ts_aircrafts?: string | null;
  ts_riskthreshold_bind$ts_riskcategories?: string | null;
  ts_suggestedinspection_bind$ts_suggestedinspections?: string | null;
  ts_tradenameId_bind$ts_tradenames?: string | null;
  ts_trip_bind$ts_trips?: string | null;
}
interface msdyn_workorder_Create extends msdyn_workorder {
}
interface msdyn_workorder_Update extends msdyn_workorder {
}
interface msdyn_workorder_Select {
  createdby_guid: WebAttribute<msdyn_workorder_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
  createdon: WebAttribute<msdyn_workorder_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
  createdonbehalfby_guid: WebAttribute<msdyn_workorder_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
  exchangerate: WebAttribute<msdyn_workorder_Select, { exchangerate: number | null }, {  }>;
  importsequencenumber: WebAttribute<msdyn_workorder_Select, { importsequencenumber: number | null }, {  }>;
  modifiedby_guid: WebAttribute<msdyn_workorder_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
  modifiedon: WebAttribute<msdyn_workorder_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
  modifiedonbehalfby_guid: WebAttribute<msdyn_workorder_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
  msdyn_address1: WebAttribute<msdyn_workorder_Select, { msdyn_address1: string | null }, {  }>;
  msdyn_address2: WebAttribute<msdyn_workorder_Select, { msdyn_address2: string | null }, {  }>;
  msdyn_address3: WebAttribute<msdyn_workorder_Select, { msdyn_address3: string | null }, {  }>;
  msdyn_addressname: WebAttribute<msdyn_workorder_Select, { msdyn_addressname: string | null }, {  }>;
  msdyn_agreement_guid: WebAttribute<msdyn_workorder_Select, { msdyn_agreement_guid: string | null }, { msdyn_agreement_formatted?: string }>;
  msdyn_autonumbering: WebAttribute<msdyn_workorder_Select, { msdyn_autonumbering: string | null }, {  }>;
  msdyn_billingaccount_guid: WebAttribute<msdyn_workorder_Select, { msdyn_billingaccount_guid: string | null }, { msdyn_billingaccount_formatted?: string }>;
  msdyn_bookingsummary: WebAttribute<msdyn_workorder_Select, { msdyn_bookingsummary: string | null }, {  }>;
  msdyn_childindex: WebAttribute<msdyn_workorder_Select, { msdyn_childindex: number | null }, {  }>;
  msdyn_city: WebAttribute<msdyn_workorder_Select, { msdyn_city: string | null }, {  }>;
  msdyn_closedby_guid: WebAttribute<msdyn_workorder_Select, { msdyn_closedby_guid: string | null }, { msdyn_closedby_formatted?: string }>;
  msdyn_completedon: WebAttribute<msdyn_workorder_Select, { msdyn_completedon: Date | null }, { msdyn_completedon_formatted?: string }>;
  msdyn_costntepercent: WebAttribute<msdyn_workorder_Select, { msdyn_costntepercent: number | null }, {  }>;
  msdyn_country: WebAttribute<msdyn_workorder_Select, { msdyn_country: string | null }, {  }>;
  msdyn_customerasset_guid: WebAttribute<msdyn_workorder_Select, { msdyn_customerasset_guid: string | null }, { msdyn_customerasset_formatted?: string }>;
  msdyn_datewindowend: WebAttribute<msdyn_workorder_Select, { msdyn_datewindowend: Date | null }, { msdyn_datewindowend_formatted?: string }>;
  msdyn_datewindowstart: WebAttribute<msdyn_workorder_Select, { msdyn_datewindowstart: Date | null }, { msdyn_datewindowstart_formatted?: string }>;
  msdyn_displayaddress: WebAttribute<msdyn_workorder_Select, { msdyn_displayaddress: string | null }, {  }>;
  msdyn_estimatesubtotalamount: WebAttribute<msdyn_workorder_Select, { msdyn_estimatesubtotalamount: number | null; transactioncurrencyid_guid: string | null }, { msdyn_estimatesubtotalamount_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_estimatesubtotalamount_base: WebAttribute<msdyn_workorder_Select, { msdyn_estimatesubtotalamount_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_estimatesubtotalamount_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_firstarrivedon: WebAttribute<msdyn_workorder_Select, { msdyn_firstarrivedon: Date | null }, { msdyn_firstarrivedon_formatted?: string }>;
  msdyn_followupnote: WebAttribute<msdyn_workorder_Select, { msdyn_followupnote: string | null }, {  }>;
  msdyn_followuprequired: WebAttribute<msdyn_workorder_Select, { msdyn_followuprequired: boolean | null }, {  }>;
  msdyn_functionallocation_guid: WebAttribute<msdyn_workorder_Select, { msdyn_functionallocation_guid: string | null }, { msdyn_functionallocation_formatted?: string }>;
  msdyn_instructions: WebAttribute<msdyn_workorder_Select, { msdyn_instructions: string | null }, {  }>;
  msdyn_internalflags: WebAttribute<msdyn_workorder_Select, { msdyn_internalflags: string | null }, {  }>;
  msdyn_iotalert_guid: WebAttribute<msdyn_workorder_Select, { msdyn_iotalert_guid: string | null }, { msdyn_iotalert_formatted?: string }>;
  msdyn_isfollowup: WebAttribute<msdyn_workorder_Select, { msdyn_isfollowup: boolean | null }, {  }>;
  msdyn_ismobile: WebAttribute<msdyn_workorder_Select, { msdyn_ismobile: boolean | null }, {  }>;
  msdyn_latitude: WebAttribute<msdyn_workorder_Select, { msdyn_latitude: number | null }, {  }>;
  msdyn_longitude: WebAttribute<msdyn_workorder_Select, { msdyn_longitude: number | null }, {  }>;
  msdyn_mapcontrol: WebAttribute<msdyn_workorder_Select, { msdyn_mapcontrol: string | null }, {  }>;
  msdyn_name: WebAttribute<msdyn_workorder_Select, { msdyn_name: string | null }, {  }>;
  msdyn_nottoexceedcostamount: WebAttribute<msdyn_workorder_Select, { msdyn_nottoexceedcostamount: number | null; transactioncurrencyid_guid: string | null }, { msdyn_nottoexceedcostamount_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_nottoexceedcostamount_base: WebAttribute<msdyn_workorder_Select, { msdyn_nottoexceedcostamount_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_nottoexceedcostamount_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_nottoexceedpriceamount: WebAttribute<msdyn_workorder_Select, { msdyn_nottoexceedpriceamount: number | null; transactioncurrencyid_guid: string | null }, { msdyn_nottoexceedpriceamount_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_nottoexceedpriceamount_base: WebAttribute<msdyn_workorder_Select, { msdyn_nottoexceedpriceamount_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_nottoexceedpriceamount_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_opportunityid_guid: WebAttribute<msdyn_workorder_Select, { msdyn_opportunityid_guid: string | null }, { msdyn_opportunityid_formatted?: string }>;
  msdyn_parentworkorder_guid: WebAttribute<msdyn_workorder_Select, { msdyn_parentworkorder_guid: string | null }, { msdyn_parentworkorder_formatted?: string }>;
  msdyn_phoneNumber: WebAttribute<msdyn_workorder_Select, { msdyn_phoneNumber: string | null }, {  }>;
  msdyn_postalcode: WebAttribute<msdyn_workorder_Select, { msdyn_postalcode: string | null }, {  }>;
  msdyn_preferredresource_guid: WebAttribute<msdyn_workorder_Select, { msdyn_preferredresource_guid: string | null }, { msdyn_preferredresource_formatted?: string }>;
  msdyn_pricelist_guid: WebAttribute<msdyn_workorder_Select, { msdyn_pricelist_guid: string | null }, { msdyn_pricelist_formatted?: string }>;
  msdyn_pricentepercent: WebAttribute<msdyn_workorder_Select, { msdyn_pricentepercent: number | null }, {  }>;
  msdyn_primaryincidentdescription: WebAttribute<msdyn_workorder_Select, { msdyn_primaryincidentdescription: string | null }, {  }>;
  msdyn_primaryincidentestimatedduration: WebAttribute<msdyn_workorder_Select, { msdyn_primaryincidentestimatedduration: number | null }, {  }>;
  msdyn_primaryincidenttype_guid: WebAttribute<msdyn_workorder_Select, { msdyn_primaryincidenttype_guid: string | null }, { msdyn_primaryincidenttype_formatted?: string }>;
  msdyn_primaryresolution_guid: WebAttribute<msdyn_workorder_Select, { msdyn_primaryresolution_guid: string | null }, { msdyn_primaryresolution_formatted?: string }>;
  msdyn_priority_guid: WebAttribute<msdyn_workorder_Select, { msdyn_priority_guid: string | null }, { msdyn_priority_formatted?: string }>;
  msdyn_productsservicescost: WebAttribute<msdyn_workorder_Select, { msdyn_productsservicescost: number | null; transactioncurrencyid_guid: string | null }, { msdyn_productsservicescost_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_productsservicescost_base: WebAttribute<msdyn_workorder_Select, { msdyn_productsservicescost_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_productsservicescost_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_productsservicesestimatedcost: WebAttribute<msdyn_workorder_Select, { msdyn_productsservicesestimatedcost: number | null; transactioncurrencyid_guid: string | null }, { msdyn_productsservicesestimatedcost_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_productsservicesestimatedcost_base: WebAttribute<msdyn_workorder_Select, { msdyn_productsservicesestimatedcost_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_productsservicesestimatedcost_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_reportedbycontact_guid: WebAttribute<msdyn_workorder_Select, { msdyn_reportedbycontact_guid: string | null }, { msdyn_reportedbycontact_formatted?: string }>;
  msdyn_serviceaccount_guid: WebAttribute<msdyn_workorder_Select, { msdyn_serviceaccount_guid: string | null }, { msdyn_serviceaccount_formatted?: string }>;
  msdyn_servicerequest_guid: WebAttribute<msdyn_workorder_Select, { msdyn_servicerequest_guid: string | null }, { msdyn_servicerequest_formatted?: string }>;
  msdyn_serviceterritory_guid: WebAttribute<msdyn_workorder_Select, { msdyn_serviceterritory_guid: string | null }, { msdyn_serviceterritory_formatted?: string }>;
  msdyn_stateorprovince: WebAttribute<msdyn_workorder_Select, { msdyn_stateorprovince: string | null }, {  }>;
  msdyn_substatus_guid: WebAttribute<msdyn_workorder_Select, { msdyn_substatus_guid: string | null }, { msdyn_substatus_formatted?: string }>;
  msdyn_subtotalamount: WebAttribute<msdyn_workorder_Select, { msdyn_subtotalamount: number | null; transactioncurrencyid_guid: string | null }, { msdyn_subtotalamount_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_subtotalamount_base: WebAttribute<msdyn_workorder_Select, { msdyn_subtotalamount_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_subtotalamount_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_supportcontact_guid: WebAttribute<msdyn_workorder_Select, { msdyn_supportcontact_guid: string | null }, { msdyn_supportcontact_formatted?: string }>;
  msdyn_systemstatus: WebAttribute<msdyn_workorder_Select, { msdyn_systemstatus: msdyn_wosystemstatus | null }, { msdyn_systemstatus_formatted?: string }>;
  msdyn_taxable: WebAttribute<msdyn_workorder_Select, { msdyn_taxable: boolean | null }, {  }>;
  msdyn_taxcode_guid: WebAttribute<msdyn_workorder_Select, { msdyn_taxcode_guid: string | null }, { msdyn_taxcode_formatted?: string }>;
  msdyn_timeclosed: WebAttribute<msdyn_workorder_Select, { msdyn_timeclosed: Date | null }, { msdyn_timeclosed_formatted?: string }>;
  msdyn_timefrompromised: WebAttribute<msdyn_workorder_Select, { msdyn_timefrompromised: Date | null }, { msdyn_timefrompromised_formatted?: string }>;
  msdyn_timegroup_guid: WebAttribute<msdyn_workorder_Select, { msdyn_timegroup_guid: string | null }, { msdyn_timegroup_formatted?: string }>;
  msdyn_timegroupdetailselected_guid: WebAttribute<msdyn_workorder_Select, { msdyn_timegroupdetailselected_guid: string | null }, { msdyn_timegroupdetailselected_formatted?: string }>;
  msdyn_timetopromised: WebAttribute<msdyn_workorder_Select, { msdyn_timetopromised: Date | null }, { msdyn_timetopromised_formatted?: string }>;
  msdyn_timewindowend: WebAttribute<msdyn_workorder_Select, { msdyn_timewindowend: Date | null }, { msdyn_timewindowend_formatted?: string }>;
  msdyn_timewindowstart: WebAttribute<msdyn_workorder_Select, { msdyn_timewindowstart: Date | null }, { msdyn_timewindowstart_formatted?: string }>;
  msdyn_totalamount: WebAttribute<msdyn_workorder_Select, { msdyn_totalamount: number | null; transactioncurrencyid_guid: string | null }, { msdyn_totalamount_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_totalamount_base: WebAttribute<msdyn_workorder_Select, { msdyn_totalamount_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_totalamount_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_totalestimatedaftertaxprice: WebAttribute<msdyn_workorder_Select, { msdyn_totalestimatedaftertaxprice: number | null; transactioncurrencyid_guid: string | null }, { msdyn_totalestimatedaftertaxprice_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_totalestimatedaftertaxprice_base: WebAttribute<msdyn_workorder_Select, { msdyn_totalestimatedaftertaxprice_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_totalestimatedaftertaxprice_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_totalestimatedduration: WebAttribute<msdyn_workorder_Select, { msdyn_totalestimatedduration: number | null }, {  }>;
  msdyn_totalsalestax: WebAttribute<msdyn_workorder_Select, { msdyn_totalsalestax: number | null; transactioncurrencyid_guid: string | null }, { msdyn_totalsalestax_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_totalsalestax_base: WebAttribute<msdyn_workorder_Select, { msdyn_totalsalestax_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_totalsalestax_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_trade_guid: WebAttribute<msdyn_workorder_Select, { msdyn_trade_guid: string | null }, { msdyn_trade_formatted?: string }>;
  msdyn_workhourtemplate_guid: WebAttribute<msdyn_workorder_Select, { msdyn_workhourtemplate_guid: string | null }, { msdyn_workhourtemplate_formatted?: string }>;
  msdyn_worklocation: WebAttribute<msdyn_workorder_Select, { msdyn_worklocation: msdyn_worklocation | null }, { msdyn_worklocation_formatted?: string }>;
  msdyn_workorderarrivaltimekpiid_guid: WebAttribute<msdyn_workorder_Select, { msdyn_workorderarrivaltimekpiid_guid: string | null }, { msdyn_workorderarrivaltimekpiid_formatted?: string }>;
  msdyn_workorderid: WebAttribute<msdyn_workorder_Select, { msdyn_workorderid: string | null }, {  }>;
  msdyn_workorderresolutionkpiid_guid: WebAttribute<msdyn_workorder_Select, { msdyn_workorderresolutionkpiid_guid: string | null }, { msdyn_workorderresolutionkpiid_formatted?: string }>;
  msdyn_workordersummary: WebAttribute<msdyn_workorder_Select, { msdyn_workordersummary: string | null }, {  }>;
  msdyn_workordertype_guid: WebAttribute<msdyn_workorder_Select, { msdyn_workordertype_guid: string | null }, { msdyn_workordertype_formatted?: string }>;
  overriddencreatedon: WebAttribute<msdyn_workorder_Select, { overriddencreatedon: Date | null }, { overriddencreatedon_formatted?: string }>;
  ovs_asset_guid: WebAttribute<msdyn_workorder_Select, { ovs_asset_guid: string | null }, { ovs_asset_formatted?: string }>;
  ovs_assetcategory_guid: WebAttribute<msdyn_workorder_Select, { ovs_assetcategory_guid: string | null }, { ovs_assetcategory_formatted?: string }>;
  ovs_currentfiscalquarter_guid: WebAttribute<msdyn_workorder_Select, { ovs_currentfiscalquarter_guid: string | null }, { ovs_currentfiscalquarter_formatted?: string }>;
  ovs_fiscalquarter_guid: WebAttribute<msdyn_workorder_Select, { ovs_fiscalquarter_guid: string | null }, { ovs_fiscalquarter_formatted?: string }>;
  ovs_fiscalyear_guid: WebAttribute<msdyn_workorder_Select, { ovs_fiscalyear_guid: string | null }, { ovs_fiscalyear_formatted?: string }>;
  ovs_iisid: WebAttribute<msdyn_workorder_Select, { ovs_iisid: string | null }, {  }>;
  ovs_mocid: WebAttribute<msdyn_workorder_Select, { ovs_mocid: string | null }, {  }>;
  ovs_operationid_guid: WebAttribute<msdyn_workorder_Select, { ovs_operationid_guid: string | null }, { ovs_operationid_formatted?: string }>;
  ovs_operationtypeid_guid: WebAttribute<msdyn_workorder_Select, { ovs_operationtypeid_guid: string | null }, { ovs_operationtypeid_formatted?: string }>;
  ovs_primaryinspector_guid: WebAttribute<msdyn_workorder_Select, { ovs_primaryinspector_guid: string | null }, { ovs_primaryinspector_formatted?: string }>;
  ovs_rational_guid: WebAttribute<msdyn_workorder_Select, { ovs_rational_guid: string | null }, { ovs_rational_formatted?: string }>;
  ovs_revisedquarterid_guid: WebAttribute<msdyn_workorder_Select, { ovs_revisedquarterid_guid: string | null }, { ovs_revisedquarterid_formatted?: string }>;
  ovs_secondaryinspector_guid: WebAttribute<msdyn_workorder_Select, { ovs_secondaryinspector_guid: string | null }, { ovs_secondaryinspector_formatted?: string }>;
  ovs_tyrational_guid: WebAttribute<msdyn_workorder_Select, { ovs_tyrational_guid: string | null }, { ovs_tyrational_formatted?: string }>;
  ownerid_guid: WebAttribute<msdyn_workorder_Select, { ownerid_guid: string | null }, { ownerid_formatted?: string }>;
  owningbusinessunit_guid: WebAttribute<msdyn_workorder_Select, { owningbusinessunit_guid: string | null }, { owningbusinessunit_formatted?: string }>;
  owningteam_guid: WebAttribute<msdyn_workorder_Select, { owningteam_guid: string | null }, { owningteam_formatted?: string }>;
  owninguser_guid: WebAttribute<msdyn_workorder_Select, { owninguser_guid: string | null }, { owninguser_formatted?: string }>;
  processid: WebAttribute<msdyn_workorder_Select, { processid: string | null }, {  }>;
  qm_blobpath: WebAttribute<msdyn_workorder_Select, { qm_blobpath: string | null }, {  }>;
  qm_remote: WebAttribute<msdyn_workorder_Select, { qm_remote: boolean | null }, {  }>;
  qm_reportcontactid_guid: WebAttribute<msdyn_workorder_Select, { qm_reportcontactid_guid: string | null }, { qm_reportcontactid_formatted?: string }>;
  stageid: WebAttribute<msdyn_workorder_Select, { stageid: string | null }, {  }>;
  statecode: WebAttribute<msdyn_workorder_Select, { statecode: msdyn_workorder_statecode | null }, { statecode_formatted?: string }>;
  statuscode: WebAttribute<msdyn_workorder_Select, { statuscode: msdyn_workorder_statuscode | null }, { statuscode_formatted?: string }>;
  timezoneruleversionnumber: WebAttribute<msdyn_workorder_Select, { timezoneruleversionnumber: number | null }, {  }>;
  transactioncurrencyid_guid: WebAttribute<msdyn_workorder_Select, { transactioncurrencyid_guid: string | null }, { transactioncurrencyid_formatted?: string }>;
  traversedpath: WebAttribute<msdyn_workorder_Select, { traversedpath: string | null }, {  }>;
  ts_accountableteam_guid: WebAttribute<msdyn_workorder_Select, { ts_accountableteam_guid: string | null }, { ts_accountableteam_formatted?: string }>;
  ts_actualcost: WebAttribute<msdyn_workorder_Select, { ts_actualcost: number | null; transactioncurrencyid_guid: string | null }, { ts_actualcost_formatted?: string; transactioncurrencyid_formatted?: string }>;
  ts_actualcost_base: WebAttribute<msdyn_workorder_Select, { ts_actualcost_base: number | null; transactioncurrencyid_guid: string | null }, { ts_actualcost_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  ts_actualtimeofarrival: WebAttribute<msdyn_workorder_Select, { ts_actualtimeofarrival: Date | null }, { ts_actualtimeofarrival_formatted?: string }>;
  ts_actualtimeofdeparture: WebAttribute<msdyn_workorder_Select, { ts_actualtimeofdeparture: Date | null }, { ts_actualtimeofdeparture_formatted?: string }>;
  ts_aircraftclassification: WebAttribute<msdyn_workorder_Select, { ts_aircraftclassification: ts_aircraftclassification | null }, { ts_aircraftclassification_formatted?: string }>;
  ts_aircraftregistration: WebAttribute<msdyn_workorder_Select, { ts_aircraftregistration: string | null }, {  }>;
  ts_airserviceclassification: WebAttribute<msdyn_workorder_Select, { ts_airserviceclassification: ts_airserviceclassification | null }, { ts_airserviceclassification_formatted?: string }>;
  ts_alternateoperatingcarrier: WebAttribute<msdyn_workorder_Select, { ts_alternateoperatingcarrier: ts_yesno | null }, { ts_alternateoperatingcarrier_formatted?: string }>;
  ts_arrivalaerodrome_guid: WebAttribute<msdyn_workorder_Select, { ts_arrivalaerodrome_guid: string | null }, { ts_arrivalaerodrome_formatted?: string }>;
  ts_canceledinspectionjustification_guid: WebAttribute<msdyn_workorder_Select, { ts_canceledinspectionjustification_guid: string | null }, { ts_canceledinspectionjustification_formatted?: string }>;
  ts_cantcompleteinspection: WebAttribute<msdyn_workorder_Select, { ts_cantcompleteinspection: boolean | null }, {  }>;
  ts_canvasappnumber: WebAttribute<msdyn_workorder_Select, { ts_canvasappnumber: string | null }, {  }>;
  ts_cargoonlyflight: WebAttribute<msdyn_workorder_Select, { ts_cargoonlyflight: boolean | null }, {  }>;
  ts_casetimetracking_guid: WebAttribute<msdyn_workorder_Select, { ts_casetimetracking_guid: string | null }, { ts_casetimetracking_formatted?: string }>;
  ts_checkedbagsboarded: WebAttribute<msdyn_workorder_Select, { ts_checkedbagsboarded: number | null }, {  }>;
  ts_checkedbagscheckedin: WebAttribute<msdyn_workorder_Select, { ts_checkedbagscheckedin: number | null }, {  }>;
  ts_comments: WebAttribute<msdyn_workorder_Select, { ts_comments: string | null }, {  }>;
  ts_completedquarter: WebAttribute<msdyn_workorder_Select, { ts_completedquarter: ts_msdyn_workorder_ts_completedquarter | null }, { ts_completedquarter_formatted?: string }>;
  ts_conductingoversight: WebAttribute<msdyn_workorder_Select, { ts_conductingoversight: number | null }, {  }>;
  ts_contact_guid: WebAttribute<msdyn_workorder_Select, { ts_contact_guid: string | null }, { ts_contact_formatted?: string }>;
  ts_costexplanation: WebAttribute<msdyn_workorder_Select, { ts_costexplanation: string | null }, {  }>;
  ts_country_guid: WebAttribute<msdyn_workorder_Select, { ts_country_guid: string | null }, { ts_country_formatted?: string }>;
  ts_departureaerodrome_guid: WebAttribute<msdyn_workorder_Select, { ts_departureaerodrome_guid: string | null }, { ts_departureaerodrome_formatted?: string }>;
  ts_details: WebAttribute<msdyn_workorder_Select, { ts_details: string | null }, {  }>;
  ts_documenteddate: WebAttribute<msdyn_workorder_Select, { ts_documenteddate: Date | null }, { ts_documenteddate_formatted?: string }>;
  ts_flightnumber: WebAttribute<msdyn_workorder_Select, { ts_flightnumber: string | null }, {  }>;
  ts_flighttype: WebAttribute<msdyn_workorder_Select, { ts_flighttype: ts_flighttype | null }, { ts_flighttype_formatted?: string }>;
  ts_incident: WebAttribute<msdyn_workorder_Select, { ts_incident: ts_yesno | null }, { ts_incident_formatted?: string }>;
  ts_incompleteworkorderreason_guid: WebAttribute<msdyn_workorder_Select, { ts_incompleteworkorderreason_guid: string | null }, { ts_incompleteworkorderreason_formatted?: string }>;
  ts_incompleteworkorderreasonforother: WebAttribute<msdyn_workorder_Select, { ts_incompleteworkorderreasonforother: string | null }, {  }>;
  ts_isisso: WebAttribute<msdyn_workorder_Select, { ts_isisso: number | null }, {  }>;
  ts_justificationcomment: WebAttribute<msdyn_workorder_Select, { ts_justificationcomment: string | null }, {  }>;
  ts_notes: WebAttribute<msdyn_workorder_Select, { ts_notes: string | null }, {  }>;
  ts_numberoffindings: WebAttribute<msdyn_workorder_Select, { ts_numberoffindings: number | null }, {  }>;
  ts_numberoffindings_date: WebAttribute<msdyn_workorder_Select, { ts_numberoffindings_date: Date | null }, { ts_numberoffindings_date_formatted?: string }>;
  ts_numberoffindings_state: WebAttribute<msdyn_workorder_Select, { ts_numberoffindings_state: number | null }, {  }>;
  ts_operatingcarrier_guid: WebAttribute<msdyn_workorder_Select, { ts_operatingcarrier_guid: string | null }, { ts_operatingcarrier_formatted?: string }>;
  ts_operatingname_guid: WebAttribute<msdyn_workorder_Select, { ts_operatingname_guid: string | null }, { ts_operatingname_formatted?: string }>;
  ts_origin: WebAttribute<msdyn_workorder_Select, { ts_origin: string | null }, {  }>;
  ts_othercanceledjustification: WebAttribute<msdyn_workorder_Select, { ts_othercanceledjustification: string | null }, {  }>;
  ts_overtime: WebAttribute<msdyn_workorder_Select, { ts_overtime: number | null }, {  }>;
  ts_overtimerequired: WebAttribute<msdyn_workorder_Select, { ts_overtimerequired: boolean | null }, {  }>;
  ts_paxboarded: WebAttribute<msdyn_workorder_Select, { ts_paxboarded: number | null }, {  }>;
  ts_paxcheckedin: WebAttribute<msdyn_workorder_Select, { ts_paxcheckedin: number | null }, {  }>;
  ts_plan_guid: WebAttribute<msdyn_workorder_Select, { ts_plan_guid: string | null }, { ts_plan_formatted?: string }>;
  ts_plannedcost: WebAttribute<msdyn_workorder_Select, { ts_plannedcost: number | null; transactioncurrencyid_guid: string | null }, { ts_plannedcost_formatted?: string; transactioncurrencyid_formatted?: string }>;
  ts_plannedcost_base: WebAttribute<msdyn_workorder_Select, { ts_plannedcost_base: number | null; transactioncurrencyid_guid: string | null }, { ts_plannedcost_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  ts_planningdata_guid: WebAttribute<msdyn_workorder_Select, { ts_planningdata_guid: string | null }, { ts_planningdata_formatted?: string }>;
  ts_preparationtime: WebAttribute<msdyn_workorder_Select, { ts_preparationtime: number | null }, {  }>;
  ts_quarterofconductingoversight: WebAttribute<msdyn_workorder_Select, { ts_quarterofconductingoversight: ts_quarter | null }, { ts_quarterofconductingoversight_formatted?: string }>;
  ts_quarterofpreparationtime: WebAttribute<msdyn_workorder_Select, { ts_quarterofpreparationtime: ts_quarter | null }, { ts_quarterofpreparationtime_formatted?: string }>;
  ts_quarterofreportinganddocumentation: WebAttribute<msdyn_workorder_Select, { ts_quarterofreportinganddocumentation: ts_quarter | null }, { ts_quarterofreportinganddocumentation_formatted?: string }>;
  ts_quarteroftraveltime: WebAttribute<msdyn_workorder_Select, { ts_quarteroftraveltime: ts_quarter | null }, { ts_quarteroftraveltime_formatted?: string }>;
  ts_reason_guid: WebAttribute<msdyn_workorder_Select, { ts_reason_guid: string | null }, { ts_reason_formatted?: string }>;
  ts_reasontext: WebAttribute<msdyn_workorder_Select, { ts_reasontext: string | null }, {  }>;
  ts_region_guid: WebAttribute<msdyn_workorder_Select, { ts_region_guid: string | null }, { ts_region_formatted?: string }>;
  ts_registration_guid: WebAttribute<msdyn_workorder_Select, { ts_registration_guid: string | null }, { ts_registration_formatted?: string }>;
  ts_reportdetails: WebAttribute<msdyn_workorder_Select, { ts_reportdetails: string | null }, {  }>;
  ts_riskscore: WebAttribute<msdyn_workorder_Select, { ts_riskscore: number | null }, {  }>;
  ts_riskthreshold_guid: WebAttribute<msdyn_workorder_Select, { ts_riskthreshold_guid: string | null }, { ts_riskthreshold_formatted?: string }>;
  ts_scheduledquarterjustification_guid: WebAttribute<msdyn_workorder_Select, { ts_scheduledquarterjustification_guid: string | null }, { ts_scheduledquarterjustification_formatted?: string }>;
  ts_scheduledtimeofarrival: WebAttribute<msdyn_workorder_Select, { ts_scheduledtimeofarrival: Date | null }, { ts_scheduledtimeofarrival_formatted?: string }>;
  ts_scheduledtimeofdeparture: WebAttribute<msdyn_workorder_Select, { ts_scheduledtimeofdeparture: Date | null }, { ts_scheduledtimeofdeparture_formatted?: string }>;
  ts_securityincident_guid: WebAttribute<msdyn_workorder_Select, { ts_securityincident_guid: string | null }, { ts_securityincident_formatted?: string }>;
  ts_site_guid: WebAttribute<msdyn_workorder_Select, { ts_site_guid: string | null }, { ts_site_formatted?: string }>;
  ts_state: WebAttribute<msdyn_workorder_Select, { ts_state: ts_planningstate | null }, { ts_state_formatted?: string }>;
  ts_subsubsite_guid: WebAttribute<msdyn_workorder_Select, { ts_subsubsite_guid: string | null }, { ts_subsubsite_formatted?: string }>;
  ts_suggestedinspection_guid: WebAttribute<msdyn_workorder_Select, { ts_suggestedinspection_guid: string | null }, { ts_suggestedinspection_formatted?: string }>;
  ts_teamplanningdata_guid: WebAttribute<msdyn_workorder_Select, { ts_teamplanningdata_guid: string | null }, { ts_teamplanningdata_formatted?: string }>;
  ts_totalconductoversight: WebAttribute<msdyn_workorder_Select, { ts_totalconductoversight: number | null }, {  }>;
  ts_totalconductoversight_date: WebAttribute<msdyn_workorder_Select, { ts_totalconductoversight_date: Date | null }, { ts_totalconductoversight_date_formatted?: string }>;
  ts_totalconductoversight_state: WebAttribute<msdyn_workorder_Select, { ts_totalconductoversight_state: number | null }, {  }>;
  ts_totalpreparationtime: WebAttribute<msdyn_workorder_Select, { ts_totalpreparationtime: number | null }, {  }>;
  ts_totalpreparationtime_date: WebAttribute<msdyn_workorder_Select, { ts_totalpreparationtime_date: Date | null }, { ts_totalpreparationtime_date_formatted?: string }>;
  ts_totalpreparationtime_state: WebAttribute<msdyn_workorder_Select, { ts_totalpreparationtime_state: number | null }, {  }>;
  ts_totalrepanddoctime: WebAttribute<msdyn_workorder_Select, { ts_totalrepanddoctime: number | null }, {  }>;
  ts_totalrepanddoctime_date: WebAttribute<msdyn_workorder_Select, { ts_totalrepanddoctime_date: Date | null }, { ts_totalrepanddoctime_date_formatted?: string }>;
  ts_totalrepanddoctime_state: WebAttribute<msdyn_workorder_Select, { ts_totalrepanddoctime_state: number | null }, {  }>;
  ts_totaltraveltime: WebAttribute<msdyn_workorder_Select, { ts_totaltraveltime: number | null }, {  }>;
  ts_totaltraveltime_date: WebAttribute<msdyn_workorder_Select, { ts_totaltraveltime_date: Date | null }, { ts_totaltraveltime_date_formatted?: string }>;
  ts_totaltraveltime_state: WebAttribute<msdyn_workorder_Select, { ts_totaltraveltime_state: number | null }, {  }>;
  ts_tradenameid_guid: WebAttribute<msdyn_workorder_Select, { ts_tradenameid_guid: string | null }, { ts_tradenameid_formatted?: string }>;
  ts_traveltime: WebAttribute<msdyn_workorder_Select, { ts_traveltime: number | null }, {  }>;
  ts_trip_guid: WebAttribute<msdyn_workorder_Select, { ts_trip_guid: string | null }, { ts_trip_formatted?: string }>;
  ts_woreportinganddocumentation: WebAttribute<msdyn_workorder_Select, { ts_woreportinganddocumentation: number | null }, {  }>;
  ts_workordercreationwizardid_guid: WebAttribute<msdyn_workorder_Select, { ts_workordercreationwizardid_guid: string | null }, { ts_workordercreationwizardid_formatted?: string }>;
  ts_workorderenddate: WebAttribute<msdyn_workorder_Select, { ts_workorderenddate: Date | null }, { ts_workorderenddate_formatted?: string }>;
  ts_workorderstartdate: WebAttribute<msdyn_workorder_Select, { ts_workorderstartdate: Date | null }, { ts_workorderstartdate_formatted?: string }>;
  utcconversiontimezonecode: WebAttribute<msdyn_workorder_Select, { utcconversiontimezonecode: number | null }, {  }>;
  versionnumber: WebAttribute<msdyn_workorder_Select, { versionnumber: number | null }, {  }>;
}
interface msdyn_workorder_Filter {
  createdby_guid: XQW.Guid;
  createdon: Date;
  createdonbehalfby_guid: XQW.Guid;
  exchangerate: any;
  importsequencenumber: number;
  modifiedby_guid: XQW.Guid;
  modifiedon: Date;
  modifiedonbehalfby_guid: XQW.Guid;
  msdyn_address1: string;
  msdyn_address2: string;
  msdyn_address3: string;
  msdyn_addressname: string;
  msdyn_agreement_guid: XQW.Guid;
  msdyn_autonumbering: string;
  msdyn_billingaccount_guid: XQW.Guid;
  msdyn_bookingsummary: string;
  msdyn_childindex: number;
  msdyn_city: string;
  msdyn_closedby_guid: XQW.Guid;
  msdyn_completedon: Date;
  msdyn_costntepercent: number;
  msdyn_country: string;
  msdyn_customerasset_guid: XQW.Guid;
  msdyn_datewindowend: Date;
  msdyn_datewindowstart: Date;
  msdyn_displayaddress: string;
  msdyn_estimatesubtotalamount: number;
  msdyn_estimatesubtotalamount_base: number;
  msdyn_firstarrivedon: Date;
  msdyn_followupnote: string;
  msdyn_followuprequired: boolean;
  msdyn_functionallocation_guid: XQW.Guid;
  msdyn_instructions: string;
  msdyn_internalflags: string;
  msdyn_iotalert_guid: XQW.Guid;
  msdyn_isfollowup: boolean;
  msdyn_ismobile: boolean;
  msdyn_latitude: number;
  msdyn_longitude: number;
  msdyn_mapcontrol: string;
  msdyn_name: string;
  msdyn_nottoexceedcostamount: number;
  msdyn_nottoexceedcostamount_base: number;
  msdyn_nottoexceedpriceamount: number;
  msdyn_nottoexceedpriceamount_base: number;
  msdyn_opportunityid_guid: XQW.Guid;
  msdyn_parentworkorder_guid: XQW.Guid;
  msdyn_phoneNumber: string;
  msdyn_postalcode: string;
  msdyn_preferredresource_guid: XQW.Guid;
  msdyn_pricelist_guid: XQW.Guid;
  msdyn_pricentepercent: number;
  msdyn_primaryincidentdescription: string;
  msdyn_primaryincidentestimatedduration: number;
  msdyn_primaryincidenttype_guid: XQW.Guid;
  msdyn_primaryresolution_guid: XQW.Guid;
  msdyn_priority_guid: XQW.Guid;
  msdyn_productsservicescost: number;
  msdyn_productsservicescost_base: number;
  msdyn_productsservicesestimatedcost: number;
  msdyn_productsservicesestimatedcost_base: number;
  msdyn_reportedbycontact_guid: XQW.Guid;
  msdyn_serviceaccount_guid: XQW.Guid;
  msdyn_servicerequest_guid: XQW.Guid;
  msdyn_serviceterritory_guid: XQW.Guid;
  msdyn_stateorprovince: string;
  msdyn_substatus_guid: XQW.Guid;
  msdyn_subtotalamount: number;
  msdyn_subtotalamount_base: number;
  msdyn_supportcontact_guid: XQW.Guid;
  msdyn_systemstatus: msdyn_wosystemstatus;
  msdyn_taxable: boolean;
  msdyn_taxcode_guid: XQW.Guid;
  msdyn_timeclosed: Date;
  msdyn_timefrompromised: Date;
  msdyn_timegroup_guid: XQW.Guid;
  msdyn_timegroupdetailselected_guid: XQW.Guid;
  msdyn_timetopromised: Date;
  msdyn_timewindowend: Date;
  msdyn_timewindowstart: Date;
  msdyn_totalamount: number;
  msdyn_totalamount_base: number;
  msdyn_totalestimatedaftertaxprice: number;
  msdyn_totalestimatedaftertaxprice_base: number;
  msdyn_totalestimatedduration: number;
  msdyn_totalsalestax: number;
  msdyn_totalsalestax_base: number;
  msdyn_trade_guid: XQW.Guid;
  msdyn_workhourtemplate_guid: XQW.Guid;
  msdyn_worklocation: msdyn_worklocation;
  msdyn_workorderarrivaltimekpiid_guid: XQW.Guid;
  msdyn_workorderid: XQW.Guid;
  msdyn_workorderresolutionkpiid_guid: XQW.Guid;
  msdyn_workordersummary: string;
  msdyn_workordertype_guid: XQW.Guid;
  overriddencreatedon: Date;
  ovs_asset_guid: XQW.Guid;
  ovs_assetcategory_guid: XQW.Guid;
  ovs_currentfiscalquarter_guid: XQW.Guid;
  ovs_fiscalquarter_guid: XQW.Guid;
  ovs_fiscalyear_guid: XQW.Guid;
  ovs_iisid: string;
  ovs_mocid: string;
  ovs_operationid_guid: XQW.Guid;
  ovs_operationtypeid_guid: XQW.Guid;
  ovs_primaryinspector_guid: XQW.Guid;
  ovs_rational_guid: XQW.Guid;
  ovs_revisedquarterid_guid: XQW.Guid;
  ovs_secondaryinspector_guid: XQW.Guid;
  ovs_tyrational_guid: XQW.Guid;
  ownerid_guid: XQW.Guid;
  owningbusinessunit_guid: XQW.Guid;
  owningteam_guid: XQW.Guid;
  owninguser_guid: XQW.Guid;
  processid: XQW.Guid;
  qm_blobpath: string;
  qm_remote: boolean;
  qm_reportcontactid_guid: XQW.Guid;
  stageid: XQW.Guid;
  statecode: msdyn_workorder_statecode;
  statuscode: msdyn_workorder_statuscode;
  timezoneruleversionnumber: number;
  transactioncurrencyid_guid: XQW.Guid;
  traversedpath: string;
  ts_accountableteam_guid: XQW.Guid;
  ts_actualcost: number;
  ts_actualcost_base: number;
  ts_actualtimeofarrival: Date;
  ts_actualtimeofdeparture: Date;
  ts_aircraftclassification: ts_aircraftclassification;
  ts_aircraftregistration: string;
  ts_airserviceclassification: ts_airserviceclassification;
  ts_alternateoperatingcarrier: ts_yesno;
  ts_arrivalaerodrome_guid: XQW.Guid;
  ts_canceledinspectionjustification_guid: XQW.Guid;
  ts_cantcompleteinspection: boolean;
  ts_canvasappnumber: string;
  ts_cargoonlyflight: boolean;
  ts_casetimetracking_guid: XQW.Guid;
  ts_checkedbagsboarded: number;
  ts_checkedbagscheckedin: number;
  ts_comments: string;
  ts_completedquarter: ts_msdyn_workorder_ts_completedquarter;
  ts_conductingoversight: any;
  ts_contact_guid: XQW.Guid;
  ts_costexplanation: string;
  ts_country_guid: XQW.Guid;
  ts_departureaerodrome_guid: XQW.Guid;
  ts_details: string;
  ts_documenteddate: Date;
  ts_flightnumber: string;
  ts_flighttype: ts_flighttype;
  ts_incident: ts_yesno;
  ts_incompleteworkorderreason_guid: XQW.Guid;
  ts_incompleteworkorderreasonforother: string;
  ts_isisso: number;
  ts_justificationcomment: string;
  ts_notes: string;
  ts_numberoffindings: number;
  ts_numberoffindings_date: Date;
  ts_numberoffindings_state: number;
  ts_operatingcarrier_guid: XQW.Guid;
  ts_operatingname_guid: XQW.Guid;
  ts_origin: string;
  ts_othercanceledjustification: string;
  ts_overtime: any;
  ts_overtimerequired: boolean;
  ts_paxboarded: number;
  ts_paxcheckedin: number;
  ts_plan_guid: XQW.Guid;
  ts_plannedcost: number;
  ts_plannedcost_base: number;
  ts_planningdata_guid: XQW.Guid;
  ts_preparationtime: any;
  ts_quarterofconductingoversight: ts_quarter;
  ts_quarterofpreparationtime: ts_quarter;
  ts_quarterofreportinganddocumentation: ts_quarter;
  ts_quarteroftraveltime: ts_quarter;
  ts_reason_guid: XQW.Guid;
  ts_reasontext: string;
  ts_region_guid: XQW.Guid;
  ts_registration_guid: XQW.Guid;
  ts_reportdetails: string;
  ts_riskscore: number;
  ts_riskthreshold_guid: XQW.Guid;
  ts_scheduledquarterjustification_guid: XQW.Guid;
  ts_scheduledtimeofarrival: Date;
  ts_scheduledtimeofdeparture: Date;
  ts_securityincident_guid: XQW.Guid;
  ts_site_guid: XQW.Guid;
  ts_state: ts_planningstate;
  ts_subsubsite_guid: XQW.Guid;
  ts_suggestedinspection_guid: XQW.Guid;
  ts_teamplanningdata_guid: XQW.Guid;
  ts_totalconductoversight: any;
  ts_totalconductoversight_date: Date;
  ts_totalconductoversight_state: number;
  ts_totalpreparationtime: any;
  ts_totalpreparationtime_date: Date;
  ts_totalpreparationtime_state: number;
  ts_totalrepanddoctime: any;
  ts_totalrepanddoctime_date: Date;
  ts_totalrepanddoctime_state: number;
  ts_totaltraveltime: any;
  ts_totaltraveltime_date: Date;
  ts_totaltraveltime_state: number;
  ts_tradenameid_guid: XQW.Guid;
  ts_traveltime: any;
  ts_trip_guid: XQW.Guid;
  ts_woreportinganddocumentation: any;
  ts_workordercreationwizardid_guid: XQW.Guid;
  ts_workorderenddate: Date;
  ts_workorderstartdate: Date;
  utcconversiontimezonecode: number;
  versionnumber: number;
}
interface msdyn_workorder_Expand {
  createdby: WebExpand<msdyn_workorder_Expand, SystemUser_Select, SystemUser_Filter, { createdby: SystemUser_Result }>;
  createdonbehalfby: WebExpand<msdyn_workorder_Expand, SystemUser_Select, SystemUser_Filter, { createdonbehalfby: SystemUser_Result }>;
  modifiedby: WebExpand<msdyn_workorder_Expand, SystemUser_Select, SystemUser_Filter, { modifiedby: SystemUser_Result }>;
  modifiedonbehalfby: WebExpand<msdyn_workorder_Expand, SystemUser_Select, SystemUser_Filter, { modifiedonbehalfby: SystemUser_Result }>;
  msdyn_FunctionalLocation: WebExpand<msdyn_workorder_Expand, msdyn_FunctionalLocation_Select, msdyn_FunctionalLocation_Filter, { msdyn_FunctionalLocation: msdyn_FunctionalLocation_Result }>;
  msdyn_SupportContact: WebExpand<msdyn_workorder_Expand, BookableResource_Select, BookableResource_Filter, { msdyn_SupportContact: BookableResource_Result }>;
  msdyn_billingaccount: WebExpand<msdyn_workorder_Expand, Account_Select, Account_Filter, { msdyn_billingaccount: Account_Result }>;
  msdyn_closedby: WebExpand<msdyn_workorder_Expand, SystemUser_Select, SystemUser_Filter, { msdyn_closedby: SystemUser_Result }>;
  msdyn_customerasset: WebExpand<msdyn_workorder_Expand, msdyn_customerasset_Select, msdyn_customerasset_Filter, { msdyn_customerasset: msdyn_customerasset_Result }>;
  msdyn_msdyn_workorder_bookableresourcebooking_WorkOrder: WebExpand<msdyn_workorder_Expand, BookableResourceBooking_Select, BookableResourceBooking_Filter, { msdyn_msdyn_workorder_bookableresourcebooking_WorkOrder: BookableResourceBooking_Result[] }>;
  msdyn_msdyn_workorder_msdyn_workorder_ParentWorkOrder: WebExpand<msdyn_workorder_Expand, msdyn_workorder_Select, msdyn_workorder_Filter, { msdyn_msdyn_workorder_msdyn_workorder_ParentWorkOrder: msdyn_workorder_Result[] }>;
  msdyn_msdyn_workorder_msdyn_workorderservicetask_WorkOrder: WebExpand<msdyn_workorder_Expand, msdyn_workorderservicetask_Select, msdyn_workorderservicetask_Filter, { msdyn_msdyn_workorder_msdyn_workorderservicetask_WorkOrder: msdyn_workorderservicetask_Result[] }>;
  msdyn_parentworkorder_msdyn_workorder: WebExpand<msdyn_workorder_Expand, msdyn_workorder_Select, msdyn_workorder_Filter, { msdyn_parentworkorder_msdyn_workorder: msdyn_workorder_Result }>;
  msdyn_preferredresource: WebExpand<msdyn_workorder_Expand, BookableResource_Select, BookableResource_Filter, { msdyn_preferredresource: BookableResource_Result }>;
  msdyn_primaryincidenttype: WebExpand<msdyn_workorder_Expand, msdyn_incidenttype_Select, msdyn_incidenttype_Filter, { msdyn_primaryincidenttype: msdyn_incidenttype_Result }>;
  msdyn_reportedbycontact: WebExpand<msdyn_workorder_Expand, Contact_Select, Contact_Filter, { msdyn_reportedbycontact: Contact_Result }>;
  msdyn_serviceaccount: WebExpand<msdyn_workorder_Expand, Account_Select, Account_Filter, { msdyn_serviceaccount: Account_Result }>;
  msdyn_servicerequest: WebExpand<msdyn_workorder_Expand, Incident_Select, Incident_Filter, { msdyn_servicerequest: Incident_Result }>;
  msdyn_workorder_Appointments: WebExpand<msdyn_workorder_Expand, Appointment_Select, Appointment_Filter, { msdyn_workorder_Appointments: Appointment_Result[] }>;
  msdyn_workorder_Emails: WebExpand<msdyn_workorder_Expand, Email_Select, Email_Filter, { msdyn_workorder_Emails: Email_Result[] }>;
  msdyn_workorder_PostFollows: WebExpand<msdyn_workorder_Expand, PostFollow_Select, PostFollow_Filter, { msdyn_workorder_PostFollows: PostFollow_Result[] }>;
  msdyn_workorder_ServiceAppointments: WebExpand<msdyn_workorder_Expand, ServiceAppointment_Select, ServiceAppointment_Filter, { msdyn_workorder_ServiceAppointments: ServiceAppointment_Result[] }>;
  msdyn_workorder_Teams: WebExpand<msdyn_workorder_Expand, Team_Select, Team_Filter, { msdyn_workorder_Teams: Team_Result[] }>;
  msdyn_workorder_connections1: WebExpand<msdyn_workorder_Expand, Connection_Select, Connection_Filter, { msdyn_workorder_connections1: Connection_Result[] }>;
  msdyn_workorder_connections2: WebExpand<msdyn_workorder_Expand, Connection_Select, Connection_Filter, { msdyn_workorder_connections2: Connection_Result[] }>;
  msdyn_workorder_ts_enforcementactions: WebExpand<msdyn_workorder_Expand, ts_enforcementaction_Select, ts_enforcementaction_Filter, { msdyn_workorder_ts_enforcementactions: ts_enforcementaction_Result[] }>;
  ovs_AssetCategory: WebExpand<msdyn_workorder_Expand, msdyn_customerassetcategory_Select, msdyn_customerassetcategory_Filter, { ovs_AssetCategory: msdyn_customerassetcategory_Result }>;
  ovs_CurrentFiscalQuarter: WebExpand<msdyn_workorder_Expand, tc_TCFiscalQuarter_Select, tc_TCFiscalQuarter_Filter, { ovs_CurrentFiscalQuarter: tc_TCFiscalQuarter_Result }>;
  ovs_FiscalQuarter: WebExpand<msdyn_workorder_Expand, tc_TCFiscalQuarter_Select, tc_TCFiscalQuarter_Filter, { ovs_FiscalQuarter: tc_TCFiscalQuarter_Result }>;
  ovs_FiscalYear: WebExpand<msdyn_workorder_Expand, tc_TCFiscalYear_Select, tc_TCFiscalYear_Filter, { ovs_FiscalYear: tc_TCFiscalYear_Result }>;
  ovs_OperationId: WebExpand<msdyn_workorder_Expand, ovs_operation_Select, ovs_operation_Filter, { ovs_OperationId: ovs_operation_Result }>;
  ovs_PrimaryInspector: WebExpand<msdyn_workorder_Expand, BookableResource_Select, BookableResource_Filter, { ovs_PrimaryInspector: BookableResource_Result }>;
  ovs_RevisedQuarterId: WebExpand<msdyn_workorder_Expand, tc_TCFiscalQuarter_Select, tc_TCFiscalQuarter_Filter, { ovs_RevisedQuarterId: tc_TCFiscalQuarter_Result }>;
  ovs_SecondaryInspector: WebExpand<msdyn_workorder_Expand, BookableResource_Select, BookableResource_Filter, { ovs_SecondaryInspector: BookableResource_Result }>;
  ovs_asset: WebExpand<msdyn_workorder_Expand, msdyn_customerasset_Select, msdyn_customerasset_Filter, { ovs_asset: msdyn_customerasset_Result }>;
  ownerid: WebExpand<msdyn_workorder_Expand, SystemUser_Select & Team_Select, SystemUser_Filter & Team_Filter, { ownerid: SystemUser_Result } & { ownerid: Team_Result }>;
  owningteam: WebExpand<msdyn_workorder_Expand, Team_Select, Team_Filter, { owningteam: Team_Result }>;
  owninguser: WebExpand<msdyn_workorder_Expand, SystemUser_Select, SystemUser_Filter, { owninguser: SystemUser_Result }>;
  qm_ReportContactId: WebExpand<msdyn_workorder_Expand, Contact_Select, Contact_Filter, { qm_ReportContactId: Contact_Result }>;
  ts_AccountableTeam: WebExpand<msdyn_workorder_Expand, Team_Select, Team_Filter, { ts_AccountableTeam: Team_Result }>;
  ts_CaseTimeTracking: WebExpand<msdyn_workorder_Expand, Incident_Select, Incident_Filter, { ts_CaseTimeTracking: Incident_Result }>;
  ts_Contact: WebExpand<msdyn_workorder_Expand, Contact_Select, Contact_Filter, { ts_Contact: Contact_Result }>;
  ts_Contact_msdyn_workorder_msdyn_workorder: WebExpand<msdyn_workorder_Expand, Contact_Select, Contact_Filter, { ts_Contact_msdyn_workorder_msdyn_workorder: Contact_Result[] }>;
  ts_IncompleteWorkOrderReason: WebExpand<msdyn_workorder_Expand, ts_IncompleteWorkOrderReason_Select, ts_IncompleteWorkOrderReason_Filter, { ts_IncompleteWorkOrderReason: ts_IncompleteWorkOrderReason_Result }>;
  ts_PlanningData: WebExpand<msdyn_workorder_Expand, ts_PlanningData_Select, ts_PlanningData_Filter, { ts_PlanningData: ts_PlanningData_Result }>;
  ts_SecurityIncident: WebExpand<msdyn_workorder_Expand, ts_securityincident_Select, ts_securityincident_Filter, { ts_SecurityIncident: ts_securityincident_Result }>;
  ts_Site: WebExpand<msdyn_workorder_Expand, msdyn_FunctionalLocation_Select, msdyn_FunctionalLocation_Filter, { ts_Site: msdyn_FunctionalLocation_Result }>;
  ts_Subsubsite: WebExpand<msdyn_workorder_Expand, msdyn_FunctionalLocation_Select, msdyn_FunctionalLocation_Filter, { ts_Subsubsite: msdyn_FunctionalLocation_Result }>;
  ts_TeamPlanningData: WebExpand<msdyn_workorder_Expand, ts_TeamPlanningData_Select, ts_TeamPlanningData_Filter, { ts_TeamPlanningData: ts_TeamPlanningData_Result }>;
  ts_WorkOrderCreationWizardId: WebExpand<msdyn_workorder_Expand, ts_workordercreationwizard_Select, ts_workordercreationwizard_Filter, { ts_WorkOrderCreationWizardId: ts_workordercreationwizard_Result }>;
  ts_arrivalaerodrome: WebExpand<msdyn_workorder_Expand, msdyn_FunctionalLocation_Select, msdyn_FunctionalLocation_Filter, { ts_arrivalaerodrome: msdyn_FunctionalLocation_Result }>;
  ts_canceledinspectionjustification: WebExpand<msdyn_workorder_Expand, ts_canceledinspectionjustification_Select, ts_canceledinspectionjustification_Filter, { ts_canceledinspectionjustification: ts_canceledinspectionjustification_Result }>;
  ts_departureaerodrome: WebExpand<msdyn_workorder_Expand, msdyn_FunctionalLocation_Select, msdyn_FunctionalLocation_Filter, { ts_departureaerodrome: msdyn_FunctionalLocation_Result }>;
  ts_incident_WorkOrder1_msdyn_workorder: WebExpand<msdyn_workorder_Expand, Incident_Select, Incident_Filter, { ts_incident_WorkOrder1_msdyn_workorder: Incident_Result[] }>;
  ts_incident_WorkOrder2_msdyn_workorder: WebExpand<msdyn_workorder_Expand, Incident_Select, Incident_Filter, { ts_incident_WorkOrder2_msdyn_workorder: Incident_Result[] }>;
  ts_msdyn_customerasset_msdyn_workorder_msdyn: WebExpand<msdyn_workorder_Expand, msdyn_customerasset_Select, msdyn_customerasset_Filter, { ts_msdyn_customerasset_msdyn_workorder_msdyn: msdyn_customerasset_Result[] }>;
  ts_msdyn_workorder_msdyn_workorder_Account: WebExpand<msdyn_workorder_Expand, Account_Select, Account_Filter, { ts_msdyn_workorder_msdyn_workorder_Account: Account_Result[] }>;
  ts_msdyn_workorder_ovs_operation_ovs_operati: WebExpand<msdyn_workorder_Expand, ovs_operation_Select, ovs_operation_Filter, { ts_msdyn_workorder_ovs_operation_ovs_operati: ovs_operation_Result[] }>;
  ts_msdyn_workorder_ts_operationcontact: WebExpand<msdyn_workorder_Expand, ts_operationcontact_Select, ts_operationcontact_Filter, { ts_msdyn_workorder_ts_operationcontact: ts_operationcontact_Result[] }>;
  ts_operatingcarrier: WebExpand<msdyn_workorder_Expand, Account_Select, Account_Filter, { ts_operatingcarrier: Account_Result }>;
  ts_operatingname: WebExpand<msdyn_workorder_Expand, Account_Select, Account_Filter, { ts_operatingname: Account_Result }>;
  ts_operationcontact_workorder_msdyn_worko: WebExpand<msdyn_workorder_Expand, ts_operationcontact_Select, ts_operationcontact_Filter, { ts_operationcontact_workorder_msdyn_worko: ts_operationcontact_Result[] }>;
  ts_ovs_Finding_WorkOrder_msdyn_workorder: WebExpand<msdyn_workorder_Expand, ovs_Finding_Select, ovs_Finding_Filter, { ts_ovs_Finding_WorkOrder_msdyn_workorder: ovs_Finding_Result[] }>;
  ts_plan: WebExpand<msdyn_workorder_Expand, ts_Plan_Select, ts_Plan_Filter, { ts_plan: ts_Plan_Result }>;
  ts_riskthreshold: WebExpand<msdyn_workorder_Expand, ts_RiskCategory_Select, ts_RiskCategory_Filter, { ts_riskthreshold: ts_RiskCategory_Result }>;
  ts_suggestedinspection: WebExpand<msdyn_workorder_Expand, ts_SuggestedInspection_Select, ts_SuggestedInspection_Filter, { ts_suggestedinspection: ts_SuggestedInspection_Result }>;
}
interface msdyn_workorder_FormattedResult {
  createdby_formatted?: string;
  createdon_formatted?: string;
  createdonbehalfby_formatted?: string;
  modifiedby_formatted?: string;
  modifiedon_formatted?: string;
  modifiedonbehalfby_formatted?: string;
  msdyn_agreement_formatted?: string;
  msdyn_billingaccount_formatted?: string;
  msdyn_closedby_formatted?: string;
  msdyn_completedon_formatted?: string;
  msdyn_customerasset_formatted?: string;
  msdyn_datewindowend_formatted?: string;
  msdyn_datewindowstart_formatted?: string;
  msdyn_estimatesubtotalamount_base_formatted?: string;
  msdyn_estimatesubtotalamount_formatted?: string;
  msdyn_firstarrivedon_formatted?: string;
  msdyn_functionallocation_formatted?: string;
  msdyn_iotalert_formatted?: string;
  msdyn_nottoexceedcostamount_base_formatted?: string;
  msdyn_nottoexceedcostamount_formatted?: string;
  msdyn_nottoexceedpriceamount_base_formatted?: string;
  msdyn_nottoexceedpriceamount_formatted?: string;
  msdyn_opportunityid_formatted?: string;
  msdyn_parentworkorder_formatted?: string;
  msdyn_preferredresource_formatted?: string;
  msdyn_pricelist_formatted?: string;
  msdyn_primaryincidenttype_formatted?: string;
  msdyn_primaryresolution_formatted?: string;
  msdyn_priority_formatted?: string;
  msdyn_productsservicescost_base_formatted?: string;
  msdyn_productsservicescost_formatted?: string;
  msdyn_productsservicesestimatedcost_base_formatted?: string;
  msdyn_productsservicesestimatedcost_formatted?: string;
  msdyn_reportedbycontact_formatted?: string;
  msdyn_serviceaccount_formatted?: string;
  msdyn_servicerequest_formatted?: string;
  msdyn_serviceterritory_formatted?: string;
  msdyn_substatus_formatted?: string;
  msdyn_subtotalamount_base_formatted?: string;
  msdyn_subtotalamount_formatted?: string;
  msdyn_supportcontact_formatted?: string;
  msdyn_systemstatus_formatted?: string;
  msdyn_taxcode_formatted?: string;
  msdyn_timeclosed_formatted?: string;
  msdyn_timefrompromised_formatted?: string;
  msdyn_timegroup_formatted?: string;
  msdyn_timegroupdetailselected_formatted?: string;
  msdyn_timetopromised_formatted?: string;
  msdyn_timewindowend_formatted?: string;
  msdyn_timewindowstart_formatted?: string;
  msdyn_totalamount_base_formatted?: string;
  msdyn_totalamount_formatted?: string;
  msdyn_totalestimatedaftertaxprice_base_formatted?: string;
  msdyn_totalestimatedaftertaxprice_formatted?: string;
  msdyn_totalsalestax_base_formatted?: string;
  msdyn_totalsalestax_formatted?: string;
  msdyn_trade_formatted?: string;
  msdyn_workhourtemplate_formatted?: string;
  msdyn_worklocation_formatted?: string;
  msdyn_workorderarrivaltimekpiid_formatted?: string;
  msdyn_workorderresolutionkpiid_formatted?: string;
  msdyn_workordertype_formatted?: string;
  overriddencreatedon_formatted?: string;
  ovs_asset_formatted?: string;
  ovs_assetcategory_formatted?: string;
  ovs_currentfiscalquarter_formatted?: string;
  ovs_fiscalquarter_formatted?: string;
  ovs_fiscalyear_formatted?: string;
  ovs_operationid_formatted?: string;
  ovs_operationtypeid_formatted?: string;
  ovs_primaryinspector_formatted?: string;
  ovs_rational_formatted?: string;
  ovs_revisedquarterid_formatted?: string;
  ovs_secondaryinspector_formatted?: string;
  ovs_tyrational_formatted?: string;
  ownerid_formatted?: string;
  owningbusinessunit_formatted?: string;
  owningteam_formatted?: string;
  owninguser_formatted?: string;
  qm_reportcontactid_formatted?: string;
  statecode_formatted?: string;
  statuscode_formatted?: string;
  transactioncurrencyid_formatted?: string;
  ts_accountableteam_formatted?: string;
  ts_actualcost_base_formatted?: string;
  ts_actualcost_formatted?: string;
  ts_actualtimeofarrival_formatted?: string;
  ts_actualtimeofdeparture_formatted?: string;
  ts_aircraftclassification_formatted?: string;
  ts_airserviceclassification_formatted?: string;
  ts_alternateoperatingcarrier_formatted?: string;
  ts_arrivalaerodrome_formatted?: string;
  ts_canceledinspectionjustification_formatted?: string;
  ts_casetimetracking_formatted?: string;
  ts_completedquarter_formatted?: string;
  ts_contact_formatted?: string;
  ts_country_formatted?: string;
  ts_departureaerodrome_formatted?: string;
  ts_documenteddate_formatted?: string;
  ts_flighttype_formatted?: string;
  ts_incident_formatted?: string;
  ts_incompleteworkorderreason_formatted?: string;
  ts_numberoffindings_date_formatted?: string;
  ts_operatingcarrier_formatted?: string;
  ts_operatingname_formatted?: string;
  ts_plan_formatted?: string;
  ts_plannedcost_base_formatted?: string;
  ts_plannedcost_formatted?: string;
  ts_planningdata_formatted?: string;
  ts_quarterofconductingoversight_formatted?: string;
  ts_quarterofpreparationtime_formatted?: string;
  ts_quarterofreportinganddocumentation_formatted?: string;
  ts_quarteroftraveltime_formatted?: string;
  ts_reason_formatted?: string;
  ts_region_formatted?: string;
  ts_registration_formatted?: string;
  ts_riskthreshold_formatted?: string;
  ts_scheduledquarterjustification_formatted?: string;
  ts_scheduledtimeofarrival_formatted?: string;
  ts_scheduledtimeofdeparture_formatted?: string;
  ts_securityincident_formatted?: string;
  ts_site_formatted?: string;
  ts_state_formatted?: string;
  ts_subsubsite_formatted?: string;
  ts_suggestedinspection_formatted?: string;
  ts_teamplanningdata_formatted?: string;
  ts_totalconductoversight_date_formatted?: string;
  ts_totalpreparationtime_date_formatted?: string;
  ts_totalrepanddoctime_date_formatted?: string;
  ts_totaltraveltime_date_formatted?: string;
  ts_tradenameid_formatted?: string;
  ts_trip_formatted?: string;
  ts_workordercreationwizardid_formatted?: string;
  ts_workorderenddate_formatted?: string;
  ts_workorderstartdate_formatted?: string;
}
interface msdyn_workorder_Result extends msdyn_workorder_Base, msdyn_workorder_Relationships {
  "@odata.etag": string;
  createdby_guid: string | null;
  createdonbehalfby_guid: string | null;
  modifiedby_guid: string | null;
  modifiedonbehalfby_guid: string | null;
  msdyn_agreement_guid: string | null;
  msdyn_billingaccount_guid: string | null;
  msdyn_closedby_guid: string | null;
  msdyn_customerasset_guid: string | null;
  msdyn_functionallocation_guid: string | null;
  msdyn_iotalert_guid: string | null;
  msdyn_opportunityid_guid: string | null;
  msdyn_parentworkorder_guid: string | null;
  msdyn_preferredresource_guid: string | null;
  msdyn_pricelist_guid: string | null;
  msdyn_primaryincidenttype_guid: string | null;
  msdyn_primaryresolution_guid: string | null;
  msdyn_priority_guid: string | null;
  msdyn_reportedbycontact_guid: string | null;
  msdyn_serviceaccount_guid: string | null;
  msdyn_servicerequest_guid: string | null;
  msdyn_serviceterritory_guid: string | null;
  msdyn_substatus_guid: string | null;
  msdyn_supportcontact_guid: string | null;
  msdyn_taxcode_guid: string | null;
  msdyn_timegroup_guid: string | null;
  msdyn_timegroupdetailselected_guid: string | null;
  msdyn_trade_guid: string | null;
  msdyn_workhourtemplate_guid: string | null;
  msdyn_workorderarrivaltimekpiid_guid: string | null;
  msdyn_workorderresolutionkpiid_guid: string | null;
  msdyn_workordertype_guid: string | null;
  ovs_asset_guid: string | null;
  ovs_assetcategory_guid: string | null;
  ovs_currentfiscalquarter_guid: string | null;
  ovs_fiscalquarter_guid: string | null;
  ovs_fiscalyear_guid: string | null;
  ovs_operationid_guid: string | null;
  ovs_operationtypeid_guid: string | null;
  ovs_primaryinspector_guid: string | null;
  ovs_rational_guid: string | null;
  ovs_revisedquarterid_guid: string | null;
  ovs_secondaryinspector_guid: string | null;
  ovs_tyrational_guid: string | null;
  ownerid_guid: string | null;
  owningbusinessunit_guid: string | null;
  owningteam_guid: string | null;
  owninguser_guid: string | null;
  qm_reportcontactid_guid: string | null;
  transactioncurrencyid_guid: string | null;
  ts_accountableteam_guid: string | null;
  ts_arrivalaerodrome_guid: string | null;
  ts_canceledinspectionjustification_guid: string | null;
  ts_casetimetracking_guid: string | null;
  ts_contact_guid: string | null;
  ts_country_guid: string | null;
  ts_departureaerodrome_guid: string | null;
  ts_incompleteworkorderreason_guid: string | null;
  ts_operatingcarrier_guid: string | null;
  ts_operatingname_guid: string | null;
  ts_plan_guid: string | null;
  ts_planningdata_guid: string | null;
  ts_reason_guid: string | null;
  ts_region_guid: string | null;
  ts_registration_guid: string | null;
  ts_riskthreshold_guid: string | null;
  ts_scheduledquarterjustification_guid: string | null;
  ts_securityincident_guid: string | null;
  ts_site_guid: string | null;
  ts_subsubsite_guid: string | null;
  ts_suggestedinspection_guid: string | null;
  ts_teamplanningdata_guid: string | null;
  ts_tradenameid_guid: string | null;
  ts_trip_guid: string | null;
  ts_workordercreationwizardid_guid: string | null;
}
interface msdyn_workorder_RelatedOne {
  createdby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  createdonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  msdyn_FunctionalLocation: WebMappingRetrieve<msdyn_FunctionalLocation_Select,msdyn_FunctionalLocation_Expand,msdyn_FunctionalLocation_Filter,msdyn_FunctionalLocation_Fixed,msdyn_FunctionalLocation_Result,msdyn_FunctionalLocation_FormattedResult>;
  msdyn_SupportContact: WebMappingRetrieve<BookableResource_Select,BookableResource_Expand,BookableResource_Filter,BookableResource_Fixed,BookableResource_Result,BookableResource_FormattedResult>;
  msdyn_billingaccount: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  msdyn_closedby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  msdyn_customerasset: WebMappingRetrieve<msdyn_customerasset_Select,msdyn_customerasset_Expand,msdyn_customerasset_Filter,msdyn_customerasset_Fixed,msdyn_customerasset_Result,msdyn_customerasset_FormattedResult>;
  msdyn_parentworkorder_msdyn_workorder: WebMappingRetrieve<msdyn_workorder_Select,msdyn_workorder_Expand,msdyn_workorder_Filter,msdyn_workorder_Fixed,msdyn_workorder_Result,msdyn_workorder_FormattedResult>;
  msdyn_preferredresource: WebMappingRetrieve<BookableResource_Select,BookableResource_Expand,BookableResource_Filter,BookableResource_Fixed,BookableResource_Result,BookableResource_FormattedResult>;
  msdyn_primaryincidenttype: WebMappingRetrieve<msdyn_incidenttype_Select,msdyn_incidenttype_Expand,msdyn_incidenttype_Filter,msdyn_incidenttype_Fixed,msdyn_incidenttype_Result,msdyn_incidenttype_FormattedResult>;
  msdyn_reportedbycontact: WebMappingRetrieve<Contact_Select,Contact_Expand,Contact_Filter,Contact_Fixed,Contact_Result,Contact_FormattedResult>;
  msdyn_serviceaccount: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  msdyn_servicerequest: WebMappingRetrieve<Incident_Select,Incident_Expand,Incident_Filter,Incident_Fixed,Incident_Result,Incident_FormattedResult>;
  ovs_AssetCategory: WebMappingRetrieve<msdyn_customerassetcategory_Select,msdyn_customerassetcategory_Expand,msdyn_customerassetcategory_Filter,msdyn_customerassetcategory_Fixed,msdyn_customerassetcategory_Result,msdyn_customerassetcategory_FormattedResult>;
  ovs_CurrentFiscalQuarter: WebMappingRetrieve<tc_TCFiscalQuarter_Select,tc_TCFiscalQuarter_Expand,tc_TCFiscalQuarter_Filter,tc_TCFiscalQuarter_Fixed,tc_TCFiscalQuarter_Result,tc_TCFiscalQuarter_FormattedResult>;
  ovs_FiscalQuarter: WebMappingRetrieve<tc_TCFiscalQuarter_Select,tc_TCFiscalQuarter_Expand,tc_TCFiscalQuarter_Filter,tc_TCFiscalQuarter_Fixed,tc_TCFiscalQuarter_Result,tc_TCFiscalQuarter_FormattedResult>;
  ovs_FiscalYear: WebMappingRetrieve<tc_TCFiscalYear_Select,tc_TCFiscalYear_Expand,tc_TCFiscalYear_Filter,tc_TCFiscalYear_Fixed,tc_TCFiscalYear_Result,tc_TCFiscalYear_FormattedResult>;
  ovs_OperationId: WebMappingRetrieve<ovs_operation_Select,ovs_operation_Expand,ovs_operation_Filter,ovs_operation_Fixed,ovs_operation_Result,ovs_operation_FormattedResult>;
  ovs_PrimaryInspector: WebMappingRetrieve<BookableResource_Select,BookableResource_Expand,BookableResource_Filter,BookableResource_Fixed,BookableResource_Result,BookableResource_FormattedResult>;
  ovs_RevisedQuarterId: WebMappingRetrieve<tc_TCFiscalQuarter_Select,tc_TCFiscalQuarter_Expand,tc_TCFiscalQuarter_Filter,tc_TCFiscalQuarter_Fixed,tc_TCFiscalQuarter_Result,tc_TCFiscalQuarter_FormattedResult>;
  ovs_SecondaryInspector: WebMappingRetrieve<BookableResource_Select,BookableResource_Expand,BookableResource_Filter,BookableResource_Fixed,BookableResource_Result,BookableResource_FormattedResult>;
  ovs_asset: WebMappingRetrieve<msdyn_customerasset_Select,msdyn_customerasset_Expand,msdyn_customerasset_Filter,msdyn_customerasset_Fixed,msdyn_customerasset_Result,msdyn_customerasset_FormattedResult>;
  ownerid: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult> & WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owningteam: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owninguser: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  qm_ReportContactId: WebMappingRetrieve<Contact_Select,Contact_Expand,Contact_Filter,Contact_Fixed,Contact_Result,Contact_FormattedResult>;
  ts_AccountableTeam: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  ts_CaseTimeTracking: WebMappingRetrieve<Incident_Select,Incident_Expand,Incident_Filter,Incident_Fixed,Incident_Result,Incident_FormattedResult>;
  ts_Contact: WebMappingRetrieve<Contact_Select,Contact_Expand,Contact_Filter,Contact_Fixed,Contact_Result,Contact_FormattedResult>;
  ts_IncompleteWorkOrderReason: WebMappingRetrieve<ts_IncompleteWorkOrderReason_Select,ts_IncompleteWorkOrderReason_Expand,ts_IncompleteWorkOrderReason_Filter,ts_IncompleteWorkOrderReason_Fixed,ts_IncompleteWorkOrderReason_Result,ts_IncompleteWorkOrderReason_FormattedResult>;
  ts_PlanningData: WebMappingRetrieve<ts_PlanningData_Select,ts_PlanningData_Expand,ts_PlanningData_Filter,ts_PlanningData_Fixed,ts_PlanningData_Result,ts_PlanningData_FormattedResult>;
  ts_SecurityIncident: WebMappingRetrieve<ts_securityincident_Select,ts_securityincident_Expand,ts_securityincident_Filter,ts_securityincident_Fixed,ts_securityincident_Result,ts_securityincident_FormattedResult>;
  ts_Site: WebMappingRetrieve<msdyn_FunctionalLocation_Select,msdyn_FunctionalLocation_Expand,msdyn_FunctionalLocation_Filter,msdyn_FunctionalLocation_Fixed,msdyn_FunctionalLocation_Result,msdyn_FunctionalLocation_FormattedResult>;
  ts_Subsubsite: WebMappingRetrieve<msdyn_FunctionalLocation_Select,msdyn_FunctionalLocation_Expand,msdyn_FunctionalLocation_Filter,msdyn_FunctionalLocation_Fixed,msdyn_FunctionalLocation_Result,msdyn_FunctionalLocation_FormattedResult>;
  ts_TeamPlanningData: WebMappingRetrieve<ts_TeamPlanningData_Select,ts_TeamPlanningData_Expand,ts_TeamPlanningData_Filter,ts_TeamPlanningData_Fixed,ts_TeamPlanningData_Result,ts_TeamPlanningData_FormattedResult>;
  ts_WorkOrderCreationWizardId: WebMappingRetrieve<ts_workordercreationwizard_Select,ts_workordercreationwizard_Expand,ts_workordercreationwizard_Filter,ts_workordercreationwizard_Fixed,ts_workordercreationwizard_Result,ts_workordercreationwizard_FormattedResult>;
  ts_arrivalaerodrome: WebMappingRetrieve<msdyn_FunctionalLocation_Select,msdyn_FunctionalLocation_Expand,msdyn_FunctionalLocation_Filter,msdyn_FunctionalLocation_Fixed,msdyn_FunctionalLocation_Result,msdyn_FunctionalLocation_FormattedResult>;
  ts_canceledinspectionjustification: WebMappingRetrieve<ts_canceledinspectionjustification_Select,ts_canceledinspectionjustification_Expand,ts_canceledinspectionjustification_Filter,ts_canceledinspectionjustification_Fixed,ts_canceledinspectionjustification_Result,ts_canceledinspectionjustification_FormattedResult>;
  ts_departureaerodrome: WebMappingRetrieve<msdyn_FunctionalLocation_Select,msdyn_FunctionalLocation_Expand,msdyn_FunctionalLocation_Filter,msdyn_FunctionalLocation_Fixed,msdyn_FunctionalLocation_Result,msdyn_FunctionalLocation_FormattedResult>;
  ts_operatingcarrier: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  ts_operatingname: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  ts_plan: WebMappingRetrieve<ts_Plan_Select,ts_Plan_Expand,ts_Plan_Filter,ts_Plan_Fixed,ts_Plan_Result,ts_Plan_FormattedResult>;
  ts_riskthreshold: WebMappingRetrieve<ts_RiskCategory_Select,ts_RiskCategory_Expand,ts_RiskCategory_Filter,ts_RiskCategory_Fixed,ts_RiskCategory_Result,ts_RiskCategory_FormattedResult>;
  ts_suggestedinspection: WebMappingRetrieve<ts_SuggestedInspection_Select,ts_SuggestedInspection_Expand,ts_SuggestedInspection_Filter,ts_SuggestedInspection_Fixed,ts_SuggestedInspection_Result,ts_SuggestedInspection_FormattedResult>;
}
interface msdyn_workorder_RelatedMany {
  msdyn_msdyn_workorder_bookableresourcebooking_WorkOrder: WebMappingRetrieve<BookableResourceBooking_Select,BookableResourceBooking_Expand,BookableResourceBooking_Filter,BookableResourceBooking_Fixed,BookableResourceBooking_Result,BookableResourceBooking_FormattedResult>;
  msdyn_msdyn_workorder_msdyn_workorder_ParentWorkOrder: WebMappingRetrieve<msdyn_workorder_Select,msdyn_workorder_Expand,msdyn_workorder_Filter,msdyn_workorder_Fixed,msdyn_workorder_Result,msdyn_workorder_FormattedResult>;
  msdyn_msdyn_workorder_msdyn_workorderservicetask_WorkOrder: WebMappingRetrieve<msdyn_workorderservicetask_Select,msdyn_workorderservicetask_Expand,msdyn_workorderservicetask_Filter,msdyn_workorderservicetask_Fixed,msdyn_workorderservicetask_Result,msdyn_workorderservicetask_FormattedResult>;
  msdyn_workorder_Appointments: WebMappingRetrieve<Appointment_Select,Appointment_Expand,Appointment_Filter,Appointment_Fixed,Appointment_Result,Appointment_FormattedResult>;
  msdyn_workorder_Emails: WebMappingRetrieve<Email_Select,Email_Expand,Email_Filter,Email_Fixed,Email_Result,Email_FormattedResult>;
  msdyn_workorder_PostFollows: WebMappingRetrieve<PostFollow_Select,PostFollow_Expand,PostFollow_Filter,PostFollow_Fixed,PostFollow_Result,PostFollow_FormattedResult>;
  msdyn_workorder_ServiceAppointments: WebMappingRetrieve<ServiceAppointment_Select,ServiceAppointment_Expand,ServiceAppointment_Filter,ServiceAppointment_Fixed,ServiceAppointment_Result,ServiceAppointment_FormattedResult>;
  msdyn_workorder_Teams: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  msdyn_workorder_connections1: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  msdyn_workorder_connections2: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  msdyn_workorder_ts_enforcementactions: WebMappingRetrieve<ts_enforcementaction_Select,ts_enforcementaction_Expand,ts_enforcementaction_Filter,ts_enforcementaction_Fixed,ts_enforcementaction_Result,ts_enforcementaction_FormattedResult>;
  ts_Contact_msdyn_workorder_msdyn_workorder: WebMappingRetrieve<Contact_Select,Contact_Expand,Contact_Filter,Contact_Fixed,Contact_Result,Contact_FormattedResult>;
  ts_incident_WorkOrder1_msdyn_workorder: WebMappingRetrieve<Incident_Select,Incident_Expand,Incident_Filter,Incident_Fixed,Incident_Result,Incident_FormattedResult>;
  ts_incident_WorkOrder2_msdyn_workorder: WebMappingRetrieve<Incident_Select,Incident_Expand,Incident_Filter,Incident_Fixed,Incident_Result,Incident_FormattedResult>;
  ts_msdyn_customerasset_msdyn_workorder_msdyn: WebMappingRetrieve<msdyn_customerasset_Select,msdyn_customerasset_Expand,msdyn_customerasset_Filter,msdyn_customerasset_Fixed,msdyn_customerasset_Result,msdyn_customerasset_FormattedResult>;
  ts_msdyn_workorder_msdyn_workorder_Account: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  ts_msdyn_workorder_ovs_operation_ovs_operati: WebMappingRetrieve<ovs_operation_Select,ovs_operation_Expand,ovs_operation_Filter,ovs_operation_Fixed,ovs_operation_Result,ovs_operation_FormattedResult>;
  ts_msdyn_workorder_ts_operationcontact: WebMappingRetrieve<ts_operationcontact_Select,ts_operationcontact_Expand,ts_operationcontact_Filter,ts_operationcontact_Fixed,ts_operationcontact_Result,ts_operationcontact_FormattedResult>;
  ts_operationcontact_workorder_msdyn_worko: WebMappingRetrieve<ts_operationcontact_Select,ts_operationcontact_Expand,ts_operationcontact_Filter,ts_operationcontact_Fixed,ts_operationcontact_Result,ts_operationcontact_FormattedResult>;
  ts_ovs_Finding_WorkOrder_msdyn_workorder: WebMappingRetrieve<ovs_Finding_Select,ovs_Finding_Expand,ovs_Finding_Filter,ovs_Finding_Fixed,ovs_Finding_Result,ovs_Finding_FormattedResult>;
}
interface WebEntitiesRetrieve {
  msdyn_workorders: WebMappingRetrieve<msdyn_workorder_Select,msdyn_workorder_Expand,msdyn_workorder_Filter,msdyn_workorder_Fixed,msdyn_workorder_Result,msdyn_workorder_FormattedResult>;
}
interface WebEntitiesRelated {
  msdyn_workorders: WebMappingRelated<msdyn_workorder_RelatedOne,msdyn_workorder_RelatedMany>;
}
interface WebEntitiesCUDA {
  msdyn_workorders: WebMappingCUDA<msdyn_workorder_Create,msdyn_workorder_Update,msdyn_workorder_Select>;
}
