interface msdyn_incidenttype_Base extends WebEntity {
  createdon?: Date | null;
  importsequencenumber?: number | null;
  modifiedon?: Date | null;
  msdyn_copyincidentitemstoagreement?: boolean | null;
  msdyn_description?: string | null;
  msdyn_estimatedduration?: number | null;
  msdyn_incidenttypeid?: string | null;
  msdyn_lastcalculatedtime?: Date | null;
  msdyn_name?: string | null;
  msdyn_resolutionrequiredonwocompletion?: boolean | null;
  msdyn_suggestedduration?: number | null;
  overriddencreatedon?: Date | null;
  ovs_incidenttypenameenglish?: string | null;
  ovs_incidenttypenamefrench?: string | null;
  statecode?: msdyn_incidenttype_statecode | null;
  statuscode?: msdyn_incidenttype_statuscode | null;
  timezoneruleversionnumber?: number | null;
  ts_aircargo?: boolean | null;
  ts_aviationsecuritytraining?: boolean | null;
  ts_cateringandstores?: boolean | null;
  ts_conductingoversight?: number | null;
  ts_domestic?: boolean | null;
  ts_domesticflights?: boolean | null;
  ts_estimateddurationinhours?: number | null;
  ts_excludefromplanning?: boolean | null;
  ts_includeinplanning?: boolean | null;
  ts_international?: boolean | null;
  ts_internationalflights?: boolean | null;
  ts_internationalprogramsbranchipb?: boolean | null;
  ts_mail?: boolean | null;
  ts_onestopsecurityoss?: boolean | null;
  ts_opi?: boolean | null;
  ts_preparationtime?: number | null;
  ts_remainovernightron?: boolean | null;
  ts_reportinganddocumentation?: number | null;
  ts_reportingcategory?: ts_reportingcategory | null;
  ts_transborderflights?: boolean | null;
  ts_unattendedaircraft?: boolean | null;
  ts_vaccesscontrolsecurityservices?: boolean | null;
  ts_vactualtime?: boolean | null;
  ts_vaocoperation?: boolean | null;
  ts_vaocoperationtype?: boolean | null;
  ts_vaocsite?: boolean | null;
  ts_vaocstakeholder?: boolean | null;
  ts_vbrandname?: boolean | null;
  ts_vcargoservices?: boolean | null;
  ts_vcateringservices?: boolean | null;
  ts_vcbcheckedin?: boolean | null;
  ts_vcbloaded?: boolean | null;
  ts_vdestination?: boolean | null;
  ts_vflightcategory?: boolean | null;
  ts_vflightnumber?: boolean | null;
  ts_vflighttype?: boolean | null;
  ts_vgroomingservices?: boolean | null;
  ts_vlocation?: boolean | null;
  ts_vmanufacturer?: boolean | null;
  ts_vmodel?: boolean | null;
  ts_vorigin?: boolean | null;
  ts_vothersecurityservices?: boolean | null;
  ts_vpassengerservices?: boolean | null;
  ts_vpaxboarded?: boolean | null;
  ts_vpaxcheckedin?: boolean | null;
  ts_vrampservices?: boolean | null;
  ts_vregistration?: boolean | null;
  ts_vreportdetails?: boolean | null;
  ts_vscheduledtime?: boolean | null;
  ts_vsecuritysearchservices?: boolean | null;
  utcconversiontimezonecode?: number | null;
  versionnumber?: number | null;
}
interface msdyn_incidenttype_Relationships {
  msdyn_incidenttype_connections1?: Connection_Result[] | null;
  msdyn_incidenttype_connections2?: Connection_Result[] | null;
  msdyn_msdyn_incidenttype_incident_IncidentType?: Incident_Result[] | null;
  msdyn_msdyn_incidenttype_msdyn_incidenttypeservicetask_IncidentType?: msdyn_incidenttypeservicetask_Result[] | null;
  msdyn_msdyn_incidenttype_msdyn_workorder_PrimaryIncidentType?: msdyn_workorder_Result[] | null;
  ts_EntityRisk_msdyn_incidenttype_msdyn_incidenttype?: ts_EntityRisk_Result[] | null;
  ts_entityriskfrequency_ActivityType_msdyn_incidenttype?: ts_EntityRiskFrequency_Result[] | null;
  ts_incident_InspectionType1_msdyn_incidentty?: Incident_Result[] | null;
  ts_incident_InspectionType2_msdyn_incidentty?: Incident_Result[] | null;
  ts_ovs_operationtypes_msdyn_incidenttypes?: ovs_operationtype_Result[] | null;
  ts_questionnaireresponse_ActivityType_msdyn_incidenttype?: ts_questionnaireresponse_Result[] | null;
  ts_suggestedinspection_activitytype?: ts_SuggestedInspection_Result[] | null;
  ts_ts_case_InspectionType1_msdyn_incidentty?: ts_case_Result[] | null;
  ts_ts_case_InspectionType2_msdyn_incidentty?: ts_case_Result[] | null;
  ts_ts_operationactivity_Activity_msdyn_incid?: ts_OperationActivity_Result[] | null;
  ts_ts_planningdata_ActivityType_msdyn_incide?: ts_PlanningData_Result[] | null;
}
interface msdyn_incidenttype extends msdyn_incidenttype_Base, msdyn_incidenttype_Relationships {
  msdyn_Trade_bind$msdyn_trades?: string | null;
  msdyn_defaultworkordertype_bind$msdyn_workordertypes?: string | null;
  ownerid_bind$systemusers?: string | null;
  ownerid_bind$teams?: string | null;
  ts_ProgramActivityRiskRating_bind$ts_riskratings?: string | null;
  ts_ProgramArea_bind$ts_programareas?: string | null;
  ts_RiskScore_bind$ts_recurrencefrequencieses?: string | null;
  ts_ovs_operation_bind$ovs_operations?: string | null;
}
interface msdyn_incidenttype_Create extends msdyn_incidenttype {
}
interface msdyn_incidenttype_Update extends msdyn_incidenttype {
}
interface msdyn_incidenttype_Select {
  createdby_guid: WebAttribute<msdyn_incidenttype_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
  createdon: WebAttribute<msdyn_incidenttype_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
  createdonbehalfby_guid: WebAttribute<msdyn_incidenttype_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
  importsequencenumber: WebAttribute<msdyn_incidenttype_Select, { importsequencenumber: number | null }, {  }>;
  modifiedby_guid: WebAttribute<msdyn_incidenttype_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
  modifiedon: WebAttribute<msdyn_incidenttype_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
  modifiedonbehalfby_guid: WebAttribute<msdyn_incidenttype_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
  msdyn_copyincidentitemstoagreement: WebAttribute<msdyn_incidenttype_Select, { msdyn_copyincidentitemstoagreement: boolean | null }, {  }>;
  msdyn_defaultworkordertype_guid: WebAttribute<msdyn_incidenttype_Select, { msdyn_defaultworkordertype_guid: string | null }, { msdyn_defaultworkordertype_formatted?: string }>;
  msdyn_description: WebAttribute<msdyn_incidenttype_Select, { msdyn_description: string | null }, {  }>;
  msdyn_estimatedduration: WebAttribute<msdyn_incidenttype_Select, { msdyn_estimatedduration: number | null }, {  }>;
  msdyn_incidenttypeid: WebAttribute<msdyn_incidenttype_Select, { msdyn_incidenttypeid: string | null }, {  }>;
  msdyn_lastcalculatedtime: WebAttribute<msdyn_incidenttype_Select, { msdyn_lastcalculatedtime: Date | null }, { msdyn_lastcalculatedtime_formatted?: string }>;
  msdyn_name: WebAttribute<msdyn_incidenttype_Select, { msdyn_name: string | null }, {  }>;
  msdyn_resolutionrequiredonwocompletion: WebAttribute<msdyn_incidenttype_Select, { msdyn_resolutionrequiredonwocompletion: boolean | null }, {  }>;
  msdyn_suggestedduration: WebAttribute<msdyn_incidenttype_Select, { msdyn_suggestedduration: number | null }, {  }>;
  msdyn_trade_guid: WebAttribute<msdyn_incidenttype_Select, { msdyn_trade_guid: string | null }, { msdyn_trade_formatted?: string }>;
  overriddencreatedon: WebAttribute<msdyn_incidenttype_Select, { overriddencreatedon: Date | null }, { overriddencreatedon_formatted?: string }>;
  ovs_incidenttypenameenglish: WebAttribute<msdyn_incidenttype_Select, { ovs_incidenttypenameenglish: string | null }, {  }>;
  ovs_incidenttypenamefrench: WebAttribute<msdyn_incidenttype_Select, { ovs_incidenttypenamefrench: string | null }, {  }>;
  ownerid_guid: WebAttribute<msdyn_incidenttype_Select, { ownerid_guid: string | null }, { ownerid_formatted?: string }>;
  owningbusinessunit_guid: WebAttribute<msdyn_incidenttype_Select, { owningbusinessunit_guid: string | null }, { owningbusinessunit_formatted?: string }>;
  owningteam_guid: WebAttribute<msdyn_incidenttype_Select, { owningteam_guid: string | null }, { owningteam_formatted?: string }>;
  owninguser_guid: WebAttribute<msdyn_incidenttype_Select, { owninguser_guid: string | null }, { owninguser_formatted?: string }>;
  statecode: WebAttribute<msdyn_incidenttype_Select, { statecode: msdyn_incidenttype_statecode | null }, { statecode_formatted?: string }>;
  statuscode: WebAttribute<msdyn_incidenttype_Select, { statuscode: msdyn_incidenttype_statuscode | null }, { statuscode_formatted?: string }>;
  timezoneruleversionnumber: WebAttribute<msdyn_incidenttype_Select, { timezoneruleversionnumber: number | null }, {  }>;
  ts_aircargo: WebAttribute<msdyn_incidenttype_Select, { ts_aircargo: boolean | null }, {  }>;
  ts_aviationsecuritytraining: WebAttribute<msdyn_incidenttype_Select, { ts_aviationsecuritytraining: boolean | null }, {  }>;
  ts_cateringandstores: WebAttribute<msdyn_incidenttype_Select, { ts_cateringandstores: boolean | null }, {  }>;
  ts_conductingoversight: WebAttribute<msdyn_incidenttype_Select, { ts_conductingoversight: number | null }, {  }>;
  ts_domestic: WebAttribute<msdyn_incidenttype_Select, { ts_domestic: boolean | null }, {  }>;
  ts_domesticflights: WebAttribute<msdyn_incidenttype_Select, { ts_domesticflights: boolean | null }, {  }>;
  ts_estimateddurationinhours: WebAttribute<msdyn_incidenttype_Select, { ts_estimateddurationinhours: number | null }, {  }>;
  ts_excludefromplanning: WebAttribute<msdyn_incidenttype_Select, { ts_excludefromplanning: boolean | null }, {  }>;
  ts_includeinplanning: WebAttribute<msdyn_incidenttype_Select, { ts_includeinplanning: boolean | null }, {  }>;
  ts_international: WebAttribute<msdyn_incidenttype_Select, { ts_international: boolean | null }, {  }>;
  ts_internationalflights: WebAttribute<msdyn_incidenttype_Select, { ts_internationalflights: boolean | null }, {  }>;
  ts_internationalprogramsbranchipb: WebAttribute<msdyn_incidenttype_Select, { ts_internationalprogramsbranchipb: boolean | null }, {  }>;
  ts_mail: WebAttribute<msdyn_incidenttype_Select, { ts_mail: boolean | null }, {  }>;
  ts_onestopsecurityoss: WebAttribute<msdyn_incidenttype_Select, { ts_onestopsecurityoss: boolean | null }, {  }>;
  ts_opi: WebAttribute<msdyn_incidenttype_Select, { ts_opi: boolean | null }, {  }>;
  ts_ovs_operation_guid: WebAttribute<msdyn_incidenttype_Select, { ts_ovs_operation_guid: string | null }, { ts_ovs_operation_formatted?: string }>;
  ts_preparationtime: WebAttribute<msdyn_incidenttype_Select, { ts_preparationtime: number | null }, {  }>;
  ts_programactivityriskrating_guid: WebAttribute<msdyn_incidenttype_Select, { ts_programactivityriskrating_guid: string | null }, { ts_programactivityriskrating_formatted?: string }>;
  ts_programarea_guid: WebAttribute<msdyn_incidenttype_Select, { ts_programarea_guid: string | null }, { ts_programarea_formatted?: string }>;
  ts_remainovernightron: WebAttribute<msdyn_incidenttype_Select, { ts_remainovernightron: boolean | null }, {  }>;
  ts_reportinganddocumentation: WebAttribute<msdyn_incidenttype_Select, { ts_reportinganddocumentation: number | null }, {  }>;
  ts_reportingcategory: WebAttribute<msdyn_incidenttype_Select, { ts_reportingcategory: ts_reportingcategory | null }, { ts_reportingcategory_formatted?: string }>;
  ts_riskscore_guid: WebAttribute<msdyn_incidenttype_Select, { ts_riskscore_guid: string | null }, { ts_riskscore_formatted?: string }>;
  ts_transborderflights: WebAttribute<msdyn_incidenttype_Select, { ts_transborderflights: boolean | null }, {  }>;
  ts_unattendedaircraft: WebAttribute<msdyn_incidenttype_Select, { ts_unattendedaircraft: boolean | null }, {  }>;
  ts_vaccesscontrolsecurityservices: WebAttribute<msdyn_incidenttype_Select, { ts_vaccesscontrolsecurityservices: boolean | null }, {  }>;
  ts_vactualtime: WebAttribute<msdyn_incidenttype_Select, { ts_vactualtime: boolean | null }, {  }>;
  ts_vaocoperation: WebAttribute<msdyn_incidenttype_Select, { ts_vaocoperation: boolean | null }, {  }>;
  ts_vaocoperationtype: WebAttribute<msdyn_incidenttype_Select, { ts_vaocoperationtype: boolean | null }, {  }>;
  ts_vaocsite: WebAttribute<msdyn_incidenttype_Select, { ts_vaocsite: boolean | null }, {  }>;
  ts_vaocstakeholder: WebAttribute<msdyn_incidenttype_Select, { ts_vaocstakeholder: boolean | null }, {  }>;
  ts_vbrandname: WebAttribute<msdyn_incidenttype_Select, { ts_vbrandname: boolean | null }, {  }>;
  ts_vcargoservices: WebAttribute<msdyn_incidenttype_Select, { ts_vcargoservices: boolean | null }, {  }>;
  ts_vcateringservices: WebAttribute<msdyn_incidenttype_Select, { ts_vcateringservices: boolean | null }, {  }>;
  ts_vcbcheckedin: WebAttribute<msdyn_incidenttype_Select, { ts_vcbcheckedin: boolean | null }, {  }>;
  ts_vcbloaded: WebAttribute<msdyn_incidenttype_Select, { ts_vcbloaded: boolean | null }, {  }>;
  ts_vdestination: WebAttribute<msdyn_incidenttype_Select, { ts_vdestination: boolean | null }, {  }>;
  ts_vflightcategory: WebAttribute<msdyn_incidenttype_Select, { ts_vflightcategory: boolean | null }, {  }>;
  ts_vflightnumber: WebAttribute<msdyn_incidenttype_Select, { ts_vflightnumber: boolean | null }, {  }>;
  ts_vflighttype: WebAttribute<msdyn_incidenttype_Select, { ts_vflighttype: boolean | null }, {  }>;
  ts_vgroomingservices: WebAttribute<msdyn_incidenttype_Select, { ts_vgroomingservices: boolean | null }, {  }>;
  ts_vlocation: WebAttribute<msdyn_incidenttype_Select, { ts_vlocation: boolean | null }, {  }>;
  ts_vmanufacturer: WebAttribute<msdyn_incidenttype_Select, { ts_vmanufacturer: boolean | null }, {  }>;
  ts_vmodel: WebAttribute<msdyn_incidenttype_Select, { ts_vmodel: boolean | null }, {  }>;
  ts_vorigin: WebAttribute<msdyn_incidenttype_Select, { ts_vorigin: boolean | null }, {  }>;
  ts_vothersecurityservices: WebAttribute<msdyn_incidenttype_Select, { ts_vothersecurityservices: boolean | null }, {  }>;
  ts_vpassengerservices: WebAttribute<msdyn_incidenttype_Select, { ts_vpassengerservices: boolean | null }, {  }>;
  ts_vpaxboarded: WebAttribute<msdyn_incidenttype_Select, { ts_vpaxboarded: boolean | null }, {  }>;
  ts_vpaxcheckedin: WebAttribute<msdyn_incidenttype_Select, { ts_vpaxcheckedin: boolean | null }, {  }>;
  ts_vrampservices: WebAttribute<msdyn_incidenttype_Select, { ts_vrampservices: boolean | null }, {  }>;
  ts_vregistration: WebAttribute<msdyn_incidenttype_Select, { ts_vregistration: boolean | null }, {  }>;
  ts_vreportdetails: WebAttribute<msdyn_incidenttype_Select, { ts_vreportdetails: boolean | null }, {  }>;
  ts_vscheduledtime: WebAttribute<msdyn_incidenttype_Select, { ts_vscheduledtime: boolean | null }, {  }>;
  ts_vsecuritysearchservices: WebAttribute<msdyn_incidenttype_Select, { ts_vsecuritysearchservices: boolean | null }, {  }>;
  utcconversiontimezonecode: WebAttribute<msdyn_incidenttype_Select, { utcconversiontimezonecode: number | null }, {  }>;
  versionnumber: WebAttribute<msdyn_incidenttype_Select, { versionnumber: number | null }, {  }>;
}
interface msdyn_incidenttype_Filter {
  createdby_guid: XQW.Guid;
  createdon: Date;
  createdonbehalfby_guid: XQW.Guid;
  importsequencenumber: number;
  modifiedby_guid: XQW.Guid;
  modifiedon: Date;
  modifiedonbehalfby_guid: XQW.Guid;
  msdyn_copyincidentitemstoagreement: boolean;
  msdyn_defaultworkordertype_guid: XQW.Guid;
  msdyn_description: string;
  msdyn_estimatedduration: number;
  msdyn_incidenttypeid: XQW.Guid;
  msdyn_lastcalculatedtime: Date;
  msdyn_name: string;
  msdyn_resolutionrequiredonwocompletion: boolean;
  msdyn_suggestedduration: number;
  msdyn_trade_guid: XQW.Guid;
  overriddencreatedon: Date;
  ovs_incidenttypenameenglish: string;
  ovs_incidenttypenamefrench: string;
  ownerid_guid: XQW.Guid;
  owningbusinessunit_guid: XQW.Guid;
  owningteam_guid: XQW.Guid;
  owninguser_guid: XQW.Guid;
  statecode: msdyn_incidenttype_statecode;
  statuscode: msdyn_incidenttype_statuscode;
  timezoneruleversionnumber: number;
  ts_aircargo: boolean;
  ts_aviationsecuritytraining: boolean;
  ts_cateringandstores: boolean;
  ts_conductingoversight: any;
  ts_domestic: boolean;
  ts_domesticflights: boolean;
  ts_estimateddurationinhours: any;
  ts_excludefromplanning: boolean;
  ts_includeinplanning: boolean;
  ts_international: boolean;
  ts_internationalflights: boolean;
  ts_internationalprogramsbranchipb: boolean;
  ts_mail: boolean;
  ts_onestopsecurityoss: boolean;
  ts_opi: boolean;
  ts_ovs_operation_guid: XQW.Guid;
  ts_preparationtime: any;
  ts_programactivityriskrating_guid: XQW.Guid;
  ts_programarea_guid: XQW.Guid;
  ts_remainovernightron: boolean;
  ts_reportinganddocumentation: any;
  ts_reportingcategory: ts_reportingcategory;
  ts_riskscore_guid: XQW.Guid;
  ts_transborderflights: boolean;
  ts_unattendedaircraft: boolean;
  ts_vaccesscontrolsecurityservices: boolean;
  ts_vactualtime: boolean;
  ts_vaocoperation: boolean;
  ts_vaocoperationtype: boolean;
  ts_vaocsite: boolean;
  ts_vaocstakeholder: boolean;
  ts_vbrandname: boolean;
  ts_vcargoservices: boolean;
  ts_vcateringservices: boolean;
  ts_vcbcheckedin: boolean;
  ts_vcbloaded: boolean;
  ts_vdestination: boolean;
  ts_vflightcategory: boolean;
  ts_vflightnumber: boolean;
  ts_vflighttype: boolean;
  ts_vgroomingservices: boolean;
  ts_vlocation: boolean;
  ts_vmanufacturer: boolean;
  ts_vmodel: boolean;
  ts_vorigin: boolean;
  ts_vothersecurityservices: boolean;
  ts_vpassengerservices: boolean;
  ts_vpaxboarded: boolean;
  ts_vpaxcheckedin: boolean;
  ts_vrampservices: boolean;
  ts_vregistration: boolean;
  ts_vreportdetails: boolean;
  ts_vscheduledtime: boolean;
  ts_vsecuritysearchservices: boolean;
  utcconversiontimezonecode: number;
  versionnumber: number;
}
interface msdyn_incidenttype_Expand {
  createdby: WebExpand<msdyn_incidenttype_Expand, SystemUser_Select, SystemUser_Filter, { createdby: SystemUser_Result }>;
  createdonbehalfby: WebExpand<msdyn_incidenttype_Expand, SystemUser_Select, SystemUser_Filter, { createdonbehalfby: SystemUser_Result }>;
  modifiedby: WebExpand<msdyn_incidenttype_Expand, SystemUser_Select, SystemUser_Filter, { modifiedby: SystemUser_Result }>;
  modifiedonbehalfby: WebExpand<msdyn_incidenttype_Expand, SystemUser_Select, SystemUser_Filter, { modifiedonbehalfby: SystemUser_Result }>;
  msdyn_incidenttype_connections1: WebExpand<msdyn_incidenttype_Expand, Connection_Select, Connection_Filter, { msdyn_incidenttype_connections1: Connection_Result[] }>;
  msdyn_incidenttype_connections2: WebExpand<msdyn_incidenttype_Expand, Connection_Select, Connection_Filter, { msdyn_incidenttype_connections2: Connection_Result[] }>;
  msdyn_msdyn_incidenttype_incident_IncidentType: WebExpand<msdyn_incidenttype_Expand, Incident_Select, Incident_Filter, { msdyn_msdyn_incidenttype_incident_IncidentType: Incident_Result[] }>;
  msdyn_msdyn_incidenttype_msdyn_incidenttypeservicetask_IncidentType: WebExpand<msdyn_incidenttype_Expand, msdyn_incidenttypeservicetask_Select, msdyn_incidenttypeservicetask_Filter, { msdyn_msdyn_incidenttype_msdyn_incidenttypeservicetask_IncidentType: msdyn_incidenttypeservicetask_Result[] }>;
  msdyn_msdyn_incidenttype_msdyn_workorder_PrimaryIncidentType: WebExpand<msdyn_incidenttype_Expand, msdyn_workorder_Select, msdyn_workorder_Filter, { msdyn_msdyn_incidenttype_msdyn_workorder_PrimaryIncidentType: msdyn_workorder_Result[] }>;
  ownerid: WebExpand<msdyn_incidenttype_Expand, SystemUser_Select & Team_Select, SystemUser_Filter & Team_Filter, { ownerid: SystemUser_Result } & { ownerid: Team_Result }>;
  owningteam: WebExpand<msdyn_incidenttype_Expand, Team_Select, Team_Filter, { owningteam: Team_Result }>;
  owninguser: WebExpand<msdyn_incidenttype_Expand, SystemUser_Select, SystemUser_Filter, { owninguser: SystemUser_Result }>;
  ts_EntityRisk_msdyn_incidenttype_msdyn_incidenttype: WebExpand<msdyn_incidenttype_Expand, ts_EntityRisk_Select, ts_EntityRisk_Filter, { ts_EntityRisk_msdyn_incidenttype_msdyn_incidenttype: ts_EntityRisk_Result[] }>;
  ts_entityriskfrequency_ActivityType_msdyn_incidenttype: WebExpand<msdyn_incidenttype_Expand, ts_EntityRiskFrequency_Select, ts_EntityRiskFrequency_Filter, { ts_entityriskfrequency_ActivityType_msdyn_incidenttype: ts_EntityRiskFrequency_Result[] }>;
  ts_incident_InspectionType1_msdyn_incidentty: WebExpand<msdyn_incidenttype_Expand, Incident_Select, Incident_Filter, { ts_incident_InspectionType1_msdyn_incidentty: Incident_Result[] }>;
  ts_incident_InspectionType2_msdyn_incidentty: WebExpand<msdyn_incidenttype_Expand, Incident_Select, Incident_Filter, { ts_incident_InspectionType2_msdyn_incidentty: Incident_Result[] }>;
  ts_ovs_operation: WebExpand<msdyn_incidenttype_Expand, ovs_operation_Select, ovs_operation_Filter, { ts_ovs_operation: ovs_operation_Result }>;
  ts_ovs_operationtypes_msdyn_incidenttypes: WebExpand<msdyn_incidenttype_Expand, ovs_operationtype_Select, ovs_operationtype_Filter, { ts_ovs_operationtypes_msdyn_incidenttypes: ovs_operationtype_Result[] }>;
  ts_questionnaireresponse_ActivityType_msdyn_incidenttype: WebExpand<msdyn_incidenttype_Expand, ts_questionnaireresponse_Select, ts_questionnaireresponse_Filter, { ts_questionnaireresponse_ActivityType_msdyn_incidenttype: ts_questionnaireresponse_Result[] }>;
  ts_suggestedinspection_activitytype: WebExpand<msdyn_incidenttype_Expand, ts_SuggestedInspection_Select, ts_SuggestedInspection_Filter, { ts_suggestedinspection_activitytype: ts_SuggestedInspection_Result[] }>;
  ts_ts_case_InspectionType1_msdyn_incidentty: WebExpand<msdyn_incidenttype_Expand, ts_case_Select, ts_case_Filter, { ts_ts_case_InspectionType1_msdyn_incidentty: ts_case_Result[] }>;
  ts_ts_case_InspectionType2_msdyn_incidentty: WebExpand<msdyn_incidenttype_Expand, ts_case_Select, ts_case_Filter, { ts_ts_case_InspectionType2_msdyn_incidentty: ts_case_Result[] }>;
  ts_ts_operationactivity_Activity_msdyn_incid: WebExpand<msdyn_incidenttype_Expand, ts_OperationActivity_Select, ts_OperationActivity_Filter, { ts_ts_operationactivity_Activity_msdyn_incid: ts_OperationActivity_Result[] }>;
  ts_ts_planningdata_ActivityType_msdyn_incide: WebExpand<msdyn_incidenttype_Expand, ts_PlanningData_Select, ts_PlanningData_Filter, { ts_ts_planningdata_ActivityType_msdyn_incide: ts_PlanningData_Result[] }>;
}
interface msdyn_incidenttype_FormattedResult {
  createdby_formatted?: string;
  createdon_formatted?: string;
  createdonbehalfby_formatted?: string;
  modifiedby_formatted?: string;
  modifiedon_formatted?: string;
  modifiedonbehalfby_formatted?: string;
  msdyn_defaultworkordertype_formatted?: string;
  msdyn_lastcalculatedtime_formatted?: string;
  msdyn_trade_formatted?: string;
  overriddencreatedon_formatted?: string;
  ownerid_formatted?: string;
  owningbusinessunit_formatted?: string;
  owningteam_formatted?: string;
  owninguser_formatted?: string;
  statecode_formatted?: string;
  statuscode_formatted?: string;
  ts_ovs_operation_formatted?: string;
  ts_programactivityriskrating_formatted?: string;
  ts_programarea_formatted?: string;
  ts_reportingcategory_formatted?: string;
  ts_riskscore_formatted?: string;
}
interface msdyn_incidenttype_Result extends msdyn_incidenttype_Base, msdyn_incidenttype_Relationships {
  "@odata.etag": string;
  createdby_guid: string | null;
  createdonbehalfby_guid: string | null;
  modifiedby_guid: string | null;
  modifiedonbehalfby_guid: string | null;
  msdyn_defaultworkordertype_guid: string | null;
  msdyn_trade_guid: string | null;
  ownerid_guid: string | null;
  owningbusinessunit_guid: string | null;
  owningteam_guid: string | null;
  owninguser_guid: string | null;
  ts_ovs_operation_guid: string | null;
  ts_programactivityriskrating_guid: string | null;
  ts_programarea_guid: string | null;
  ts_riskscore_guid: string | null;
}
interface msdyn_incidenttype_RelatedOne {
  createdby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  createdonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  ownerid: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult> & WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owningteam: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owninguser: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  ts_ovs_operation: WebMappingRetrieve<ovs_operation_Select,ovs_operation_Expand,ovs_operation_Filter,ovs_operation_Fixed,ovs_operation_Result,ovs_operation_FormattedResult>;
}
interface msdyn_incidenttype_RelatedMany {
  msdyn_incidenttype_connections1: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  msdyn_incidenttype_connections2: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  msdyn_msdyn_incidenttype_incident_IncidentType: WebMappingRetrieve<Incident_Select,Incident_Expand,Incident_Filter,Incident_Fixed,Incident_Result,Incident_FormattedResult>;
  msdyn_msdyn_incidenttype_msdyn_incidenttypeservicetask_IncidentType: WebMappingRetrieve<msdyn_incidenttypeservicetask_Select,msdyn_incidenttypeservicetask_Expand,msdyn_incidenttypeservicetask_Filter,msdyn_incidenttypeservicetask_Fixed,msdyn_incidenttypeservicetask_Result,msdyn_incidenttypeservicetask_FormattedResult>;
  msdyn_msdyn_incidenttype_msdyn_workorder_PrimaryIncidentType: WebMappingRetrieve<msdyn_workorder_Select,msdyn_workorder_Expand,msdyn_workorder_Filter,msdyn_workorder_Fixed,msdyn_workorder_Result,msdyn_workorder_FormattedResult>;
  ts_EntityRisk_msdyn_incidenttype_msdyn_incidenttype: WebMappingRetrieve<ts_EntityRisk_Select,ts_EntityRisk_Expand,ts_EntityRisk_Filter,ts_EntityRisk_Fixed,ts_EntityRisk_Result,ts_EntityRisk_FormattedResult>;
  ts_entityriskfrequency_ActivityType_msdyn_incidenttype: WebMappingRetrieve<ts_EntityRiskFrequency_Select,ts_EntityRiskFrequency_Expand,ts_EntityRiskFrequency_Filter,ts_EntityRiskFrequency_Fixed,ts_EntityRiskFrequency_Result,ts_EntityRiskFrequency_FormattedResult>;
  ts_incident_InspectionType1_msdyn_incidentty: WebMappingRetrieve<Incident_Select,Incident_Expand,Incident_Filter,Incident_Fixed,Incident_Result,Incident_FormattedResult>;
  ts_incident_InspectionType2_msdyn_incidentty: WebMappingRetrieve<Incident_Select,Incident_Expand,Incident_Filter,Incident_Fixed,Incident_Result,Incident_FormattedResult>;
  ts_ovs_operationtypes_msdyn_incidenttypes: WebMappingRetrieve<ovs_operationtype_Select,ovs_operationtype_Expand,ovs_operationtype_Filter,ovs_operationtype_Fixed,ovs_operationtype_Result,ovs_operationtype_FormattedResult>;
  ts_questionnaireresponse_ActivityType_msdyn_incidenttype: WebMappingRetrieve<ts_questionnaireresponse_Select,ts_questionnaireresponse_Expand,ts_questionnaireresponse_Filter,ts_questionnaireresponse_Fixed,ts_questionnaireresponse_Result,ts_questionnaireresponse_FormattedResult>;
  ts_suggestedinspection_activitytype: WebMappingRetrieve<ts_SuggestedInspection_Select,ts_SuggestedInspection_Expand,ts_SuggestedInspection_Filter,ts_SuggestedInspection_Fixed,ts_SuggestedInspection_Result,ts_SuggestedInspection_FormattedResult>;
  ts_ts_case_InspectionType1_msdyn_incidentty: WebMappingRetrieve<ts_case_Select,ts_case_Expand,ts_case_Filter,ts_case_Fixed,ts_case_Result,ts_case_FormattedResult>;
  ts_ts_case_InspectionType2_msdyn_incidentty: WebMappingRetrieve<ts_case_Select,ts_case_Expand,ts_case_Filter,ts_case_Fixed,ts_case_Result,ts_case_FormattedResult>;
  ts_ts_operationactivity_Activity_msdyn_incid: WebMappingRetrieve<ts_OperationActivity_Select,ts_OperationActivity_Expand,ts_OperationActivity_Filter,ts_OperationActivity_Fixed,ts_OperationActivity_Result,ts_OperationActivity_FormattedResult>;
  ts_ts_planningdata_ActivityType_msdyn_incide: WebMappingRetrieve<ts_PlanningData_Select,ts_PlanningData_Expand,ts_PlanningData_Filter,ts_PlanningData_Fixed,ts_PlanningData_Result,ts_PlanningData_FormattedResult>;
}
interface WebEntitiesRetrieve {
  msdyn_incidenttypes: WebMappingRetrieve<msdyn_incidenttype_Select,msdyn_incidenttype_Expand,msdyn_incidenttype_Filter,msdyn_incidenttype_Fixed,msdyn_incidenttype_Result,msdyn_incidenttype_FormattedResult>;
}
interface WebEntitiesRelated {
  msdyn_incidenttypes: WebMappingRelated<msdyn_incidenttype_RelatedOne,msdyn_incidenttype_RelatedMany>;
}
interface WebEntitiesCUDA {
  msdyn_incidenttypes: WebMappingCUDA<msdyn_incidenttype_Create,msdyn_incidenttype_Update,msdyn_incidenttype_Select>;
}
