interface msdyn_workorderservicetask_Base extends WebEntity {
  createdon?: Date | null;
  importsequencenumber?: number | null;
  modifiedon?: Date | null;
  msdyn_actualduration?: number | null;
  msdyn_description?: string | null;
  msdyn_estimatedduration?: number | null;
  msdyn_inspectionenabled?: boolean | null;
  msdyn_inspectionresult?: msdyn_msdyn_workorderservicetask_msdyn_inspectionresult | null;
  msdyn_inspectiontaskresult?: msdyn_inspectionresult | null;
  msdyn_internalflags?: string | null;
  msdyn_lineorder?: number | null;
  msdyn_name?: string | null;
  msdyn_percentcomplete?: number | null;
  msdyn_surveyboundedoutput?: string | null;
  msdyn_workorderservicetaskid?: string | null;
  overriddencreatedon?: Date | null;
  ovs_isquestionnairecomplete?: boolean | null;
  ovs_questionnairedefinition?: string | null;
  ovs_questionnaireresponse?: string | null;
  ovs_questionnaireresultjson?: string | null;
  qm_blobpath?: string | null;
  qm_isquestionnaireupdated?: boolean | null;
  statecode?: msdyn_workorderservicetask_statecode | null;
  statuscode?: msdyn_workorderservicetask_statuscode | null;
  timezoneruleversionnumber?: number | null;
  ts_accesscontrol?: boolean | null;
  ts_actualtime?: Date | null;
  ts_aircraftmanufacturer?: ts_aircraftmanufacturer | null;
  ts_aircraftmark?: string | null;
  ts_aircraftmodel?: ts_aircraftmodel | null;
  ts_aircraftmodelother?: string | null;
  ts_brandname?: ts_aircarrierbrandname | null;
  ts_cbloaded?: string | null;
  ts_cbonboard?: string | null;
  ts_documenteddate?: Date | null;
  ts_flightcategory?: ts_flightcategory | null;
  ts_flightnumber?: string | null;
  ts_flighttype?: ts_flighttype | null;
  ts_location?: string | null;
  ts_mandatory?: boolean | null;
  ts_paxboarded?: string | null;
  ts_paxonboard?: string | null;
  ts_reportdetails?: string | null;
  ts_scheduledtime?: Date | null;
  ts_servicetaskenddate?: Date | null;
  ts_servicetaskstartdate?: Date | null;
  ts_workorderstartdate?: Date | null;
  utcconversiontimezonecode?: number | null;
  versionnumber?: number | null;
}
interface msdyn_workorderservicetask_Relationships {
  msdyn_workorderservicetask_Appointments?: Appointment_Result[] | null;
  msdyn_workorderservicetask_Emails?: Email_Result[] | null;
  msdyn_workorderservicetask_ServiceAppointments?: ServiceAppointment_Result[] | null;
  msdyn_workorderservicetask_connections1?: Connection_Result[] | null;
  msdyn_workorderservicetask_connections2?: Connection_Result[] | null;
  msdyn_workorderservicetask_ts_enforcementactions?: ts_enforcementaction_Result[] | null;
  ovs_CaseId?: Incident_Result | null;
  ovs_Questionnaire?: ovs_Questionnaire_Result | null;
  ovs_msdyn_workorderservicetask_ovs_finding?: ovs_Finding_Result[] | null;
  ts_AOCOperation?: ovs_operation_Result | null;
  ts_AOCSite?: msdyn_FunctionalLocation_Result | null;
  ts_AOCSite_Site?: ts_site_Result | null;
  ts_AOCStakeholder?: Account_Result | null;
  ts_AccessControlSecurityServices?: Account_Result | null;
  ts_ArrivalAerodrome_Site?: ts_site_Result | null;
  ts_BoardingLounge?: msdyn_FunctionalLocation_Result | null;
  ts_BoardingLounge_Site?: ts_site_Result | null;
  ts_CargoServices?: Account_Result | null;
  ts_CateringServices?: Account_Result | null;
  ts_DepartureAerodrome_Site?: ts_site_Result | null;
  ts_Destination?: msdyn_FunctionalLocation_Result | null;
  ts_Gate?: msdyn_FunctionalLocation_Result | null;
  ts_Gate_Site?: ts_site_Result | null;
  ts_GroomingServices?: Account_Result | null;
  ts_Origin?: msdyn_FunctionalLocation_Result | null;
  ts_OtherSecurityServices?: Account_Result | null;
  ts_PassengerServices?: Account_Result | null;
  ts_RampServices?: Account_Result | null;
  ts_SecuritySearchServices?: Account_Result | null;
  ts_incident_WorkOrderServiceTask1_msdyn_work?: Incident_Result[] | null;
  ts_incident_WorkOrderServiceTask2_msdyn_work?: Incident_Result[] | null;
  ts_msdyn_workorderservicetask_systemuser?: SystemUser_Result[] | null;
  ts_workorderservicetask_qm_rclegislation?: qm_rclegislation_Result[] | null;
}
interface msdyn_workorderservicetask extends msdyn_workorderservicetask_Base, msdyn_workorderservicetask_Relationships {
  msdyn_Inspection_bind$msdyn_inspections?: string | null;
  msdyn_agreementbookingservicetask_bind$msdyn_agreementbookingservicetasks?: string | null;
  msdyn_booking_bind$bookableresourcebookings?: string | null;
  msdyn_customerasset_bind$msdyn_customerassets?: string | null;
  msdyn_inspectiondefinitionid_bind$msdyn_inspectiondefinitions?: string | null;
  msdyn_inspectionresponseid_bind$msdyn_inspectionresponses?: string | null;
  msdyn_tasktype_bind$msdyn_servicetasktypes?: string | null;
  msdyn_workorder_bind$msdyn_workorders?: string | null;
  msdyn_workorderincident_bind$msdyn_workorderincidents?: string | null;
  ovs_CaseId_bind$incidents?: string | null;
  ovs_Questionnaire_bind$ovs_questionnaires?: string | null;
  ownerid_bind$systemusers?: string | null;
  ownerid_bind$teams?: string | null;
  ts_AOCOperationType_bind$ovs_operationtypes?: string | null;
  ts_AOCOperation_bind$ovs_operations?: string | null;
  ts_AOCSite_Site_bind$ts_sites?: string | null;
  ts_AOCSite_bind$msdyn_functionallocations?: string | null;
  ts_AOCStakeholder_bind$accounts?: string | null;
  ts_AccessControlSecurityServices_bind$accounts?: string | null;
  ts_ArrivalAerodrome_Site_bind$ts_sites?: string | null;
  ts_BoardingLounge_Site_bind$ts_sites?: string | null;
  ts_BoardingLounge_bind$msdyn_functionallocations?: string | null;
  ts_CargoServices_bind$accounts?: string | null;
  ts_CateringServices_bind$accounts?: string | null;
  ts_DepartureAerodrome_Site_bind$ts_sites?: string | null;
  ts_Destination_bind$msdyn_functionallocations?: string | null;
  ts_Gate_Site_bind$ts_sites?: string | null;
  ts_Gate_bind$msdyn_functionallocations?: string | null;
  ts_GroomingServices_bind$accounts?: string | null;
  ts_Origin_bind$msdyn_functionallocations?: string | null;
  ts_OtherSecurityServices_bind$accounts?: string | null;
  ts_PassengerServices_bind$accounts?: string | null;
  ts_RampServices_bind$accounts?: string | null;
  ts_SecuritySearchServices_bind$accounts?: string | null;
  ts_legislationsourcefilter_bind$qm_tylegislationsources?: string | null;
  ts_legislationtypefilter_bind$qm_tylegislationtypes?: string | null;
  ts_operationtypefilter_bind$ovs_operationtypes?: string | null;
}
interface msdyn_workorderservicetask_Create extends msdyn_workorderservicetask {
}
interface msdyn_workorderservicetask_Update extends msdyn_workorderservicetask {
}
interface msdyn_workorderservicetask_Select {
  createdby_guid: WebAttribute<msdyn_workorderservicetask_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
  createdon: WebAttribute<msdyn_workorderservicetask_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
  createdonbehalfby_guid: WebAttribute<msdyn_workorderservicetask_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
  importsequencenumber: WebAttribute<msdyn_workorderservicetask_Select, { importsequencenumber: number | null }, {  }>;
  modifiedby_guid: WebAttribute<msdyn_workorderservicetask_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
  modifiedon: WebAttribute<msdyn_workorderservicetask_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
  modifiedonbehalfby_guid: WebAttribute<msdyn_workorderservicetask_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
  msdyn_actualduration: WebAttribute<msdyn_workorderservicetask_Select, { msdyn_actualduration: number | null }, {  }>;
  msdyn_agreementbookingservicetask_guid: WebAttribute<msdyn_workorderservicetask_Select, { msdyn_agreementbookingservicetask_guid: string | null }, { msdyn_agreementbookingservicetask_formatted?: string }>;
  msdyn_booking_guid: WebAttribute<msdyn_workorderservicetask_Select, { msdyn_booking_guid: string | null }, { msdyn_booking_formatted?: string }>;
  msdyn_customerasset_guid: WebAttribute<msdyn_workorderservicetask_Select, { msdyn_customerasset_guid: string | null }, { msdyn_customerasset_formatted?: string }>;
  msdyn_description: WebAttribute<msdyn_workorderservicetask_Select, { msdyn_description: string | null }, {  }>;
  msdyn_estimatedduration: WebAttribute<msdyn_workorderservicetask_Select, { msdyn_estimatedduration: number | null }, {  }>;
  msdyn_inspection_guid: WebAttribute<msdyn_workorderservicetask_Select, { msdyn_inspection_guid: string | null }, { msdyn_inspection_formatted?: string }>;
  msdyn_inspectiondefinitionid_guid: WebAttribute<msdyn_workorderservicetask_Select, { msdyn_inspectiondefinitionid_guid: string | null }, { msdyn_inspectiondefinitionid_formatted?: string }>;
  msdyn_inspectionenabled: WebAttribute<msdyn_workorderservicetask_Select, { msdyn_inspectionenabled: boolean | null }, {  }>;
  msdyn_inspectionresponseid_guid: WebAttribute<msdyn_workorderservicetask_Select, { msdyn_inspectionresponseid_guid: string | null }, { msdyn_inspectionresponseid_formatted?: string }>;
  msdyn_inspectionresult: WebAttribute<msdyn_workorderservicetask_Select, { msdyn_inspectionresult: msdyn_msdyn_workorderservicetask_msdyn_inspectionresult | null }, { msdyn_inspectionresult_formatted?: string }>;
  msdyn_inspectiontaskresult: WebAttribute<msdyn_workorderservicetask_Select, { msdyn_inspectiontaskresult: msdyn_inspectionresult | null }, { msdyn_inspectiontaskresult_formatted?: string }>;
  msdyn_internalflags: WebAttribute<msdyn_workorderservicetask_Select, { msdyn_internalflags: string | null }, {  }>;
  msdyn_lineorder: WebAttribute<msdyn_workorderservicetask_Select, { msdyn_lineorder: number | null }, {  }>;
  msdyn_name: WebAttribute<msdyn_workorderservicetask_Select, { msdyn_name: string | null }, {  }>;
  msdyn_percentcomplete: WebAttribute<msdyn_workorderservicetask_Select, { msdyn_percentcomplete: number | null }, {  }>;
  msdyn_surveyboundedoutput: WebAttribute<msdyn_workorderservicetask_Select, { msdyn_surveyboundedoutput: string | null }, {  }>;
  msdyn_tasktype_guid: WebAttribute<msdyn_workorderservicetask_Select, { msdyn_tasktype_guid: string | null }, { msdyn_tasktype_formatted?: string }>;
  msdyn_workorder_guid: WebAttribute<msdyn_workorderservicetask_Select, { msdyn_workorder_guid: string | null }, { msdyn_workorder_formatted?: string }>;
  msdyn_workorderincident_guid: WebAttribute<msdyn_workorderservicetask_Select, { msdyn_workorderincident_guid: string | null }, { msdyn_workorderincident_formatted?: string }>;
  msdyn_workorderservicetaskid: WebAttribute<msdyn_workorderservicetask_Select, { msdyn_workorderservicetaskid: string | null }, {  }>;
  overriddencreatedon: WebAttribute<msdyn_workorderservicetask_Select, { overriddencreatedon: Date | null }, { overriddencreatedon_formatted?: string }>;
  ovs_caseid_guid: WebAttribute<msdyn_workorderservicetask_Select, { ovs_caseid_guid: string | null }, { ovs_caseid_formatted?: string }>;
  ovs_isquestionnairecomplete: WebAttribute<msdyn_workorderservicetask_Select, { ovs_isquestionnairecomplete: boolean | null }, {  }>;
  ovs_questionnaire_guid: WebAttribute<msdyn_workorderservicetask_Select, { ovs_questionnaire_guid: string | null }, { ovs_questionnaire_formatted?: string }>;
  ovs_questionnairedefinition: WebAttribute<msdyn_workorderservicetask_Select, { ovs_questionnairedefinition: string | null }, {  }>;
  ovs_questionnaireresponse: WebAttribute<msdyn_workorderservicetask_Select, { ovs_questionnaireresponse: string | null }, {  }>;
  ovs_questionnaireresultjson: WebAttribute<msdyn_workorderservicetask_Select, { ovs_questionnaireresultjson: string | null }, {  }>;
  ownerid_guid: WebAttribute<msdyn_workorderservicetask_Select, { ownerid_guid: string | null }, { ownerid_formatted?: string }>;
  owningbusinessunit_guid: WebAttribute<msdyn_workorderservicetask_Select, { owningbusinessunit_guid: string | null }, { owningbusinessunit_formatted?: string }>;
  owningteam_guid: WebAttribute<msdyn_workorderservicetask_Select, { owningteam_guid: string | null }, { owningteam_formatted?: string }>;
  owninguser_guid: WebAttribute<msdyn_workorderservicetask_Select, { owninguser_guid: string | null }, { owninguser_formatted?: string }>;
  qm_blobpath: WebAttribute<msdyn_workorderservicetask_Select, { qm_blobpath: string | null }, {  }>;
  qm_isquestionnaireupdated: WebAttribute<msdyn_workorderservicetask_Select, { qm_isquestionnaireupdated: boolean | null }, {  }>;
  statecode: WebAttribute<msdyn_workorderservicetask_Select, { statecode: msdyn_workorderservicetask_statecode | null }, { statecode_formatted?: string }>;
  statuscode: WebAttribute<msdyn_workorderservicetask_Select, { statuscode: msdyn_workorderservicetask_statuscode | null }, { statuscode_formatted?: string }>;
  timezoneruleversionnumber: WebAttribute<msdyn_workorderservicetask_Select, { timezoneruleversionnumber: number | null }, {  }>;
  ts_accesscontrol: WebAttribute<msdyn_workorderservicetask_Select, { ts_accesscontrol: boolean | null }, {  }>;
  ts_accesscontrolsecurityservices_guid: WebAttribute<msdyn_workorderservicetask_Select, { ts_accesscontrolsecurityservices_guid: string | null }, { ts_accesscontrolsecurityservices_formatted?: string }>;
  ts_actualtime: WebAttribute<msdyn_workorderservicetask_Select, { ts_actualtime: Date | null }, { ts_actualtime_formatted?: string }>;
  ts_aircraftmanufacturer: WebAttribute<msdyn_workorderservicetask_Select, { ts_aircraftmanufacturer: ts_aircraftmanufacturer | null }, { ts_aircraftmanufacturer_formatted?: string }>;
  ts_aircraftmark: WebAttribute<msdyn_workorderservicetask_Select, { ts_aircraftmark: string | null }, {  }>;
  ts_aircraftmodel: WebAttribute<msdyn_workorderservicetask_Select, { ts_aircraftmodel: ts_aircraftmodel | null }, { ts_aircraftmodel_formatted?: string }>;
  ts_aircraftmodelother: WebAttribute<msdyn_workorderservicetask_Select, { ts_aircraftmodelother: string | null }, {  }>;
  ts_aocoperation_guid: WebAttribute<msdyn_workorderservicetask_Select, { ts_aocoperation_guid: string | null }, { ts_aocoperation_formatted?: string }>;
  ts_aocoperationtype_guid: WebAttribute<msdyn_workorderservicetask_Select, { ts_aocoperationtype_guid: string | null }, { ts_aocoperationtype_formatted?: string }>;
  ts_aocsite_guid: WebAttribute<msdyn_workorderservicetask_Select, { ts_aocsite_guid: string | null }, { ts_aocsite_formatted?: string }>;
  ts_aocsite_site_guid: WebAttribute<msdyn_workorderservicetask_Select, { ts_aocsite_site_guid: string | null }, { ts_aocsite_site_formatted?: string }>;
  ts_aocstakeholder_guid: WebAttribute<msdyn_workorderservicetask_Select, { ts_aocstakeholder_guid: string | null }, { ts_aocstakeholder_formatted?: string }>;
  ts_arrivalaerodrome_site_guid: WebAttribute<msdyn_workorderservicetask_Select, { ts_arrivalaerodrome_site_guid: string | null }, { ts_arrivalaerodrome_site_formatted?: string }>;
  ts_boardinglounge_guid: WebAttribute<msdyn_workorderservicetask_Select, { ts_boardinglounge_guid: string | null }, { ts_boardinglounge_formatted?: string }>;
  ts_boardinglounge_site_guid: WebAttribute<msdyn_workorderservicetask_Select, { ts_boardinglounge_site_guid: string | null }, { ts_boardinglounge_site_formatted?: string }>;
  ts_brandname: WebAttribute<msdyn_workorderservicetask_Select, { ts_brandname: ts_aircarrierbrandname | null }, { ts_brandname_formatted?: string }>;
  ts_cargoservices_guid: WebAttribute<msdyn_workorderservicetask_Select, { ts_cargoservices_guid: string | null }, { ts_cargoservices_formatted?: string }>;
  ts_cateringservices_guid: WebAttribute<msdyn_workorderservicetask_Select, { ts_cateringservices_guid: string | null }, { ts_cateringservices_formatted?: string }>;
  ts_cbloaded: WebAttribute<msdyn_workorderservicetask_Select, { ts_cbloaded: string | null }, {  }>;
  ts_cbonboard: WebAttribute<msdyn_workorderservicetask_Select, { ts_cbonboard: string | null }, {  }>;
  ts_departureaerodrome_site_guid: WebAttribute<msdyn_workorderservicetask_Select, { ts_departureaerodrome_site_guid: string | null }, { ts_departureaerodrome_site_formatted?: string }>;
  ts_destination_guid: WebAttribute<msdyn_workorderservicetask_Select, { ts_destination_guid: string | null }, { ts_destination_formatted?: string }>;
  ts_documenteddate: WebAttribute<msdyn_workorderservicetask_Select, { ts_documenteddate: Date | null }, { ts_documenteddate_formatted?: string }>;
  ts_flightcategory: WebAttribute<msdyn_workorderservicetask_Select, { ts_flightcategory: ts_flightcategory | null }, { ts_flightcategory_formatted?: string }>;
  ts_flightnumber: WebAttribute<msdyn_workorderservicetask_Select, { ts_flightnumber: string | null }, {  }>;
  ts_flighttype: WebAttribute<msdyn_workorderservicetask_Select, { ts_flighttype: ts_flighttype | null }, { ts_flighttype_formatted?: string }>;
  ts_gate_guid: WebAttribute<msdyn_workorderservicetask_Select, { ts_gate_guid: string | null }, { ts_gate_formatted?: string }>;
  ts_gate_site_guid: WebAttribute<msdyn_workorderservicetask_Select, { ts_gate_site_guid: string | null }, { ts_gate_site_formatted?: string }>;
  ts_groomingservices_guid: WebAttribute<msdyn_workorderservicetask_Select, { ts_groomingservices_guid: string | null }, { ts_groomingservices_formatted?: string }>;
  ts_legislationsourcefilter_guid: WebAttribute<msdyn_workorderservicetask_Select, { ts_legislationsourcefilter_guid: string | null }, { ts_legislationsourcefilter_formatted?: string }>;
  ts_legislationtypefilter_guid: WebAttribute<msdyn_workorderservicetask_Select, { ts_legislationtypefilter_guid: string | null }, { ts_legislationtypefilter_formatted?: string }>;
  ts_location: WebAttribute<msdyn_workorderservicetask_Select, { ts_location: string | null }, {  }>;
  ts_mandatory: WebAttribute<msdyn_workorderservicetask_Select, { ts_mandatory: boolean | null }, {  }>;
  ts_operationtypefilter_guid: WebAttribute<msdyn_workorderservicetask_Select, { ts_operationtypefilter_guid: string | null }, { ts_operationtypefilter_formatted?: string }>;
  ts_origin_guid: WebAttribute<msdyn_workorderservicetask_Select, { ts_origin_guid: string | null }, { ts_origin_formatted?: string }>;
  ts_othersecurityservices_guid: WebAttribute<msdyn_workorderservicetask_Select, { ts_othersecurityservices_guid: string | null }, { ts_othersecurityservices_formatted?: string }>;
  ts_passengerservices_guid: WebAttribute<msdyn_workorderservicetask_Select, { ts_passengerservices_guid: string | null }, { ts_passengerservices_formatted?: string }>;
  ts_paxboarded: WebAttribute<msdyn_workorderservicetask_Select, { ts_paxboarded: string | null }, {  }>;
  ts_paxonboard: WebAttribute<msdyn_workorderservicetask_Select, { ts_paxonboard: string | null }, {  }>;
  ts_rampservices_guid: WebAttribute<msdyn_workorderservicetask_Select, { ts_rampservices_guid: string | null }, { ts_rampservices_formatted?: string }>;
  ts_reportdetails: WebAttribute<msdyn_workorderservicetask_Select, { ts_reportdetails: string | null }, {  }>;
  ts_scheduledtime: WebAttribute<msdyn_workorderservicetask_Select, { ts_scheduledtime: Date | null }, { ts_scheduledtime_formatted?: string }>;
  ts_securitysearchservices_guid: WebAttribute<msdyn_workorderservicetask_Select, { ts_securitysearchservices_guid: string | null }, { ts_securitysearchservices_formatted?: string }>;
  ts_servicetaskenddate: WebAttribute<msdyn_workorderservicetask_Select, { ts_servicetaskenddate: Date | null }, { ts_servicetaskenddate_formatted?: string }>;
  ts_servicetaskstartdate: WebAttribute<msdyn_workorderservicetask_Select, { ts_servicetaskstartdate: Date | null }, { ts_servicetaskstartdate_formatted?: string }>;
  ts_workorderstartdate: WebAttribute<msdyn_workorderservicetask_Select, { ts_workorderstartdate: Date | null }, { ts_workorderstartdate_formatted?: string }>;
  utcconversiontimezonecode: WebAttribute<msdyn_workorderservicetask_Select, { utcconversiontimezonecode: number | null }, {  }>;
  versionnumber: WebAttribute<msdyn_workorderservicetask_Select, { versionnumber: number | null }, {  }>;
}
interface msdyn_workorderservicetask_Filter {
  createdby_guid: XQW.Guid;
  createdon: Date;
  createdonbehalfby_guid: XQW.Guid;
  importsequencenumber: number;
  modifiedby_guid: XQW.Guid;
  modifiedon: Date;
  modifiedonbehalfby_guid: XQW.Guid;
  msdyn_actualduration: number;
  msdyn_agreementbookingservicetask_guid: XQW.Guid;
  msdyn_booking_guid: XQW.Guid;
  msdyn_customerasset_guid: XQW.Guid;
  msdyn_description: string;
  msdyn_estimatedduration: number;
  msdyn_inspection_guid: XQW.Guid;
  msdyn_inspectiondefinitionid_guid: XQW.Guid;
  msdyn_inspectionenabled: boolean;
  msdyn_inspectionresponseid_guid: XQW.Guid;
  msdyn_inspectionresult: msdyn_msdyn_workorderservicetask_msdyn_inspectionresult;
  msdyn_inspectiontaskresult: msdyn_inspectionresult;
  msdyn_internalflags: string;
  msdyn_lineorder: number;
  msdyn_name: string;
  msdyn_percentcomplete: number;
  msdyn_surveyboundedoutput: string;
  msdyn_tasktype_guid: XQW.Guid;
  msdyn_workorder_guid: XQW.Guid;
  msdyn_workorderincident_guid: XQW.Guid;
  msdyn_workorderservicetaskid: XQW.Guid;
  overriddencreatedon: Date;
  ovs_caseid_guid: XQW.Guid;
  ovs_isquestionnairecomplete: boolean;
  ovs_questionnaire_guid: XQW.Guid;
  ovs_questionnairedefinition: string;
  ovs_questionnaireresponse: string;
  ovs_questionnaireresultjson: string;
  ownerid_guid: XQW.Guid;
  owningbusinessunit_guid: XQW.Guid;
  owningteam_guid: XQW.Guid;
  owninguser_guid: XQW.Guid;
  qm_blobpath: string;
  qm_isquestionnaireupdated: boolean;
  statecode: msdyn_workorderservicetask_statecode;
  statuscode: msdyn_workorderservicetask_statuscode;
  timezoneruleversionnumber: number;
  ts_accesscontrol: boolean;
  ts_accesscontrolsecurityservices_guid: XQW.Guid;
  ts_actualtime: Date;
  ts_aircraftmanufacturer: ts_aircraftmanufacturer;
  ts_aircraftmark: string;
  ts_aircraftmodel: ts_aircraftmodel;
  ts_aircraftmodelother: string;
  ts_aocoperation_guid: XQW.Guid;
  ts_aocoperationtype_guid: XQW.Guid;
  ts_aocsite_guid: XQW.Guid;
  ts_aocsite_site_guid: XQW.Guid;
  ts_aocstakeholder_guid: XQW.Guid;
  ts_arrivalaerodrome_site_guid: XQW.Guid;
  ts_boardinglounge_guid: XQW.Guid;
  ts_boardinglounge_site_guid: XQW.Guid;
  ts_brandname: ts_aircarrierbrandname;
  ts_cargoservices_guid: XQW.Guid;
  ts_cateringservices_guid: XQW.Guid;
  ts_cbloaded: string;
  ts_cbonboard: string;
  ts_departureaerodrome_site_guid: XQW.Guid;
  ts_destination_guid: XQW.Guid;
  ts_documenteddate: Date;
  ts_flightcategory: ts_flightcategory;
  ts_flightnumber: string;
  ts_flighttype: ts_flighttype;
  ts_gate_guid: XQW.Guid;
  ts_gate_site_guid: XQW.Guid;
  ts_groomingservices_guid: XQW.Guid;
  ts_legislationsourcefilter_guid: XQW.Guid;
  ts_legislationtypefilter_guid: XQW.Guid;
  ts_location: string;
  ts_mandatory: boolean;
  ts_operationtypefilter_guid: XQW.Guid;
  ts_origin_guid: XQW.Guid;
  ts_othersecurityservices_guid: XQW.Guid;
  ts_passengerservices_guid: XQW.Guid;
  ts_paxboarded: string;
  ts_paxonboard: string;
  ts_rampservices_guid: XQW.Guid;
  ts_reportdetails: string;
  ts_scheduledtime: Date;
  ts_securitysearchservices_guid: XQW.Guid;
  ts_servicetaskenddate: Date;
  ts_servicetaskstartdate: Date;
  ts_workorderstartdate: Date;
  utcconversiontimezonecode: number;
  versionnumber: number;
}
interface msdyn_workorderservicetask_Expand {
  createdby: WebExpand<msdyn_workorderservicetask_Expand, SystemUser_Select, SystemUser_Filter, { createdby: SystemUser_Result }>;
  createdonbehalfby: WebExpand<msdyn_workorderservicetask_Expand, SystemUser_Select, SystemUser_Filter, { createdonbehalfby: SystemUser_Result }>;
  modifiedby: WebExpand<msdyn_workorderservicetask_Expand, SystemUser_Select, SystemUser_Filter, { modifiedby: SystemUser_Result }>;
  modifiedonbehalfby: WebExpand<msdyn_workorderservicetask_Expand, SystemUser_Select, SystemUser_Filter, { modifiedonbehalfby: SystemUser_Result }>;
  msdyn_booking: WebExpand<msdyn_workorderservicetask_Expand, BookableResourceBooking_Select, BookableResourceBooking_Filter, { msdyn_booking: BookableResourceBooking_Result }>;
  msdyn_customerasset: WebExpand<msdyn_workorderservicetask_Expand, msdyn_customerasset_Select, msdyn_customerasset_Filter, { msdyn_customerasset: msdyn_customerasset_Result }>;
  msdyn_tasktype: WebExpand<msdyn_workorderservicetask_Expand, msdyn_servicetasktype_Select, msdyn_servicetasktype_Filter, { msdyn_tasktype: msdyn_servicetasktype_Result }>;
  msdyn_workorder: WebExpand<msdyn_workorderservicetask_Expand, msdyn_workorder_Select, msdyn_workorder_Filter, { msdyn_workorder: msdyn_workorder_Result }>;
  msdyn_workorderservicetask_Appointments: WebExpand<msdyn_workorderservicetask_Expand, Appointment_Select, Appointment_Filter, { msdyn_workorderservicetask_Appointments: Appointment_Result[] }>;
  msdyn_workorderservicetask_Emails: WebExpand<msdyn_workorderservicetask_Expand, Email_Select, Email_Filter, { msdyn_workorderservicetask_Emails: Email_Result[] }>;
  msdyn_workorderservicetask_ServiceAppointments: WebExpand<msdyn_workorderservicetask_Expand, ServiceAppointment_Select, ServiceAppointment_Filter, { msdyn_workorderservicetask_ServiceAppointments: ServiceAppointment_Result[] }>;
  msdyn_workorderservicetask_connections1: WebExpand<msdyn_workorderservicetask_Expand, Connection_Select, Connection_Filter, { msdyn_workorderservicetask_connections1: Connection_Result[] }>;
  msdyn_workorderservicetask_connections2: WebExpand<msdyn_workorderservicetask_Expand, Connection_Select, Connection_Filter, { msdyn_workorderservicetask_connections2: Connection_Result[] }>;
  msdyn_workorderservicetask_ts_enforcementactions: WebExpand<msdyn_workorderservicetask_Expand, ts_enforcementaction_Select, ts_enforcementaction_Filter, { msdyn_workorderservicetask_ts_enforcementactions: ts_enforcementaction_Result[] }>;
  ovs_CaseId: WebExpand<msdyn_workorderservicetask_Expand, Incident_Select, Incident_Filter, { ovs_CaseId: Incident_Result }>;
  ovs_Questionnaire: WebExpand<msdyn_workorderservicetask_Expand, ovs_Questionnaire_Select, ovs_Questionnaire_Filter, { ovs_Questionnaire: ovs_Questionnaire_Result }>;
  ovs_msdyn_workorderservicetask_ovs_finding: WebExpand<msdyn_workorderservicetask_Expand, ovs_Finding_Select, ovs_Finding_Filter, { ovs_msdyn_workorderservicetask_ovs_finding: ovs_Finding_Result[] }>;
  ownerid: WebExpand<msdyn_workorderservicetask_Expand, SystemUser_Select & Team_Select, SystemUser_Filter & Team_Filter, { ownerid: SystemUser_Result } & { ownerid: Team_Result }>;
  owningteam: WebExpand<msdyn_workorderservicetask_Expand, Team_Select, Team_Filter, { owningteam: Team_Result }>;
  owninguser: WebExpand<msdyn_workorderservicetask_Expand, SystemUser_Select, SystemUser_Filter, { owninguser: SystemUser_Result }>;
  ts_AOCOperation: WebExpand<msdyn_workorderservicetask_Expand, ovs_operation_Select, ovs_operation_Filter, { ts_AOCOperation: ovs_operation_Result }>;
  ts_AOCSite: WebExpand<msdyn_workorderservicetask_Expand, msdyn_FunctionalLocation_Select, msdyn_FunctionalLocation_Filter, { ts_AOCSite: msdyn_FunctionalLocation_Result }>;
  ts_AOCSite_Site: WebExpand<msdyn_workorderservicetask_Expand, ts_site_Select, ts_site_Filter, { ts_AOCSite_Site: ts_site_Result }>;
  ts_AOCStakeholder: WebExpand<msdyn_workorderservicetask_Expand, Account_Select, Account_Filter, { ts_AOCStakeholder: Account_Result }>;
  ts_AccessControlSecurityServices: WebExpand<msdyn_workorderservicetask_Expand, Account_Select, Account_Filter, { ts_AccessControlSecurityServices: Account_Result }>;
  ts_ArrivalAerodrome_Site: WebExpand<msdyn_workorderservicetask_Expand, ts_site_Select, ts_site_Filter, { ts_ArrivalAerodrome_Site: ts_site_Result }>;
  ts_BoardingLounge: WebExpand<msdyn_workorderservicetask_Expand, msdyn_FunctionalLocation_Select, msdyn_FunctionalLocation_Filter, { ts_BoardingLounge: msdyn_FunctionalLocation_Result }>;
  ts_BoardingLounge_Site: WebExpand<msdyn_workorderservicetask_Expand, ts_site_Select, ts_site_Filter, { ts_BoardingLounge_Site: ts_site_Result }>;
  ts_CargoServices: WebExpand<msdyn_workorderservicetask_Expand, Account_Select, Account_Filter, { ts_CargoServices: Account_Result }>;
  ts_CateringServices: WebExpand<msdyn_workorderservicetask_Expand, Account_Select, Account_Filter, { ts_CateringServices: Account_Result }>;
  ts_DepartureAerodrome_Site: WebExpand<msdyn_workorderservicetask_Expand, ts_site_Select, ts_site_Filter, { ts_DepartureAerodrome_Site: ts_site_Result }>;
  ts_Destination: WebExpand<msdyn_workorderservicetask_Expand, msdyn_FunctionalLocation_Select, msdyn_FunctionalLocation_Filter, { ts_Destination: msdyn_FunctionalLocation_Result }>;
  ts_Gate: WebExpand<msdyn_workorderservicetask_Expand, msdyn_FunctionalLocation_Select, msdyn_FunctionalLocation_Filter, { ts_Gate: msdyn_FunctionalLocation_Result }>;
  ts_Gate_Site: WebExpand<msdyn_workorderservicetask_Expand, ts_site_Select, ts_site_Filter, { ts_Gate_Site: ts_site_Result }>;
  ts_GroomingServices: WebExpand<msdyn_workorderservicetask_Expand, Account_Select, Account_Filter, { ts_GroomingServices: Account_Result }>;
  ts_Origin: WebExpand<msdyn_workorderservicetask_Expand, msdyn_FunctionalLocation_Select, msdyn_FunctionalLocation_Filter, { ts_Origin: msdyn_FunctionalLocation_Result }>;
  ts_OtherSecurityServices: WebExpand<msdyn_workorderservicetask_Expand, Account_Select, Account_Filter, { ts_OtherSecurityServices: Account_Result }>;
  ts_PassengerServices: WebExpand<msdyn_workorderservicetask_Expand, Account_Select, Account_Filter, { ts_PassengerServices: Account_Result }>;
  ts_RampServices: WebExpand<msdyn_workorderservicetask_Expand, Account_Select, Account_Filter, { ts_RampServices: Account_Result }>;
  ts_SecuritySearchServices: WebExpand<msdyn_workorderservicetask_Expand, Account_Select, Account_Filter, { ts_SecuritySearchServices: Account_Result }>;
  ts_incident_WorkOrderServiceTask1_msdyn_work: WebExpand<msdyn_workorderservicetask_Expand, Incident_Select, Incident_Filter, { ts_incident_WorkOrderServiceTask1_msdyn_work: Incident_Result[] }>;
  ts_incident_WorkOrderServiceTask2_msdyn_work: WebExpand<msdyn_workorderservicetask_Expand, Incident_Select, Incident_Filter, { ts_incident_WorkOrderServiceTask2_msdyn_work: Incident_Result[] }>;
  ts_msdyn_workorderservicetask_systemuser: WebExpand<msdyn_workorderservicetask_Expand, SystemUser_Select, SystemUser_Filter, { ts_msdyn_workorderservicetask_systemuser: SystemUser_Result[] }>;
  ts_workorderservicetask_qm_rclegislation: WebExpand<msdyn_workorderservicetask_Expand, qm_rclegislation_Select, qm_rclegislation_Filter, { ts_workorderservicetask_qm_rclegislation: qm_rclegislation_Result[] }>;
}
interface msdyn_workorderservicetask_FormattedResult {
  createdby_formatted?: string;
  createdon_formatted?: string;
  createdonbehalfby_formatted?: string;
  modifiedby_formatted?: string;
  modifiedon_formatted?: string;
  modifiedonbehalfby_formatted?: string;
  msdyn_agreementbookingservicetask_formatted?: string;
  msdyn_booking_formatted?: string;
  msdyn_customerasset_formatted?: string;
  msdyn_inspection_formatted?: string;
  msdyn_inspectiondefinitionid_formatted?: string;
  msdyn_inspectionresponseid_formatted?: string;
  msdyn_inspectionresult_formatted?: string;
  msdyn_inspectiontaskresult_formatted?: string;
  msdyn_tasktype_formatted?: string;
  msdyn_workorder_formatted?: string;
  msdyn_workorderincident_formatted?: string;
  overriddencreatedon_formatted?: string;
  ovs_caseid_formatted?: string;
  ovs_questionnaire_formatted?: string;
  ownerid_formatted?: string;
  owningbusinessunit_formatted?: string;
  owningteam_formatted?: string;
  owninguser_formatted?: string;
  statecode_formatted?: string;
  statuscode_formatted?: string;
  ts_accesscontrolsecurityservices_formatted?: string;
  ts_actualtime_formatted?: string;
  ts_aircraftmanufacturer_formatted?: string;
  ts_aircraftmodel_formatted?: string;
  ts_aocoperation_formatted?: string;
  ts_aocoperationtype_formatted?: string;
  ts_aocsite_formatted?: string;
  ts_aocsite_site_formatted?: string;
  ts_aocstakeholder_formatted?: string;
  ts_arrivalaerodrome_site_formatted?: string;
  ts_boardinglounge_formatted?: string;
  ts_boardinglounge_site_formatted?: string;
  ts_brandname_formatted?: string;
  ts_cargoservices_formatted?: string;
  ts_cateringservices_formatted?: string;
  ts_departureaerodrome_site_formatted?: string;
  ts_destination_formatted?: string;
  ts_documenteddate_formatted?: string;
  ts_flightcategory_formatted?: string;
  ts_flighttype_formatted?: string;
  ts_gate_formatted?: string;
  ts_gate_site_formatted?: string;
  ts_groomingservices_formatted?: string;
  ts_legislationsourcefilter_formatted?: string;
  ts_legislationtypefilter_formatted?: string;
  ts_operationtypefilter_formatted?: string;
  ts_origin_formatted?: string;
  ts_othersecurityservices_formatted?: string;
  ts_passengerservices_formatted?: string;
  ts_rampservices_formatted?: string;
  ts_scheduledtime_formatted?: string;
  ts_securitysearchservices_formatted?: string;
  ts_servicetaskenddate_formatted?: string;
  ts_servicetaskstartdate_formatted?: string;
  ts_workorderstartdate_formatted?: string;
}
interface msdyn_workorderservicetask_Result extends msdyn_workorderservicetask_Base, msdyn_workorderservicetask_Relationships {
  "@odata.etag": string;
  createdby_guid: string | null;
  createdonbehalfby_guid: string | null;
  modifiedby_guid: string | null;
  modifiedonbehalfby_guid: string | null;
  msdyn_agreementbookingservicetask_guid: string | null;
  msdyn_booking_guid: string | null;
  msdyn_customerasset_guid: string | null;
  msdyn_inspection_guid: string | null;
  msdyn_inspectiondefinitionid_guid: string | null;
  msdyn_inspectionresponseid_guid: string | null;
  msdyn_tasktype_guid: string | null;
  msdyn_workorder_guid: string | null;
  msdyn_workorderincident_guid: string | null;
  ovs_caseid_guid: string | null;
  ovs_questionnaire_guid: string | null;
  ownerid_guid: string | null;
  owningbusinessunit_guid: string | null;
  owningteam_guid: string | null;
  owninguser_guid: string | null;
  ts_accesscontrolsecurityservices_guid: string | null;
  ts_aocoperation_guid: string | null;
  ts_aocoperationtype_guid: string | null;
  ts_aocsite_guid: string | null;
  ts_aocsite_site_guid: string | null;
  ts_aocstakeholder_guid: string | null;
  ts_arrivalaerodrome_site_guid: string | null;
  ts_boardinglounge_guid: string | null;
  ts_boardinglounge_site_guid: string | null;
  ts_cargoservices_guid: string | null;
  ts_cateringservices_guid: string | null;
  ts_departureaerodrome_site_guid: string | null;
  ts_destination_guid: string | null;
  ts_gate_guid: string | null;
  ts_gate_site_guid: string | null;
  ts_groomingservices_guid: string | null;
  ts_legislationsourcefilter_guid: string | null;
  ts_legislationtypefilter_guid: string | null;
  ts_operationtypefilter_guid: string | null;
  ts_origin_guid: string | null;
  ts_othersecurityservices_guid: string | null;
  ts_passengerservices_guid: string | null;
  ts_rampservices_guid: string | null;
  ts_securitysearchservices_guid: string | null;
}
interface msdyn_workorderservicetask_RelatedOne {
  createdby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  createdonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  msdyn_booking: WebMappingRetrieve<BookableResourceBooking_Select,BookableResourceBooking_Expand,BookableResourceBooking_Filter,BookableResourceBooking_Fixed,BookableResourceBooking_Result,BookableResourceBooking_FormattedResult>;
  msdyn_customerasset: WebMappingRetrieve<msdyn_customerasset_Select,msdyn_customerasset_Expand,msdyn_customerasset_Filter,msdyn_customerasset_Fixed,msdyn_customerasset_Result,msdyn_customerasset_FormattedResult>;
  msdyn_tasktype: WebMappingRetrieve<msdyn_servicetasktype_Select,msdyn_servicetasktype_Expand,msdyn_servicetasktype_Filter,msdyn_servicetasktype_Fixed,msdyn_servicetasktype_Result,msdyn_servicetasktype_FormattedResult>;
  msdyn_workorder: WebMappingRetrieve<msdyn_workorder_Select,msdyn_workorder_Expand,msdyn_workorder_Filter,msdyn_workorder_Fixed,msdyn_workorder_Result,msdyn_workorder_FormattedResult>;
  ovs_CaseId: WebMappingRetrieve<Incident_Select,Incident_Expand,Incident_Filter,Incident_Fixed,Incident_Result,Incident_FormattedResult>;
  ovs_Questionnaire: WebMappingRetrieve<ovs_Questionnaire_Select,ovs_Questionnaire_Expand,ovs_Questionnaire_Filter,ovs_Questionnaire_Fixed,ovs_Questionnaire_Result,ovs_Questionnaire_FormattedResult>;
  ownerid: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult> & WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owningteam: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owninguser: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  ts_AOCOperation: WebMappingRetrieve<ovs_operation_Select,ovs_operation_Expand,ovs_operation_Filter,ovs_operation_Fixed,ovs_operation_Result,ovs_operation_FormattedResult>;
  ts_AOCSite: WebMappingRetrieve<msdyn_FunctionalLocation_Select,msdyn_FunctionalLocation_Expand,msdyn_FunctionalLocation_Filter,msdyn_FunctionalLocation_Fixed,msdyn_FunctionalLocation_Result,msdyn_FunctionalLocation_FormattedResult>;
  ts_AOCSite_Site: WebMappingRetrieve<ts_site_Select,ts_site_Expand,ts_site_Filter,ts_site_Fixed,ts_site_Result,ts_site_FormattedResult>;
  ts_AOCStakeholder: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  ts_AccessControlSecurityServices: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  ts_ArrivalAerodrome_Site: WebMappingRetrieve<ts_site_Select,ts_site_Expand,ts_site_Filter,ts_site_Fixed,ts_site_Result,ts_site_FormattedResult>;
  ts_BoardingLounge: WebMappingRetrieve<msdyn_FunctionalLocation_Select,msdyn_FunctionalLocation_Expand,msdyn_FunctionalLocation_Filter,msdyn_FunctionalLocation_Fixed,msdyn_FunctionalLocation_Result,msdyn_FunctionalLocation_FormattedResult>;
  ts_BoardingLounge_Site: WebMappingRetrieve<ts_site_Select,ts_site_Expand,ts_site_Filter,ts_site_Fixed,ts_site_Result,ts_site_FormattedResult>;
  ts_CargoServices: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  ts_CateringServices: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  ts_DepartureAerodrome_Site: WebMappingRetrieve<ts_site_Select,ts_site_Expand,ts_site_Filter,ts_site_Fixed,ts_site_Result,ts_site_FormattedResult>;
  ts_Destination: WebMappingRetrieve<msdyn_FunctionalLocation_Select,msdyn_FunctionalLocation_Expand,msdyn_FunctionalLocation_Filter,msdyn_FunctionalLocation_Fixed,msdyn_FunctionalLocation_Result,msdyn_FunctionalLocation_FormattedResult>;
  ts_Gate: WebMappingRetrieve<msdyn_FunctionalLocation_Select,msdyn_FunctionalLocation_Expand,msdyn_FunctionalLocation_Filter,msdyn_FunctionalLocation_Fixed,msdyn_FunctionalLocation_Result,msdyn_FunctionalLocation_FormattedResult>;
  ts_Gate_Site: WebMappingRetrieve<ts_site_Select,ts_site_Expand,ts_site_Filter,ts_site_Fixed,ts_site_Result,ts_site_FormattedResult>;
  ts_GroomingServices: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  ts_Origin: WebMappingRetrieve<msdyn_FunctionalLocation_Select,msdyn_FunctionalLocation_Expand,msdyn_FunctionalLocation_Filter,msdyn_FunctionalLocation_Fixed,msdyn_FunctionalLocation_Result,msdyn_FunctionalLocation_FormattedResult>;
  ts_OtherSecurityServices: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  ts_PassengerServices: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  ts_RampServices: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  ts_SecuritySearchServices: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
}
interface msdyn_workorderservicetask_RelatedMany {
  msdyn_workorderservicetask_Appointments: WebMappingRetrieve<Appointment_Select,Appointment_Expand,Appointment_Filter,Appointment_Fixed,Appointment_Result,Appointment_FormattedResult>;
  msdyn_workorderservicetask_Emails: WebMappingRetrieve<Email_Select,Email_Expand,Email_Filter,Email_Fixed,Email_Result,Email_FormattedResult>;
  msdyn_workorderservicetask_ServiceAppointments: WebMappingRetrieve<ServiceAppointment_Select,ServiceAppointment_Expand,ServiceAppointment_Filter,ServiceAppointment_Fixed,ServiceAppointment_Result,ServiceAppointment_FormattedResult>;
  msdyn_workorderservicetask_connections1: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  msdyn_workorderservicetask_connections2: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  msdyn_workorderservicetask_ts_enforcementactions: WebMappingRetrieve<ts_enforcementaction_Select,ts_enforcementaction_Expand,ts_enforcementaction_Filter,ts_enforcementaction_Fixed,ts_enforcementaction_Result,ts_enforcementaction_FormattedResult>;
  ovs_msdyn_workorderservicetask_ovs_finding: WebMappingRetrieve<ovs_Finding_Select,ovs_Finding_Expand,ovs_Finding_Filter,ovs_Finding_Fixed,ovs_Finding_Result,ovs_Finding_FormattedResult>;
  ts_incident_WorkOrderServiceTask1_msdyn_work: WebMappingRetrieve<Incident_Select,Incident_Expand,Incident_Filter,Incident_Fixed,Incident_Result,Incident_FormattedResult>;
  ts_incident_WorkOrderServiceTask2_msdyn_work: WebMappingRetrieve<Incident_Select,Incident_Expand,Incident_Filter,Incident_Fixed,Incident_Result,Incident_FormattedResult>;
  ts_msdyn_workorderservicetask_systemuser: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  ts_workorderservicetask_qm_rclegislation: WebMappingRetrieve<qm_rclegislation_Select,qm_rclegislation_Expand,qm_rclegislation_Filter,qm_rclegislation_Fixed,qm_rclegislation_Result,qm_rclegislation_FormattedResult>;
}
interface WebEntitiesRetrieve {
  msdyn_workorderservicetasks: WebMappingRetrieve<msdyn_workorderservicetask_Select,msdyn_workorderservicetask_Expand,msdyn_workorderservicetask_Filter,msdyn_workorderservicetask_Fixed,msdyn_workorderservicetask_Result,msdyn_workorderservicetask_FormattedResult>;
}
interface WebEntitiesRelated {
  msdyn_workorderservicetasks: WebMappingRelated<msdyn_workorderservicetask_RelatedOne,msdyn_workorderservicetask_RelatedMany>;
}
interface WebEntitiesCUDA {
  msdyn_workorderservicetasks: WebMappingCUDA<msdyn_workorderservicetask_Create,msdyn_workorderservicetask_Update,msdyn_workorderservicetask_Select>;
}
