interface ts_serviceofenforcementaction_Base extends WebEntity {
  activityadditionalparams?: string | null;
  activityid?: string | null;
  activitytypecode?: string | null;
  actualdurationminutes?: number | null;
  actualend?: Date | null;
  actualstart?: Date | null;
  community?: socialprofile_community | null;
  createdon?: Date | null;
  deliverylastattemptedon?: Date | null;
  deliveryprioritycode?: activitypointer_deliveryprioritycode | null;
  description?: string | null;
  exchangeitemid?: string | null;
  exchangerate?: number | null;
  exchangeweblink?: string | null;
  importsequencenumber?: number | null;
  instancetypecode?: ts_serviceofenforcementaction_instancetypecode | null;
  isbilled?: boolean | null;
  ismapiprivate?: boolean | null;
  isregularactivity?: boolean | null;
  isworkflowcreated?: boolean | null;
  lastonholdtime?: Date | null;
  leftvoicemail?: boolean | null;
  modifiedon?: Date | null;
  onholdtime?: number | null;
  overriddencreatedon?: Date | null;
  postponeactivityprocessinguntil?: Date | null;
  prioritycode?: ts_serviceofenforcementaction_prioritycode | null;
  processid?: string | null;
  scheduleddurationminutes?: number | null;
  scheduledend?: Date | null;
  scheduledstart?: Date | null;
  senton?: Date | null;
  seriesid?: string | null;
  sortdate?: Date | null;
  stageid?: string | null;
  statecode?: ts_serviceofenforcementaction_statecode | null;
  statuscode?: ts_serviceofenforcementaction_statuscode | null;
  subject?: string | null;
  timezoneruleversionnumber?: number | null;
  traversedpath?: string | null;
  ts_comments?: string | null;
  ts_copyofreceiptifapplicable?: string | null;
  ts_individualposition?: string | null;
  ts_methodofservice?: ts_methodofservice | null;
  ts_timeanddateofservice?: Date | null;
  ts_verbalwarningdate?: Date | null;
  ts_verbalwarningwhere?: ts_verbalwarninglocation | null;
  ts_verbalwarningwhereother?: string | null;
  utcconversiontimezonecode?: number | null;
  versionnumber?: number | null;
}
interface ts_serviceofenforcementaction_Relationships {
  createdby_ts_serviceofenforcementaction?: SystemUser_Result | null;
  createdonbehalfby_ts_serviceofenforcementaction?: SystemUser_Result | null;
  modifiedby_ts_serviceofenforcementaction?: SystemUser_Result | null;
  modifiedonbehalfby_ts_serviceofenforcementaction?: SystemUser_Result | null;
  ownerid_ts_serviceofenforcementaction?: SystemUser_Result | null;
  owninguser_ts_serviceofenforcementaction?: SystemUser_Result | null;
  regardingobjectid_account_ts_serviceofenforcementaction?: Account_Result | null;
  regardingobjectid_bookableresourcebooking_ts_serviceofenforcementaction?: BookableResourceBooking_Result | null;
  regardingobjectid_contact_ts_serviceofenforcementaction?: Contact_Result | null;
  regardingobjectid_incident_ts_serviceofenforcementaction?: Incident_Result | null;
  regardingobjectid_msdyn_customerasset_ts_serviceofenforcementaction?: msdyn_customerasset_Result | null;
  regardingobjectid_msdyn_workorder_ts_serviceofenforcementaction?: msdyn_workorder_Result | null;
  regardingobjectid_msdyn_workorderservicetask_ts_serviceofenforcementaction?: msdyn_workorderservicetask_Result | null;
  regardingobjectid_ovs_operation_ts_serviceofenforcementaction?: ovs_operation_Result | null;
  regardingobjectid_ts_enforcementaction_ts_serviceofenforcementaction?: ts_EnforcementAction_Result | null;
  ts_AuthorizedRepresentative_ts_serviceofenforcementaction?: Contact_Result | null;
  ts_IndividualCompany_ts_serviceofenforcementaction?: Account_Result | null;
  ts_VerbalWarningGivenTo_ts_serviceofenforcementaction?: Contact_Result | null;
  ts_serviceofenforcementaction_activity_parties?: ActivityParty_Result[] | null;
  ts_serviceofenforcementaction_connections1?: Connection_Result[] | null;
  ts_serviceofenforcementaction_connections2?: Connection_Result[] | null;
}
interface ts_serviceofenforcementaction extends ts_serviceofenforcementaction_Base, ts_serviceofenforcementaction_Relationships {
  ownerid_ts_serviceofenforcementaction_bind$systemusers?: string | null;
  ownerid_ts_serviceofenforcementaction_bind$teams?: string | null;
  regardingobjectid_account_ts_serviceofenforcementaction_bind$accounts?: string | null;
  regardingobjectid_bookableresourcebooking_ts_serviceofenforcementaction_bind$bookableresourcebookings?: string | null;
  regardingobjectid_bookableresourcebookingheader_ts_serviceofenforcementaction_bind$bookableresourcebookingheaders?: string | null;
  regardingobjectid_bulkoperation_ts_serviceofenforcementaction_bind$bulkoperations?: string | null;
  regardingobjectid_campaign_ts_serviceofenforcementaction_bind$campaigns?: string | null;
  regardingobjectid_campaignactivity_ts_serviceofenforcementaction_bind$campaignactivities?: string | null;
  regardingobjectid_contact_ts_serviceofenforcementaction_bind$contacts?: string | null;
  regardingobjectid_contract_ts_serviceofenforcementaction_bind$contracts?: string | null;
  regardingobjectid_entitlement_ts_serviceofenforcementaction_bind$entitlements?: string | null;
  regardingobjectid_entitlementtemplate_ts_serviceofenforcementaction_bind$entitlementtemplates?: string | null;
  regardingobjectid_ikl_a2d_securitytemplate_ts_serviceofenforcementaction_bind$ikl_a2d_securitytemplates?: string | null;
  regardingobjectid_ikl_bulkmigrationjob_ts_serviceofenforcementaction_bind$ikl_bulkmigrationjobs?: string | null;
  regardingobjectid_ikl_bulkmigrationjobstatus_ts_serviceofenforcementaction_bind$ikl_bulkmigrationjobstatuses?: string | null;
  regardingobjectid_ikl_inogiclicensedetails_ts_serviceofenforcementaction_bind$ikl_inogiclicensedetailses?: string | null;
  regardingobjectid_incident_ts_serviceofenforcementaction_bind$incidents?: string | null;
  regardingobjectid_invoice_ts_serviceofenforcementaction_bind$invoices?: string | null;
  regardingobjectid_knowledgearticle_ts_serviceofenforcementaction_bind$knowledgearticles?: string | null;
  regardingobjectid_knowledgebaserecord_ts_serviceofenforcementaction_bind$knowledgebaserecords?: string | null;
  regardingobjectid_lead_ts_serviceofenforcementaction_bind$leads?: string | null;
  regardingobjectid_msdyn_agreement_ts_serviceofenforcementaction_bind$msdyn_agreements?: string | null;
  regardingobjectid_msdyn_agreementbookingdate_ts_serviceofenforcementaction_bind$msdyn_agreementbookingdates?: string | null;
  regardingobjectid_msdyn_agreementbookingincident_ts_serviceofenforcementaction_bind$msdyn_agreementbookingincidents?: string | null;
  regardingobjectid_msdyn_agreementbookingproduct_ts_serviceofenforcementaction_bind$msdyn_agreementbookingproducts?: string | null;
  regardingobjectid_msdyn_agreementbookingservice_ts_serviceofenforcementaction_bind$msdyn_agreementbookingservices?: string | null;
  regardingobjectid_msdyn_agreementbookingservicetask_ts_serviceofenforcementaction_bind$msdyn_agreementbookingservicetasks?: string | null;
  regardingobjectid_msdyn_agreementbookingsetup_ts_serviceofenforcementaction_bind$msdyn_agreementbookingsetups?: string | null;
  regardingobjectid_msdyn_agreementinvoicedate_ts_serviceofenforcementaction_bind$msdyn_agreementinvoicedates?: string | null;
  regardingobjectid_msdyn_agreementinvoiceproduct_ts_serviceofenforcementaction_bind$msdyn_agreementinvoiceproducts?: string | null;
  regardingobjectid_msdyn_agreementinvoicesetup_ts_serviceofenforcementaction_bind$msdyn_agreementinvoicesetups?: string | null;
  regardingobjectid_msdyn_bookingalertstatus_ts_serviceofenforcementaction_bind$msdyn_bookingalertstatuses?: string | null;
  regardingobjectid_msdyn_bookingrule_ts_serviceofenforcementaction_bind$msdyn_bookingrules?: string | null;
  regardingobjectid_msdyn_bookingtimestamp_ts_serviceofenforcementaction_bind$msdyn_bookingtimestamps?: string | null;
  regardingobjectid_msdyn_customerasset_ts_serviceofenforcementaction_bind$msdyn_customerassets?: string | null;
  regardingobjectid_msdyn_fieldservicesetting_ts_serviceofenforcementaction_bind$msdyn_fieldservicesettings?: string | null;
  regardingobjectid_msdyn_incidenttypecharacteristic_ts_serviceofenforcementaction_bind$msdyn_incidenttypecharacteristics?: string | null;
  regardingobjectid_msdyn_incidenttypeproduct_ts_serviceofenforcementaction_bind$msdyn_incidenttypeproducts?: string | null;
  regardingobjectid_msdyn_incidenttypeservice_ts_serviceofenforcementaction_bind$msdyn_incidenttypeservices?: string | null;
  regardingobjectid_msdyn_inventoryadjustment_ts_serviceofenforcementaction_bind$msdyn_inventoryadjustments?: string | null;
  regardingobjectid_msdyn_inventoryadjustmentproduct_ts_serviceofenforcementaction_bind$msdyn_inventoryadjustmentproducts?: string | null;
  regardingobjectid_msdyn_inventoryjournal_ts_serviceofenforcementaction_bind$msdyn_inventoryjournals?: string | null;
  regardingobjectid_msdyn_inventorytransfer_ts_serviceofenforcementaction_bind$msdyn_inventorytransfers?: string | null;
  regardingobjectid_msdyn_payment_ts_serviceofenforcementaction_bind$msdyn_payments?: string | null;
  regardingobjectid_msdyn_paymentdetail_ts_serviceofenforcementaction_bind$msdyn_paymentdetailes?: string | null;
  regardingobjectid_msdyn_paymentmethod_ts_serviceofenforcementaction_bind$msdyn_paymentmethods?: string | null;
  regardingobjectid_msdyn_paymentterm_ts_serviceofenforcementaction_bind$msdyn_paymentterms?: string | null;
  regardingobjectid_msdyn_playbookinstance_ts_serviceofenforcementaction_bind$msdyn_playbookinstances?: string | null;
  regardingobjectid_msdyn_postalbum_ts_serviceofenforcementaction_bind$msdyn_postalbums?: string | null;
  regardingobjectid_msdyn_postalcode_ts_serviceofenforcementaction_bind$msdyn_postalcodes?: string | null;
  regardingobjectid_msdyn_productinventory_ts_serviceofenforcementaction_bind$msdyn_productinventories?: string | null;
  regardingobjectid_msdyn_purchaseorder_ts_serviceofenforcementaction_bind$msdyn_purchaseorders?: string | null;
  regardingobjectid_msdyn_purchaseorderbill_ts_serviceofenforcementaction_bind$msdyn_purchaseorderbills?: string | null;
  regardingobjectid_msdyn_purchaseorderproduct_ts_serviceofenforcementaction_bind$msdyn_purchaseorderproducts?: string | null;
  regardingobjectid_msdyn_purchaseorderreceipt_ts_serviceofenforcementaction_bind$msdyn_purchaseorderreceipts?: string | null;
  regardingobjectid_msdyn_purchaseorderreceiptproduct_ts_serviceofenforcementaction_bind$msdyn_purchaseorderreceiptproducts?: string | null;
  regardingobjectid_msdyn_purchaseordersubstatus_ts_serviceofenforcementaction_bind$msdyn_purchaseordersubstatuses?: string | null;
  regardingobjectid_msdyn_quotebookingincident_ts_serviceofenforcementaction_bind$msdyn_quotebookingincidents?: string | null;
  regardingobjectid_msdyn_quotebookingproduct_ts_serviceofenforcementaction_bind$msdyn_quotebookingproducts?: string | null;
  regardingobjectid_msdyn_quotebookingservice_ts_serviceofenforcementaction_bind$msdyn_quotebookingservices?: string | null;
  regardingobjectid_msdyn_quotebookingservicetask_ts_serviceofenforcementaction_bind$msdyn_quotebookingservicetasks?: string | null;
  regardingobjectid_msdyn_resourceterritory_ts_serviceofenforcementaction_bind$msdyn_resourceterritories?: string | null;
  regardingobjectid_msdyn_rma_ts_serviceofenforcementaction_bind$msdyn_rmas?: string | null;
  regardingobjectid_msdyn_rmaproduct_ts_serviceofenforcementaction_bind$msdyn_rmaproducts?: string | null;
  regardingobjectid_msdyn_rmareceipt_ts_serviceofenforcementaction_bind$msdyn_rmareceipts?: string | null;
  regardingobjectid_msdyn_rmareceiptproduct_ts_serviceofenforcementaction_bind$msdyn_rmareceiptproducts?: string | null;
  regardingobjectid_msdyn_rmasubstatus_ts_serviceofenforcementaction_bind$msdyn_rmasubstatuses?: string | null;
  regardingobjectid_msdyn_rtv_ts_serviceofenforcementaction_bind$msdyn_rtvs?: string | null;
  regardingobjectid_msdyn_rtvproduct_ts_serviceofenforcementaction_bind$msdyn_rtvproducts?: string | null;
  regardingobjectid_msdyn_rtvsubstatus_ts_serviceofenforcementaction_bind$msdyn_rtvsubstatuses?: string | null;
  regardingobjectid_msdyn_salessuggestion_ts_serviceofenforcementaction_bind$msdyn_salessuggestions?: string | null;
  regardingobjectid_msdyn_shipvia_ts_serviceofenforcementaction_bind$msdyn_shipvias?: string | null;
  regardingobjectid_msdyn_systemuserschedulersetting_ts_serviceofenforcementaction_bind$msdyn_systemuserschedulersettinges?: string | null;
  regardingobjectid_msdyn_timegroup_ts_serviceofenforcementaction_bind$msdyn_timegroups?: string | null;
  regardingobjectid_msdyn_timegroupdetail_ts_serviceofenforcementaction_bind$msdyn_timegroupdetails?: string | null;
  regardingobjectid_msdyn_timeoffrequest_ts_serviceofenforcementaction_bind$msdyn_timeoffrequests?: string | null;
  regardingobjectid_msdyn_warehouse_ts_serviceofenforcementaction_bind$msdyn_warehouses?: string | null;
  regardingobjectid_msdyn_workorder_ts_serviceofenforcementaction_bind$msdyn_workorders?: string | null;
  regardingobjectid_msdyn_workordercharacteristic_ts_serviceofenforcementaction_bind$msdyn_workordercharacteristics?: string | null;
  regardingobjectid_msdyn_workorderincident_ts_serviceofenforcementaction_bind$msdyn_workorderincidents?: string | null;
  regardingobjectid_msdyn_workorderproduct_ts_serviceofenforcementaction_bind$msdyn_workorderproducts?: string | null;
  regardingobjectid_msdyn_workorderresourcerestriction_ts_serviceofenforcementaction_bind$msdyn_workorderresourcerestrictions?: string | null;
  regardingobjectid_msdyn_workorderservice_ts_serviceofenforcementaction_bind$msdyn_workorderservices?: string | null;
  regardingobjectid_msdyn_workorderservicetask_ts_serviceofenforcementaction_bind$msdyn_workorderservicetasks?: string | null;
  regardingobjectid_new_interactionforemail_ts_serviceofenforcementaction_bind$interactionforemails?: string | null;
  regardingobjectid_opportunity_ts_serviceofenforcementaction_bind$opportunities?: string | null;
  regardingobjectid_ovs_operation_ts_serviceofenforcementaction_bind$ovs_operations?: string | null;
  regardingobjectid_ppp_traveller_ts_serviceofenforcementaction_bind$ppp_travellers?: string | null;
  regardingobjectid_quote_ts_serviceofenforcementaction_bind$quotes?: string | null;
  regardingobjectid_salesorder_ts_serviceofenforcementaction_bind$salesorders?: string | null;
  regardingobjectid_site_ts_serviceofenforcementaction_bind$sites?: string | null;
  regardingobjectid_ts_enforcementaction_ts_serviceofenforcementaction_bind$ts_enforcementactions?: string | null;
  regardingobjectid_ts_request_ts_serviceofenforcementaction_bind$ts_requests?: string | null;
  serviceid_ts_serviceofenforcementaction_bind$services?: string | null;
  sla_activitypointer_sla_ts_serviceofenforcementaction_bind$slas?: string | null;
  transactioncurrencyid_ts_serviceofenforcementaction_bind$transactioncurrencies?: string | null;
  ts_AuthorizedRepresentative_ts_serviceofenforcementaction_bind$contacts?: string | null;
  ts_IndividualCompany_ts_serviceofenforcementaction_bind$accounts?: string | null;
  ts_VerbalWarningGivenTo_ts_serviceofenforcementaction_bind$contacts?: string | null;
}
interface ts_serviceofenforcementaction_Create extends ts_serviceofenforcementaction {
  activityid_ts_serviceofenforcementaction_bind$activitypointers?: string | null;
}
interface ts_serviceofenforcementaction_Update extends ts_serviceofenforcementaction {
}
interface ts_serviceofenforcementaction_Select {
  activityadditionalparams: WebAttribute<ts_serviceofenforcementaction_Select, { activityadditionalparams: string | null }, {  }>;
  activityid: WebAttribute<ts_serviceofenforcementaction_Select, { activityid: string | null }, {  }>;
  activitytypecode: WebAttribute<ts_serviceofenforcementaction_Select, { activitytypecode: string | null }, {  }>;
  actualdurationminutes: WebAttribute<ts_serviceofenforcementaction_Select, { actualdurationminutes: number | null }, {  }>;
  actualend: WebAttribute<ts_serviceofenforcementaction_Select, { actualend: Date | null }, { actualend_formatted?: string }>;
  actualstart: WebAttribute<ts_serviceofenforcementaction_Select, { actualstart: Date | null }, { actualstart_formatted?: string }>;
  bcc_guid: WebAttribute<ts_serviceofenforcementaction_Select, { bcc_guid: string | null }, { bcc_formatted?: string }>;
  cc_guid: WebAttribute<ts_serviceofenforcementaction_Select, { cc_guid: string | null }, { cc_formatted?: string }>;
  community: WebAttribute<ts_serviceofenforcementaction_Select, { community: socialprofile_community | null }, { community_formatted?: string }>;
  createdby_guid: WebAttribute<ts_serviceofenforcementaction_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
  createdon: WebAttribute<ts_serviceofenforcementaction_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
  createdonbehalfby_guid: WebAttribute<ts_serviceofenforcementaction_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
  customers_guid: WebAttribute<ts_serviceofenforcementaction_Select, { customers_guid: string | null }, { customers_formatted?: string }>;
  deliverylastattemptedon: WebAttribute<ts_serviceofenforcementaction_Select, { deliverylastattemptedon: Date | null }, { deliverylastattemptedon_formatted?: string }>;
  deliveryprioritycode: WebAttribute<ts_serviceofenforcementaction_Select, { deliveryprioritycode: activitypointer_deliveryprioritycode | null }, { deliveryprioritycode_formatted?: string }>;
  description: WebAttribute<ts_serviceofenforcementaction_Select, { description: string | null }, {  }>;
  exchangeitemid: WebAttribute<ts_serviceofenforcementaction_Select, { exchangeitemid: string | null }, {  }>;
  exchangerate: WebAttribute<ts_serviceofenforcementaction_Select, { exchangerate: number | null }, {  }>;
  exchangeweblink: WebAttribute<ts_serviceofenforcementaction_Select, { exchangeweblink: string | null }, {  }>;
  from_guid: WebAttribute<ts_serviceofenforcementaction_Select, { from_guid: string | null }, { from_formatted?: string }>;
  importsequencenumber: WebAttribute<ts_serviceofenforcementaction_Select, { importsequencenumber: number | null }, {  }>;
  instancetypecode: WebAttribute<ts_serviceofenforcementaction_Select, { instancetypecode: ts_serviceofenforcementaction_instancetypecode | null }, { instancetypecode_formatted?: string }>;
  isbilled: WebAttribute<ts_serviceofenforcementaction_Select, { isbilled: boolean | null }, {  }>;
  ismapiprivate: WebAttribute<ts_serviceofenforcementaction_Select, { ismapiprivate: boolean | null }, {  }>;
  isregularactivity: WebAttribute<ts_serviceofenforcementaction_Select, { isregularactivity: boolean | null }, {  }>;
  isworkflowcreated: WebAttribute<ts_serviceofenforcementaction_Select, { isworkflowcreated: boolean | null }, {  }>;
  lastonholdtime: WebAttribute<ts_serviceofenforcementaction_Select, { lastonholdtime: Date | null }, { lastonholdtime_formatted?: string }>;
  leftvoicemail: WebAttribute<ts_serviceofenforcementaction_Select, { leftvoicemail: boolean | null }, {  }>;
  modifiedby_guid: WebAttribute<ts_serviceofenforcementaction_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
  modifiedon: WebAttribute<ts_serviceofenforcementaction_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
  modifiedonbehalfby_guid: WebAttribute<ts_serviceofenforcementaction_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
  onholdtime: WebAttribute<ts_serviceofenforcementaction_Select, { onholdtime: number | null }, {  }>;
  optionalattendees_guid: WebAttribute<ts_serviceofenforcementaction_Select, { optionalattendees_guid: string | null }, { optionalattendees_formatted?: string }>;
  organizer_guid: WebAttribute<ts_serviceofenforcementaction_Select, { organizer_guid: string | null }, { organizer_formatted?: string }>;
  overriddencreatedon: WebAttribute<ts_serviceofenforcementaction_Select, { overriddencreatedon: Date | null }, { overriddencreatedon_formatted?: string }>;
  ownerid_guid: WebAttribute<ts_serviceofenforcementaction_Select, { ownerid_guid: string | null }, { ownerid_formatted?: string }>;
  owningbusinessunit_guid: WebAttribute<ts_serviceofenforcementaction_Select, { owningbusinessunit_guid: string | null }, { owningbusinessunit_formatted?: string }>;
  owningteam_guid: WebAttribute<ts_serviceofenforcementaction_Select, { owningteam_guid: string | null }, { owningteam_formatted?: string }>;
  owninguser_guid: WebAttribute<ts_serviceofenforcementaction_Select, { owninguser_guid: string | null }, { owninguser_formatted?: string }>;
  partners_guid: WebAttribute<ts_serviceofenforcementaction_Select, { partners_guid: string | null }, { partners_formatted?: string }>;
  postponeactivityprocessinguntil: WebAttribute<ts_serviceofenforcementaction_Select, { postponeactivityprocessinguntil: Date | null }, { postponeactivityprocessinguntil_formatted?: string }>;
  prioritycode: WebAttribute<ts_serviceofenforcementaction_Select, { prioritycode: ts_serviceofenforcementaction_prioritycode | null }, { prioritycode_formatted?: string }>;
  processid: WebAttribute<ts_serviceofenforcementaction_Select, { processid: string | null }, {  }>;
  regardingobjectid_guid: WebAttribute<ts_serviceofenforcementaction_Select, { regardingobjectid_guid: string | null }, { regardingobjectid_formatted?: string }>;
  requiredattendees_guid: WebAttribute<ts_serviceofenforcementaction_Select, { requiredattendees_guid: string | null }, { requiredattendees_formatted?: string }>;
  resources_guid: WebAttribute<ts_serviceofenforcementaction_Select, { resources_guid: string | null }, { resources_formatted?: string }>;
  scheduleddurationminutes: WebAttribute<ts_serviceofenforcementaction_Select, { scheduleddurationminutes: number | null }, {  }>;
  scheduledend: WebAttribute<ts_serviceofenforcementaction_Select, { scheduledend: Date | null }, { scheduledend_formatted?: string }>;
  scheduledstart: WebAttribute<ts_serviceofenforcementaction_Select, { scheduledstart: Date | null }, { scheduledstart_formatted?: string }>;
  sendermailboxid_guid: WebAttribute<ts_serviceofenforcementaction_Select, { sendermailboxid_guid: string | null }, { sendermailboxid_formatted?: string }>;
  senton: WebAttribute<ts_serviceofenforcementaction_Select, { senton: Date | null }, { senton_formatted?: string }>;
  seriesid: WebAttribute<ts_serviceofenforcementaction_Select, { seriesid: string | null }, {  }>;
  serviceid_guid: WebAttribute<ts_serviceofenforcementaction_Select, { serviceid_guid: string | null }, { serviceid_formatted?: string }>;
  slaid_guid: WebAttribute<ts_serviceofenforcementaction_Select, { slaid_guid: string | null }, { slaid_formatted?: string }>;
  slainvokedid_guid: WebAttribute<ts_serviceofenforcementaction_Select, { slainvokedid_guid: string | null }, { slainvokedid_formatted?: string }>;
  sortdate: WebAttribute<ts_serviceofenforcementaction_Select, { sortdate: Date | null }, { sortdate_formatted?: string }>;
  stageid: WebAttribute<ts_serviceofenforcementaction_Select, { stageid: string | null }, {  }>;
  statecode: WebAttribute<ts_serviceofenforcementaction_Select, { statecode: ts_serviceofenforcementaction_statecode | null }, { statecode_formatted?: string }>;
  statuscode: WebAttribute<ts_serviceofenforcementaction_Select, { statuscode: ts_serviceofenforcementaction_statuscode | null }, { statuscode_formatted?: string }>;
  subject: WebAttribute<ts_serviceofenforcementaction_Select, { subject: string | null }, {  }>;
  timezoneruleversionnumber: WebAttribute<ts_serviceofenforcementaction_Select, { timezoneruleversionnumber: number | null }, {  }>;
  to_guid: WebAttribute<ts_serviceofenforcementaction_Select, { to_guid: string | null }, { to_formatted?: string }>;
  transactioncurrencyid_guid: WebAttribute<ts_serviceofenforcementaction_Select, { transactioncurrencyid_guid: string | null }, { transactioncurrencyid_formatted?: string }>;
  traversedpath: WebAttribute<ts_serviceofenforcementaction_Select, { traversedpath: string | null }, {  }>;
  ts_authorizedrepresentative_guid: WebAttribute<ts_serviceofenforcementaction_Select, { ts_authorizedrepresentative_guid: string | null }, { ts_authorizedrepresentative_formatted?: string }>;
  ts_comments: WebAttribute<ts_serviceofenforcementaction_Select, { ts_comments: string | null }, {  }>;
  ts_copyofreceiptifapplicable: WebAttribute<ts_serviceofenforcementaction_Select, { ts_copyofreceiptifapplicable: string | null }, {  }>;
  ts_individualcompany_guid: WebAttribute<ts_serviceofenforcementaction_Select, { ts_individualcompany_guid: string | null }, { ts_individualcompany_formatted?: string }>;
  ts_individualposition: WebAttribute<ts_serviceofenforcementaction_Select, { ts_individualposition: string | null }, {  }>;
  ts_methodofservice: WebAttribute<ts_serviceofenforcementaction_Select, { ts_methodofservice: ts_methodofservice | null }, { ts_methodofservice_formatted?: string }>;
  ts_timeanddateofservice: WebAttribute<ts_serviceofenforcementaction_Select, { ts_timeanddateofservice: Date | null }, { ts_timeanddateofservice_formatted?: string }>;
  ts_verbalwarningdate: WebAttribute<ts_serviceofenforcementaction_Select, { ts_verbalwarningdate: Date | null }, { ts_verbalwarningdate_formatted?: string }>;
  ts_verbalwarninggivento_guid: WebAttribute<ts_serviceofenforcementaction_Select, { ts_verbalwarninggivento_guid: string | null }, { ts_verbalwarninggivento_formatted?: string }>;
  ts_verbalwarningwhere: WebAttribute<ts_serviceofenforcementaction_Select, { ts_verbalwarningwhere: ts_verbalwarninglocation | null }, { ts_verbalwarningwhere_formatted?: string }>;
  ts_verbalwarningwhereother: WebAttribute<ts_serviceofenforcementaction_Select, { ts_verbalwarningwhereother: string | null }, {  }>;
  utcconversiontimezonecode: WebAttribute<ts_serviceofenforcementaction_Select, { utcconversiontimezonecode: number | null }, {  }>;
  versionnumber: WebAttribute<ts_serviceofenforcementaction_Select, { versionnumber: number | null }, {  }>;
}
interface ts_serviceofenforcementaction_Filter {
  activityadditionalparams: string;
  activityid: XQW.Guid;
  activitytypecode: string;
  actualdurationminutes: number;
  actualend: Date;
  actualstart: Date;
  bcc_guid: XQW.Guid;
  cc_guid: XQW.Guid;
  community: socialprofile_community;
  createdby_guid: XQW.Guid;
  createdon: Date;
  createdonbehalfby_guid: XQW.Guid;
  customers_guid: XQW.Guid;
  deliverylastattemptedon: Date;
  deliveryprioritycode: activitypointer_deliveryprioritycode;
  description: string;
  exchangeitemid: string;
  exchangerate: any;
  exchangeweblink: string;
  from_guid: XQW.Guid;
  importsequencenumber: number;
  instancetypecode: ts_serviceofenforcementaction_instancetypecode;
  isbilled: boolean;
  ismapiprivate: boolean;
  isregularactivity: boolean;
  isworkflowcreated: boolean;
  lastonholdtime: Date;
  leftvoicemail: boolean;
  modifiedby_guid: XQW.Guid;
  modifiedon: Date;
  modifiedonbehalfby_guid: XQW.Guid;
  onholdtime: number;
  optionalattendees_guid: XQW.Guid;
  organizer_guid: XQW.Guid;
  overriddencreatedon: Date;
  ownerid_guid: XQW.Guid;
  owningbusinessunit_guid: XQW.Guid;
  owningteam_guid: XQW.Guid;
  owninguser_guid: XQW.Guid;
  partners_guid: XQW.Guid;
  postponeactivityprocessinguntil: Date;
  prioritycode: ts_serviceofenforcementaction_prioritycode;
  processid: XQW.Guid;
  regardingobjectid_guid: XQW.Guid;
  requiredattendees_guid: XQW.Guid;
  resources_guid: XQW.Guid;
  scheduleddurationminutes: number;
  scheduledend: Date;
  scheduledstart: Date;
  sendermailboxid_guid: XQW.Guid;
  senton: Date;
  seriesid: XQW.Guid;
  serviceid_guid: XQW.Guid;
  slaid_guid: XQW.Guid;
  slainvokedid_guid: XQW.Guid;
  sortdate: Date;
  stageid: XQW.Guid;
  statecode: ts_serviceofenforcementaction_statecode;
  statuscode: ts_serviceofenforcementaction_statuscode;
  subject: string;
  timezoneruleversionnumber: number;
  to_guid: XQW.Guid;
  transactioncurrencyid_guid: XQW.Guid;
  traversedpath: string;
  ts_authorizedrepresentative_guid: XQW.Guid;
  ts_comments: string;
  ts_copyofreceiptifapplicable: string;
  ts_individualcompany_guid: XQW.Guid;
  ts_individualposition: string;
  ts_methodofservice: ts_methodofservice;
  ts_timeanddateofservice: Date;
  ts_verbalwarningdate: Date;
  ts_verbalwarninggivento_guid: XQW.Guid;
  ts_verbalwarningwhere: ts_verbalwarninglocation;
  ts_verbalwarningwhereother: string;
  utcconversiontimezonecode: number;
  versionnumber: number;
}
interface ts_serviceofenforcementaction_Expand {
  createdby_ts_serviceofenforcementaction: WebExpand<ts_serviceofenforcementaction_Expand, SystemUser_Select, SystemUser_Filter, { createdby_ts_serviceofenforcementaction: SystemUser_Result }>;
  createdonbehalfby_ts_serviceofenforcementaction: WebExpand<ts_serviceofenforcementaction_Expand, SystemUser_Select, SystemUser_Filter, { createdonbehalfby_ts_serviceofenforcementaction: SystemUser_Result }>;
  modifiedby_ts_serviceofenforcementaction: WebExpand<ts_serviceofenforcementaction_Expand, SystemUser_Select, SystemUser_Filter, { modifiedby_ts_serviceofenforcementaction: SystemUser_Result }>;
  modifiedonbehalfby_ts_serviceofenforcementaction: WebExpand<ts_serviceofenforcementaction_Expand, SystemUser_Select, SystemUser_Filter, { modifiedonbehalfby_ts_serviceofenforcementaction: SystemUser_Result }>;
  ownerid_ts_serviceofenforcementaction: WebExpand<ts_serviceofenforcementaction_Expand, SystemUser_Select, SystemUser_Filter, { ownerid_ts_serviceofenforcementaction: SystemUser_Result }>;
  owninguser_ts_serviceofenforcementaction: WebExpand<ts_serviceofenforcementaction_Expand, SystemUser_Select, SystemUser_Filter, { owninguser_ts_serviceofenforcementaction: SystemUser_Result }>;
  regardingobjectid_account_ts_serviceofenforcementaction: WebExpand<ts_serviceofenforcementaction_Expand, Account_Select, Account_Filter, { regardingobjectid_account_ts_serviceofenforcementaction: Account_Result }>;
  regardingobjectid_bookableresourcebooking_ts_serviceofenforcementaction: WebExpand<ts_serviceofenforcementaction_Expand, BookableResourceBooking_Select, BookableResourceBooking_Filter, { regardingobjectid_bookableresourcebooking_ts_serviceofenforcementaction: BookableResourceBooking_Result }>;
  regardingobjectid_contact_ts_serviceofenforcementaction: WebExpand<ts_serviceofenforcementaction_Expand, Contact_Select, Contact_Filter, { regardingobjectid_contact_ts_serviceofenforcementaction: Contact_Result }>;
  regardingobjectid_incident_ts_serviceofenforcementaction: WebExpand<ts_serviceofenforcementaction_Expand, Incident_Select, Incident_Filter, { regardingobjectid_incident_ts_serviceofenforcementaction: Incident_Result }>;
  regardingobjectid_msdyn_customerasset_ts_serviceofenforcementaction: WebExpand<ts_serviceofenforcementaction_Expand, msdyn_customerasset_Select, msdyn_customerasset_Filter, { regardingobjectid_msdyn_customerasset_ts_serviceofenforcementaction: msdyn_customerasset_Result }>;
  regardingobjectid_msdyn_workorder_ts_serviceofenforcementaction: WebExpand<ts_serviceofenforcementaction_Expand, msdyn_workorder_Select, msdyn_workorder_Filter, { regardingobjectid_msdyn_workorder_ts_serviceofenforcementaction: msdyn_workorder_Result }>;
  regardingobjectid_msdyn_workorderservicetask_ts_serviceofenforcementaction: WebExpand<ts_serviceofenforcementaction_Expand, msdyn_workorderservicetask_Select, msdyn_workorderservicetask_Filter, { regardingobjectid_msdyn_workorderservicetask_ts_serviceofenforcementaction: msdyn_workorderservicetask_Result }>;
  regardingobjectid_ovs_operation_ts_serviceofenforcementaction: WebExpand<ts_serviceofenforcementaction_Expand, ovs_operation_Select, ovs_operation_Filter, { regardingobjectid_ovs_operation_ts_serviceofenforcementaction: ovs_operation_Result }>;
  regardingobjectid_ts_enforcementaction_ts_serviceofenforcementaction: WebExpand<ts_serviceofenforcementaction_Expand, ts_EnforcementAction_Select, ts_EnforcementAction_Filter, { regardingobjectid_ts_enforcementaction_ts_serviceofenforcementaction: ts_EnforcementAction_Result }>;
  ts_AuthorizedRepresentative_ts_serviceofenforcementaction: WebExpand<ts_serviceofenforcementaction_Expand, Contact_Select, Contact_Filter, { ts_AuthorizedRepresentative_ts_serviceofenforcementaction: Contact_Result }>;
  ts_IndividualCompany_ts_serviceofenforcementaction: WebExpand<ts_serviceofenforcementaction_Expand, Account_Select, Account_Filter, { ts_IndividualCompany_ts_serviceofenforcementaction: Account_Result }>;
  ts_VerbalWarningGivenTo_ts_serviceofenforcementaction: WebExpand<ts_serviceofenforcementaction_Expand, Contact_Select, Contact_Filter, { ts_VerbalWarningGivenTo_ts_serviceofenforcementaction: Contact_Result }>;
  ts_serviceofenforcementaction_activity_parties: WebExpand<ts_serviceofenforcementaction_Expand, ActivityParty_Select, ActivityParty_Filter, { ts_serviceofenforcementaction_activity_parties: ActivityParty_Result[] }>;
  ts_serviceofenforcementaction_connections1: WebExpand<ts_serviceofenforcementaction_Expand, Connection_Select, Connection_Filter, { ts_serviceofenforcementaction_connections1: Connection_Result[] }>;
  ts_serviceofenforcementaction_connections2: WebExpand<ts_serviceofenforcementaction_Expand, Connection_Select, Connection_Filter, { ts_serviceofenforcementaction_connections2: Connection_Result[] }>;
}
interface ts_serviceofenforcementaction_FormattedResult {
  actualend_formatted?: string;
  actualstart_formatted?: string;
  bcc_formatted?: string;
  cc_formatted?: string;
  community_formatted?: string;
  createdby_formatted?: string;
  createdon_formatted?: string;
  createdonbehalfby_formatted?: string;
  customers_formatted?: string;
  deliverylastattemptedon_formatted?: string;
  deliveryprioritycode_formatted?: string;
  from_formatted?: string;
  instancetypecode_formatted?: string;
  lastonholdtime_formatted?: string;
  modifiedby_formatted?: string;
  modifiedon_formatted?: string;
  modifiedonbehalfby_formatted?: string;
  optionalattendees_formatted?: string;
  organizer_formatted?: string;
  overriddencreatedon_formatted?: string;
  ownerid_formatted?: string;
  owningbusinessunit_formatted?: string;
  owningteam_formatted?: string;
  owninguser_formatted?: string;
  partners_formatted?: string;
  postponeactivityprocessinguntil_formatted?: string;
  prioritycode_formatted?: string;
  regardingobjectid_formatted?: string;
  requiredattendees_formatted?: string;
  resources_formatted?: string;
  scheduledend_formatted?: string;
  scheduledstart_formatted?: string;
  sendermailboxid_formatted?: string;
  senton_formatted?: string;
  serviceid_formatted?: string;
  slaid_formatted?: string;
  slainvokedid_formatted?: string;
  sortdate_formatted?: string;
  statecode_formatted?: string;
  statuscode_formatted?: string;
  to_formatted?: string;
  transactioncurrencyid_formatted?: string;
  ts_authorizedrepresentative_formatted?: string;
  ts_individualcompany_formatted?: string;
  ts_methodofservice_formatted?: string;
  ts_timeanddateofservice_formatted?: string;
  ts_verbalwarningdate_formatted?: string;
  ts_verbalwarninggivento_formatted?: string;
  ts_verbalwarningwhere_formatted?: string;
}
interface ts_serviceofenforcementaction_Result extends ts_serviceofenforcementaction_Base, ts_serviceofenforcementaction_Relationships {
  "@odata.etag": string;
  bcc_guid: string | null;
  cc_guid: string | null;
  createdby_guid: string | null;
  createdonbehalfby_guid: string | null;
  customers_guid: string | null;
  from_guid: string | null;
  modifiedby_guid: string | null;
  modifiedonbehalfby_guid: string | null;
  optionalattendees_guid: string | null;
  organizer_guid: string | null;
  ownerid_guid: string | null;
  owningbusinessunit_guid: string | null;
  owningteam_guid: string | null;
  owninguser_guid: string | null;
  partners_guid: string | null;
  regardingobjectid_guid: string | null;
  requiredattendees_guid: string | null;
  resources_guid: string | null;
  sendermailboxid_guid: string | null;
  serviceid_guid: string | null;
  slaid_guid: string | null;
  slainvokedid_guid: string | null;
  to_guid: string | null;
  transactioncurrencyid_guid: string | null;
  ts_authorizedrepresentative_guid: string | null;
  ts_individualcompany_guid: string | null;
  ts_verbalwarninggivento_guid: string | null;
}
interface ts_serviceofenforcementaction_RelatedOne {
  createdby_ts_serviceofenforcementaction: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  createdonbehalfby_ts_serviceofenforcementaction: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedby_ts_serviceofenforcementaction: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedonbehalfby_ts_serviceofenforcementaction: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  ownerid_ts_serviceofenforcementaction: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  owninguser_ts_serviceofenforcementaction: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  regardingobjectid_account_ts_serviceofenforcementaction: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  regardingobjectid_bookableresourcebooking_ts_serviceofenforcementaction: WebMappingRetrieve<BookableResourceBooking_Select,BookableResourceBooking_Expand,BookableResourceBooking_Filter,BookableResourceBooking_Fixed,BookableResourceBooking_Result,BookableResourceBooking_FormattedResult>;
  regardingobjectid_contact_ts_serviceofenforcementaction: WebMappingRetrieve<Contact_Select,Contact_Expand,Contact_Filter,Contact_Fixed,Contact_Result,Contact_FormattedResult>;
  regardingobjectid_incident_ts_serviceofenforcementaction: WebMappingRetrieve<Incident_Select,Incident_Expand,Incident_Filter,Incident_Fixed,Incident_Result,Incident_FormattedResult>;
  regardingobjectid_msdyn_customerasset_ts_serviceofenforcementaction: WebMappingRetrieve<msdyn_customerasset_Select,msdyn_customerasset_Expand,msdyn_customerasset_Filter,msdyn_customerasset_Fixed,msdyn_customerasset_Result,msdyn_customerasset_FormattedResult>;
  regardingobjectid_msdyn_workorder_ts_serviceofenforcementaction: WebMappingRetrieve<msdyn_workorder_Select,msdyn_workorder_Expand,msdyn_workorder_Filter,msdyn_workorder_Fixed,msdyn_workorder_Result,msdyn_workorder_FormattedResult>;
  regardingobjectid_msdyn_workorderservicetask_ts_serviceofenforcementaction: WebMappingRetrieve<msdyn_workorderservicetask_Select,msdyn_workorderservicetask_Expand,msdyn_workorderservicetask_Filter,msdyn_workorderservicetask_Fixed,msdyn_workorderservicetask_Result,msdyn_workorderservicetask_FormattedResult>;
  regardingobjectid_ovs_operation_ts_serviceofenforcementaction: WebMappingRetrieve<ovs_operation_Select,ovs_operation_Expand,ovs_operation_Filter,ovs_operation_Fixed,ovs_operation_Result,ovs_operation_FormattedResult>;
  regardingobjectid_ts_enforcementaction_ts_serviceofenforcementaction: WebMappingRetrieve<ts_EnforcementAction_Select,ts_EnforcementAction_Expand,ts_EnforcementAction_Filter,ts_EnforcementAction_Fixed,ts_EnforcementAction_Result,ts_EnforcementAction_FormattedResult>;
  ts_AuthorizedRepresentative_ts_serviceofenforcementaction: WebMappingRetrieve<Contact_Select,Contact_Expand,Contact_Filter,Contact_Fixed,Contact_Result,Contact_FormattedResult>;
  ts_IndividualCompany_ts_serviceofenforcementaction: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  ts_VerbalWarningGivenTo_ts_serviceofenforcementaction: WebMappingRetrieve<Contact_Select,Contact_Expand,Contact_Filter,Contact_Fixed,Contact_Result,Contact_FormattedResult>;
}
interface ts_serviceofenforcementaction_RelatedMany {
  ts_serviceofenforcementaction_activity_parties: WebMappingRetrieve<ActivityParty_Select,ActivityParty_Expand,ActivityParty_Filter,ActivityParty_Fixed,ActivityParty_Result,ActivityParty_FormattedResult>;
  ts_serviceofenforcementaction_connections1: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  ts_serviceofenforcementaction_connections2: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
}
interface WebEntitiesRetrieve {
  ts_serviceofenforcementactions: WebMappingRetrieve<ts_serviceofenforcementaction_Select,ts_serviceofenforcementaction_Expand,ts_serviceofenforcementaction_Filter,ts_serviceofenforcementaction_Fixed,ts_serviceofenforcementaction_Result,ts_serviceofenforcementaction_FormattedResult>;
}
interface WebEntitiesRelated {
  ts_serviceofenforcementactions: WebMappingRelated<ts_serviceofenforcementaction_RelatedOne,ts_serviceofenforcementaction_RelatedMany>;
}
interface WebEntitiesCUDA {
  ts_serviceofenforcementactions: WebMappingCUDA<ts_serviceofenforcementaction_Create,ts_serviceofenforcementaction_Update,ts_serviceofenforcementaction_Select>;
}
