declare namespace Form.systemuser.Main {
  namespace Information {
    namespace Tabs {
      interface addresses extends Xrm.SectionCollectionBase {
        get(name: "address preference"): Xrm.PageSection;
        get(name: "mailing address"): Xrm.PageSection;
        get(name: "other address"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface general extends Xrm.SectionCollectionBase {
        get(name: "administration"): Xrm.PageSection;
        get(name: "email configuration"): Xrm.PageSection;
        get(name: "online account information"): Xrm.PageSection;
        get(name: "onpremise account information"): Xrm.PageSection;
        get(name: "organization information"): Xrm.PageSection;
        get(name: "queue selection"): Xrm.PageSection;
        get(name: "user information"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface tab_recordwall extends Xrm.SectionCollectionBase {
        get(name: "tab_recordwall_section_1"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
    }
    interface Attributes extends Xrm.AttributeCollectionBase {
      get(name: "accessmode"): Xrm.OptionSetAttribute<systemuser_accessmode>;
      get(name: "address1_city"): Xrm.Attribute<string>;
      get(name: "address1_country"): Xrm.Attribute<string>;
      get(name: "address1_fax"): Xrm.Attribute<string>;
      get(name: "address1_line1"): Xrm.Attribute<string>;
      get(name: "address1_line2"): Xrm.Attribute<string>;
      get(name: "address1_line3"): Xrm.Attribute<string>;
      get(name: "address1_postalcode"): Xrm.Attribute<string>;
      get(name: "address1_stateorprovince"): Xrm.Attribute<string>;
      get(name: "address1_telephone1"): Xrm.Attribute<string>;
      get(name: "address1_telephone2"): Xrm.Attribute<string>;
      get(name: "address1_telephone3"): Xrm.Attribute<string>;
      get(name: "address2_city"): Xrm.Attribute<string>;
      get(name: "address2_country"): Xrm.Attribute<string>;
      get(name: "address2_line1"): Xrm.Attribute<string>;
      get(name: "address2_line2"): Xrm.Attribute<string>;
      get(name: "address2_line3"): Xrm.Attribute<string>;
      get(name: "address2_postalcode"): Xrm.Attribute<string>;
      get(name: "address2_stateorprovince"): Xrm.Attribute<string>;
      get(name: "businessunitid"): Xrm.LookupAttribute<"businessunit">;
      get(name: "caltype"): Xrm.OptionSetAttribute<systemuser_caltype>;
      get(name: "defaultmailbox"): Xrm.LookupAttribute<"mailbox">;
      get(name: "domainname"): Xrm.Attribute<string>;
      get(name: "firstname"): Xrm.Attribute<string>;
      get(name: "homephone"): Xrm.Attribute<string>;
      get(name: "internalemailaddress"): Xrm.Attribute<string>;
      get(name: "invitestatuscode"): Xrm.OptionSetAttribute<systemuser_invitestatuscode>;
      get(name: "isdisabled"): Xrm.OptionSetAttribute<boolean>;
      get(name: "lastname"): Xrm.Attribute<string>;
      get(name: "mobilealertemail"): Xrm.Attribute<string>;
      get(name: "mobilephone"): Xrm.Attribute<string>;
      get(name: "parentsystemuserid"): Xrm.LookupAttribute<"systemuser">;
      get(name: "personalemailaddress"): Xrm.Attribute<string>;
      get(name: "positionid"): Xrm.LookupAttribute<"position">;
      get(name: "preferredaddresscode"): Xrm.OptionSetAttribute<systemuser_preferredaddresscode>;
      get(name: "preferredphonecode"): Xrm.OptionSetAttribute<systemuser_preferredphonecode>;
      get(name: "queueid"): Xrm.LookupAttribute<"queue">;
      get(name: "siteid"): Xrm.LookupAttribute<"site">;
      get(name: "territoryid"): Xrm.LookupAttribute<"territory">;
      get(name: "title"): Xrm.Attribute<string>;
      get(name: "windowsliveid"): Xrm.Attribute<string>;
      get(name: string): undefined;
      get(): Xrm.Attribute<any>[];
      get(index: number): Xrm.Attribute<any>;
      get(chooser: (item: Xrm.Attribute<any>, index: number) => boolean): Xrm.Attribute<any>[];
    }
    interface Controls extends Xrm.ControlCollectionBase {
      get(name: "WebResource_RecordWall"): Xrm.WebResourceControl;
      get(name: "accessmode"): Xrm.OptionSetControl<systemuser_accessmode>;
      get(name: "address1_city"): Xrm.StringControl;
      get(name: "address1_country"): Xrm.StringControl;
      get(name: "address1_fax"): Xrm.StringControl;
      get(name: "address1_line1"): Xrm.StringControl;
      get(name: "address1_line2"): Xrm.StringControl;
      get(name: "address1_line3"): Xrm.StringControl;
      get(name: "address1_postalcode"): Xrm.StringControl;
      get(name: "address1_stateorprovince"): Xrm.StringControl;
      get(name: "address1_telephone1"): Xrm.StringControl;
      get(name: "address1_telephone2"): Xrm.StringControl;
      get(name: "address1_telephone3"): Xrm.StringControl;
      get(name: "address2_city"): Xrm.StringControl;
      get(name: "address2_country"): Xrm.StringControl;
      get(name: "address2_line1"): Xrm.StringControl;
      get(name: "address2_line2"): Xrm.StringControl;
      get(name: "address2_line3"): Xrm.StringControl;
      get(name: "address2_postalcode"): Xrm.StringControl;
      get(name: "address2_stateorprovince"): Xrm.StringControl;
      get(name: "businessunitid"): Xrm.LookupControl<"businessunit">;
      get(name: "caltype"): Xrm.OptionSetControl<systemuser_caltype>;
      get(name: "defaultmailbox"): Xrm.LookupControl<"mailbox">;
      get(name: "domainname"): Xrm.StringControl;
      get(name: "firstname"): Xrm.StringControl;
      get(name: "footer_isdisabled"): Xrm.OptionSetControl<boolean>;
      get(name: "homephone"): Xrm.StringControl;
      get(name: "internalemailaddress"): Xrm.StringControl;
      get(name: "invitestatuscode"): Xrm.OptionSetControl<systemuser_invitestatuscode>;
      get(name: "lastname"): Xrm.StringControl;
      get(name: "mobilealertemail"): Xrm.StringControl;
      get(name: "mobilephone"): Xrm.StringControl;
      get(name: "parentsystemuserid"): Xrm.LookupControl<"systemuser">;
      get(name: "personalemailaddress"): Xrm.StringControl;
      get(name: "positionid"): Xrm.LookupControl<"position">;
      get(name: "preferredaddresscode"): Xrm.OptionSetControl<systemuser_preferredaddresscode>;
      get(name: "preferredphonecode"): Xrm.OptionSetControl<systemuser_preferredphonecode>;
      get(name: "queueid"): Xrm.LookupControl<"queue">;
      get(name: "siteid"): Xrm.LookupControl<"site">;
      get(name: "territoryid"): Xrm.LookupControl<"territory">;
      get(name: "title"): Xrm.StringControl;
      get(name: "windowsliveid"): Xrm.StringControl;
      get(name: string): undefined;
      get(): Xrm.BaseControl[];
      get(index: number): Xrm.BaseControl;
      get(chooser: (item: Xrm.BaseControl, index: number) => boolean): Xrm.BaseControl[];
    }
    interface Tabs extends Xrm.TabCollectionBase {
      get(name: "addresses"): Xrm.PageTab<Tabs.addresses>;
      get(name: "general"): Xrm.PageTab<Tabs.general>;
      get(name: "tab_recordwall"): Xrm.PageTab<Tabs.tab_recordwall>;
      get(name: string): undefined;
      get(): Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>[];
      get(index: number): Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>;
      get(chooser: (item: Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>, index: number) => boolean): Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>[];
    }
  }
  interface Information extends Xrm.PageBase<Information.Attributes,Information.Tabs,Information.Controls> {
    getAttribute(attributeName: "accessmode"): Xrm.OptionSetAttribute<systemuser_accessmode>;
    getAttribute(attributeName: "address1_city"): Xrm.Attribute<string>;
    getAttribute(attributeName: "address1_country"): Xrm.Attribute<string>;
    getAttribute(attributeName: "address1_fax"): Xrm.Attribute<string>;
    getAttribute(attributeName: "address1_line1"): Xrm.Attribute<string>;
    getAttribute(attributeName: "address1_line2"): Xrm.Attribute<string>;
    getAttribute(attributeName: "address1_line3"): Xrm.Attribute<string>;
    getAttribute(attributeName: "address1_postalcode"): Xrm.Attribute<string>;
    getAttribute(attributeName: "address1_stateorprovince"): Xrm.Attribute<string>;
    getAttribute(attributeName: "address1_telephone1"): Xrm.Attribute<string>;
    getAttribute(attributeName: "address1_telephone2"): Xrm.Attribute<string>;
    getAttribute(attributeName: "address1_telephone3"): Xrm.Attribute<string>;
    getAttribute(attributeName: "address2_city"): Xrm.Attribute<string>;
    getAttribute(attributeName: "address2_country"): Xrm.Attribute<string>;
    getAttribute(attributeName: "address2_line1"): Xrm.Attribute<string>;
    getAttribute(attributeName: "address2_line2"): Xrm.Attribute<string>;
    getAttribute(attributeName: "address2_line3"): Xrm.Attribute<string>;
    getAttribute(attributeName: "address2_postalcode"): Xrm.Attribute<string>;
    getAttribute(attributeName: "address2_stateorprovince"): Xrm.Attribute<string>;
    getAttribute(attributeName: "businessunitid"): Xrm.LookupAttribute<"businessunit">;
    getAttribute(attributeName: "caltype"): Xrm.OptionSetAttribute<systemuser_caltype>;
    getAttribute(attributeName: "defaultmailbox"): Xrm.LookupAttribute<"mailbox">;
    getAttribute(attributeName: "domainname"): Xrm.Attribute<string>;
    getAttribute(attributeName: "firstname"): Xrm.Attribute<string>;
    getAttribute(attributeName: "homephone"): Xrm.Attribute<string>;
    getAttribute(attributeName: "internalemailaddress"): Xrm.Attribute<string>;
    getAttribute(attributeName: "invitestatuscode"): Xrm.OptionSetAttribute<systemuser_invitestatuscode>;
    getAttribute(attributeName: "isdisabled"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "lastname"): Xrm.Attribute<string>;
    getAttribute(attributeName: "mobilealertemail"): Xrm.Attribute<string>;
    getAttribute(attributeName: "mobilephone"): Xrm.Attribute<string>;
    getAttribute(attributeName: "parentsystemuserid"): Xrm.LookupAttribute<"systemuser">;
    getAttribute(attributeName: "personalemailaddress"): Xrm.Attribute<string>;
    getAttribute(attributeName: "positionid"): Xrm.LookupAttribute<"position">;
    getAttribute(attributeName: "preferredaddresscode"): Xrm.OptionSetAttribute<systemuser_preferredaddresscode>;
    getAttribute(attributeName: "preferredphonecode"): Xrm.OptionSetAttribute<systemuser_preferredphonecode>;
    getAttribute(attributeName: "queueid"): Xrm.LookupAttribute<"queue">;
    getAttribute(attributeName: "siteid"): Xrm.LookupAttribute<"site">;
    getAttribute(attributeName: "territoryid"): Xrm.LookupAttribute<"territory">;
    getAttribute(attributeName: "title"): Xrm.Attribute<string>;
    getAttribute(attributeName: "windowsliveid"): Xrm.Attribute<string>;
    getAttribute(attributeName: string): undefined;
    getControl(controlName: "WebResource_RecordWall"): Xrm.WebResourceControl;
    getControl(controlName: "accessmode"): Xrm.OptionSetControl<systemuser_accessmode>;
    getControl(controlName: "address1_city"): Xrm.StringControl;
    getControl(controlName: "address1_country"): Xrm.StringControl;
    getControl(controlName: "address1_fax"): Xrm.StringControl;
    getControl(controlName: "address1_line1"): Xrm.StringControl;
    getControl(controlName: "address1_line2"): Xrm.StringControl;
    getControl(controlName: "address1_line3"): Xrm.StringControl;
    getControl(controlName: "address1_postalcode"): Xrm.StringControl;
    getControl(controlName: "address1_stateorprovince"): Xrm.StringControl;
    getControl(controlName: "address1_telephone1"): Xrm.StringControl;
    getControl(controlName: "address1_telephone2"): Xrm.StringControl;
    getControl(controlName: "address1_telephone3"): Xrm.StringControl;
    getControl(controlName: "address2_city"): Xrm.StringControl;
    getControl(controlName: "address2_country"): Xrm.StringControl;
    getControl(controlName: "address2_line1"): Xrm.StringControl;
    getControl(controlName: "address2_line2"): Xrm.StringControl;
    getControl(controlName: "address2_line3"): Xrm.StringControl;
    getControl(controlName: "address2_postalcode"): Xrm.StringControl;
    getControl(controlName: "address2_stateorprovince"): Xrm.StringControl;
    getControl(controlName: "businessunitid"): Xrm.LookupControl<"businessunit">;
    getControl(controlName: "caltype"): Xrm.OptionSetControl<systemuser_caltype>;
    getControl(controlName: "defaultmailbox"): Xrm.LookupControl<"mailbox">;
    getControl(controlName: "domainname"): Xrm.StringControl;
    getControl(controlName: "firstname"): Xrm.StringControl;
    getControl(controlName: "footer_isdisabled"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "homephone"): Xrm.StringControl;
    getControl(controlName: "internalemailaddress"): Xrm.StringControl;
    getControl(controlName: "invitestatuscode"): Xrm.OptionSetControl<systemuser_invitestatuscode>;
    getControl(controlName: "lastname"): Xrm.StringControl;
    getControl(controlName: "mobilealertemail"): Xrm.StringControl;
    getControl(controlName: "mobilephone"): Xrm.StringControl;
    getControl(controlName: "parentsystemuserid"): Xrm.LookupControl<"systemuser">;
    getControl(controlName: "personalemailaddress"): Xrm.StringControl;
    getControl(controlName: "positionid"): Xrm.LookupControl<"position">;
    getControl(controlName: "preferredaddresscode"): Xrm.OptionSetControl<systemuser_preferredaddresscode>;
    getControl(controlName: "preferredphonecode"): Xrm.OptionSetControl<systemuser_preferredphonecode>;
    getControl(controlName: "queueid"): Xrm.LookupControl<"queue">;
    getControl(controlName: "siteid"): Xrm.LookupControl<"site">;
    getControl(controlName: "territoryid"): Xrm.LookupControl<"territory">;
    getControl(controlName: "title"): Xrm.StringControl;
    getControl(controlName: "windowsliveid"): Xrm.StringControl;
    getControl(controlName: string): undefined;
  }
}
