//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSIS2.WebResources.Webresources.resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AttachFile_1033 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AttachFile_1033() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TSIS2.WebResources.Webresources.resx.AttachFile.1033", typeof(AttachFile_1033).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add File(s).
        /// </summary>
        internal static string AddAttachmentText {
            get {
                return ResourceManager.GetString("AddAttachmentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of uploaded files.
        /// </summary>
        internal static string AttachedFilesGalleryAccessibleLabel {
            get {
                return ResourceManager.GetString("AttachedFilesGalleryAccessibleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more attachment(s) is not a valid type. It can&apos;t be uploaded..
        /// </summary>
        internal static string BlockedFileTypeText {
            get {
                return ResourceManager.GetString("BlockedFileTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Attachments.
        /// </summary>
        internal static string ClearAttachmentsText {
            get {
                return ResourceManager.GetString("ClearAttachmentsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete file - check log for [SharePoint] Delete File from Document Library.
        /// </summary>
        internal static string DeleteError {
            get {
                return ResourceManager.GetString("DeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this file?.
        /// </summary>
        internal static string DeleteFile {
            get {
                return ResourceManager.GetString("DeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete successful.
        /// </summary>
        internal static string DeleteSuccessful {
            get {
                return ResourceManager.GetString("DeleteSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string DescriptionText {
            get {
                return ResourceManager.GetString("DescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string DetailsHeaderText {
            get {
                return ResourceManager.GetString("DetailsHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of files:.
        /// </summary>
        internal static string DocumentCount {
            get {
                return ResourceManager.GetString("DocumentCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR.
        /// </summary>
        internal static string ErrorNotificationLabel {
            get {
                return ResourceManager.GetString("ErrorNotificationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a File Category.
        /// </summary>
        internal static string FileContextComboLabel {
            get {
                return ResourceManager.GetString("FileContextComboLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Category.
        /// </summary>
        internal static string FileContextLabel {
            get {
                return ResourceManager.GetString("FileContextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnail image of .
        /// </summary>
        internal static string FileThumbnailAccessibleLabel {
            get {
                return ResourceManager.GetString("FileThumbnailAccessibleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspection Documents.
        /// </summary>
        internal static string InspectionDocuments {
            get {
                return ResourceManager.GetString("InspectionDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string NameColumnText {
            get {
                return ResourceManager.GetString("NameColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NoAttachmentsText {
            get {
                return ResourceManager.GetString("NoAttachmentsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No documents available.
        /// </summary>
        internal static string NoDocuments {
            get {
                return ResourceManager.GetString("NoDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag file(s) here or click the paper clip to attach file(s).
        /// </summary>
        internal static string NoFilesText {
            get {
                return ResourceManager.GetString("NoFilesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load the Application. Your user account does not have permission to access this SharePoint page..
        /// </summary>
        internal static string NoSharePointAccess {
            get {
                return ResourceManager.GetString("NoSharePointAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to files attached..
        /// </summary>
        internal static string NumberOfFilesAttachedText {
            get {
                return ResourceManager.GetString("NumberOfFilesAttachedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to upload file section.
        /// </summary>
        internal static string ReturnButtonAccessibleLabel {
            get {
                return ResourceManager.GetString("ReturnButtonAccessibleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        internal static string ReturnButtonText {
            get {
                return ResourceManager.GetString("ReturnButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add an attachment.
        /// </summary>
        internal static string SubHeadingText {
            get {
                return ResourceManager.GetString("SubHeadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File upload successful.
        /// </summary>
        internal static string SuccessfulUploadText {
            get {
                return ResourceManager.GetString("SuccessfulUploadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUCCESS.
        /// </summary>
        internal static string SuccessNotificationLabel {
            get {
                return ResourceManager.GetString("SuccessNotificationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The files will be tagged with .
        /// </summary>
        internal static string TagInputAccessibleLabel {
            get {
                return ResourceManager.GetString("TagInputAccessibleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File upload unsuccessful.
        /// </summary>
        internal static string UnsuccessfulUploadText {
            get {
                return ResourceManager.GetString("UnsuccessfulUploadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string UploadButtonText {
            get {
                return ResourceManager.GetString("UploadButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Date.
        /// </summary>
        internal static string UploadDateColumnText {
            get {
                return ResourceManager.GetString("UploadDateColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your files are being uploaded.
        /// </summary>
        internal static string UploadingProgressText {
            get {
                return ResourceManager.GetString("UploadingProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading.
        /// </summary>
        internal static string UploadingText {
            get {
                return ResourceManager.GetString("UploadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attached file(s) haven&apos;t been uploaded.
        /// </summary>
        internal static string UploadWarningText {
            get {
                return ResourceManager.GetString("UploadWarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Files.
        /// </summary>
        internal static string ViewFiles {
            get {
                return ResourceManager.GetString("ViewFiles", resourceCulture);
            }
        }
    }
}
