//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSIS2.WebResources.Webresources.resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AttachFile_1036 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AttachFile_1036() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TSIS2.WebResources.Webresources.resx.AttachFile.1036", typeof(AttachFile_1036).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter un/des fichier(s).
        /// </summary>
        internal static string AddAttachmentText {
            get {
                return ResourceManager.GetString("AddAttachmentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste de fichiers téléchargés.
        /// </summary>
        internal static string AttachedFilesGalleryAccessibleLabel {
            get {
                return ResourceManager.GetString("AttachedFilesGalleryAccessibleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERREUR.
        /// </summary>
        internal static string ErrorNotificationLabel {
            get {
                return ResourceManager.GetString("ErrorNotificationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image miniature de.
        /// </summary>
        internal static string FileThumbnailAccessibleLabel {
            get {
                return ResourceManager.GetString("FileThumbnailAccessibleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        internal static string NameColumnText {
            get {
                return ResourceManager.GetString("NameColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NoAttachmentsText {
            get {
                return ResourceManager.GetString("NoAttachmentsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retourner à la section pour télécharger vos fichiers.
        /// </summary>
        internal static string ReturnButtonAccessibleLabel {
            get {
                return ResourceManager.GetString("ReturnButtonAccessibleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retourner.
        /// </summary>
        internal static string ReturnButtonText {
            get {
                return ResourceManager.GetString("ReturnButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUCCÈS.
        /// </summary>
        internal static string SuccessNotificationLabel {
            get {
                return ResourceManager.GetString("SuccessNotificationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le fichier va être marqué avec.
        /// </summary>
        internal static string TagInputAccessibleLabel {
            get {
                return ResourceManager.GetString("TagInputAccessibleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Télécharger.
        /// </summary>
        internal static string UploadButtonText {
            get {
                return ResourceManager.GetString("UploadButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date du téléchargement.
        /// </summary>
        internal static string UploadDateColumnText {
            get {
                return ResourceManager.GetString("UploadDateColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vos fichiers ont été téléchargés.
        /// </summary>
        internal static string UploadingProgressText {
            get {
                return ResourceManager.GetString("UploadingProgressText", resourceCulture);
            }
        }
    }
}
