//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSIS2.WebResources.Webresources.resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AttachFile_1036 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AttachFile_1036() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TSIS2.WebResources.Webresources.resx.AttachFile.1036", typeof(AttachFile_1036).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter un/des fichier(s).
        /// </summary>
        internal static string AddAttachmentText {
            get {
                return ResourceManager.GetString("AddAttachmentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste de fichiers téléchargés.
        /// </summary>
        internal static string AttachedFilesGalleryAccessibleLabel {
            get {
                return ResourceManager.GetString("AttachedFilesGalleryAccessibleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une ou plusieurs pièces jointes ne sont pas de type valide. Il ne peut pas être téléchargé..
        /// </summary>
        internal static string BlockedFileTypeText {
            get {
                return ResourceManager.GetString("BlockedFileTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effacer les pièces jointes.
        /// </summary>
        internal static string ClearAttachmentsText {
            get {
                return ResourceManager.GetString("ClearAttachmentsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de supprimer le fichier - vérifiez le journal pour [SharePoint] Delete File from Document Library.
        /// </summary>
        internal static string DeleteError {
            get {
                return ResourceManager.GetString("DeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Êtes-vous sûr(e) de vouloir supprimer ce fichier ?.
        /// </summary>
        internal static string DeleteFile {
            get {
                return ResourceManager.GetString("DeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppression réussie.
        /// </summary>
        internal static string DeleteSuccessful {
            get {
                return ResourceManager.GetString("DeleteSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string DescriptionText {
            get {
                return ResourceManager.GetString("DescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détails.
        /// </summary>
        internal static string DetailsHeaderText {
            get {
                return ResourceManager.GetString("DetailsHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de fichiers:.
        /// </summary>
        internal static string DocumentCount {
            get {
                return ResourceManager.GetString("DocumentCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERREUR.
        /// </summary>
        internal static string ErrorNotificationLabel {
            get {
                return ResourceManager.GetString("ErrorNotificationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionnez une catégorie du fichier.
        /// </summary>
        internal static string FileContextComboLabel {
            get {
                return ResourceManager.GetString("FileContextComboLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Catégorie.
        /// </summary>
        internal static string FileContextLabel {
            get {
                return ResourceManager.GetString("FileContextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image miniature de.
        /// </summary>
        internal static string FileThumbnailAccessibleLabel {
            get {
                return ResourceManager.GetString("FileThumbnailAccessibleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        internal static string NameColumnText {
            get {
                return ResourceManager.GetString("NameColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NoAttachmentsText {
            get {
                return ResourceManager.GetString("NoAttachmentsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun document disponible.
        /// </summary>
        internal static string NoDocuments {
            get {
                return ResourceManager.GetString("NoDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glisser le(s) fichier(s) ici ou cliquez sur le trombone pour joindre le(s) fichier(s).
        /// </summary>
        internal static string NoFilesText {
            get {
                return ResourceManager.GetString("NoFilesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de charger l’application. Votre compte utilisateur n’a pas la permission d’accéder à cette page SharePoint..
        /// </summary>
        internal static string NoSharePointAccess {
            get {
                return ResourceManager.GetString("NoSharePointAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fichiers joints..
        /// </summary>
        internal static string NumberOfFilesAttachedText {
            get {
                return ResourceManager.GetString("NumberOfFilesAttachedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retourner à la section pour télécharger vos fichiers.
        /// </summary>
        internal static string ReturnButtonAccessibleLabel {
            get {
                return ResourceManager.GetString("ReturnButtonAccessibleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retourner.
        /// </summary>
        internal static string ReturnButtonText {
            get {
                return ResourceManager.GetString("ReturnButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter une pièce jointe.
        /// </summary>
        internal static string SubHeadingText {
            get {
                return ResourceManager.GetString("SubHeadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Téléchargement de fichier réussi.
        /// </summary>
        internal static string SuccessfulUploadText {
            get {
                return ResourceManager.GetString("SuccessfulUploadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUCCÈS.
        /// </summary>
        internal static string SuccessNotificationLabel {
            get {
                return ResourceManager.GetString("SuccessNotificationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le fichier va être marqué avec.
        /// </summary>
        internal static string TagInputAccessibleLabel {
            get {
                return ResourceManager.GetString("TagInputAccessibleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Échec du téléchargement du fichier.
        /// </summary>
        internal static string UnsuccessfulUploadText {
            get {
                return ResourceManager.GetString("UnsuccessfulUploadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Télécharger.
        /// </summary>
        internal static string UploadButtonText {
            get {
                return ResourceManager.GetString("UploadButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date du téléchargement.
        /// </summary>
        internal static string UploadDateColumnText {
            get {
                return ResourceManager.GetString("UploadDateColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vos fichiers ont été téléchargés.
        /// </summary>
        internal static string UploadingProgressText {
            get {
                return ResourceManager.GetString("UploadingProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Téléchargement.
        /// </summary>
        internal static string UploadingText {
            get {
                return ResourceManager.GetString("UploadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le(s) ficher(s) joints n&apos;ont pas été téléchargés.
        /// </summary>
        internal static string UploadWarningText {
            get {
                return ResourceManager.GetString("UploadWarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voir les fichiers.
        /// </summary>
        internal static string ViewFiles {
            get {
                return ResourceManager.GetString("ViewFiles", resourceCulture);
            }
        }
    }
}
