//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSIS2.WebResources.Webresources.resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class QuestionnaireVersion_1036 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QuestionnaireVersion_1036() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TSIS2.WebResources.Webresources.resx.QuestionnaireVersion.1036", typeof(QuestionnaireVersion_1036).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brouillon.
        /// </summary>
        public static string Draft {
            get {
                return ResourceManager.GetString("Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il y a un chevauchement avec .
        /// </summary>
        public static string OverlapDates {
            get {
                return ResourceManager.GetString("OverlapDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publié (en attente de la date effective).
        /// </summary>
        public static string PublishedAwaitingEffectiveDate {
            get {
                return ResourceManager.GetString("PublishedAwaitingEffectiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publié (en vigueur).
        /// </summary>
        public static string PublishedInEffect {
            get {
                return ResourceManager.GetString("PublishedInEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publié (retraité).
        /// </summary>
        public static string PublishedRetired {
            get {
                return ResourceManager.GetString("PublishedRetired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La date de début doit être antérieure à la date de fin.
        /// </summary>
        public static string StartBeforeEnd {
            get {
                return ResourceManager.GetString("StartBeforeEnd", resourceCulture);
            }
        }
    }
}
