//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSIS2.WebResources.Webresources.resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class tsis2findingwidget_1036 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal tsis2findingwidget_1036() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TSIS2.WebResources.Webresources.resx.tsis2findingwidget.1036", typeof(tsis2findingwidget_1036).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taille de fichier maximum de 10Mb atteint. Veuillez choisir un autre fichier..
        /// </summary>
        internal static string MaxFileSizeAlertText {
            get {
                return ResourceManager.GetString("MaxFileSizeAlertText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taille de fichier maximale atteinte !.
        /// </summary>
        internal static string MaxFileSizeAlertTitle {
            get {
                return ResourceManager.GetString("MaxFileSizeAlertTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Maximum file size exceeded!.
        /// </summary>
        internal static string InspectorComments {
            get {
                return ResourceManager.GetString("InspectorComments", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Maximum file size exceeded!.
        /// </summary>
        internal static string ChooseFiles {
            get {
                return ResourceManager.GetString("ChooseFiles", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Maximum file size exceeded!.
        /// </summary>
        internal static string NoFileChosen {
            get {
                return ResourceManager.GetString("NoFileChosen", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Maximum file size exceeded!.
        /// </summary>
        internal static string DocumentaryEvidence {
            get {
                return ResourceManager.GetString("DocumentaryEvidence", resourceCulture);
            }
        }
    }
}
