//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSIS2.WebResources.Webresources.resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UnplannedWorkOrder_1036 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UnplannedWorkOrder_1036() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TSIS2.WebResources.Webresources.resx.UnplannedWorkOrder.1036", typeof(UnplannedWorkOrder_1036).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changer le statut a &quot;Annulé&quot; va mettre l&apos;ordre de travail en mode lecture-seul une fois que l&apos;enregistrement sera enregistré. Ceci empêchera les modifications aux items de l&apos;ordre de travail. Souhaitez-vous procéder?.
        /// </summary>
        public static string CancelWorkOrderConfirmationText {
            get {
                return ResourceManager.GetString("CancelWorkOrderConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation - Annuler l&apos;ordre de travail.
        /// </summary>
        public static string CancelWorkOrderConfirmationTitle {
            get {
                return ResourceManager.GetString("CancelWorkOrderConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Complete Work Order can&apos;t be canceled. (FR).
        /// </summary>
        public static string CantCancelText {
            get {
                return ResourceManager.GetString("CantCancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changer le statut a &quot;Fermé&quot; va mettre l&apos;ordre de travail en mode lecture-seul une fois que l&apos;enregistrement sera enregistré. Ceci empêchera les modifications aux items de l&apos;ordre de travail. Souhaitez-vous procéder?.
        /// </summary>
        public static string CloseWorkOrderConfirmationText {
            get {
                return ResourceManager.GetString("CloseWorkOrderConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation - Fermer l&apos;ordre de travail.
        /// </summary>
        public static string CloseWorkOrderConfirmationTitle {
            get {
                return ResourceManager.GetString("CloseWorkOrderConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tous les champs obligatoires de suivi du temps doivent être renseignés avant que l&apos;ordre de travail ne puisse être fermé..
        /// </summary>
        public static string CloseWOWithoutTimeTrackingFieldsText {
            get {
                return ResourceManager.GetString("CloseWOWithoutTimeTrackingFieldsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les champs obligatoires de suivi du temps.
        /// </summary>
        public static string CloseWOWithoutTimeTrackingFieldsTitle {
            get {
                return ResourceManager.GetString("CloseWOWithoutTimeTrackingFieldsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La tâche de service obligatoire doit être complété avant que l&apos;ordre de travail puisse être fermé..
        /// </summary>
        public static string CloseWOWithUnCompletedSTText {
            get {
                return ResourceManager.GetString("CloseWOWithUnCompletedSTText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tâche de service incomplet.
        /// </summary>
        public static string CloseWOWithUnCompletedSTTitle {
            get {
                return ResourceManager.GetString("CloseWOWithUnCompletedSTTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtered Activity Type (FR).
        /// </summary>
        public static string FilteredActivityType {
            get {
                return ResourceManager.GetString("FilteredActivityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtered Asset Categories (FR).
        /// </summary>
        public static string FilteredAssetCategories {
            get {
                return ResourceManager.GetString("FilteredAssetCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtered Assets (FR).
        /// </summary>
        public static string FilteredAssets {
            get {
                return ResourceManager.GetString("FilteredAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtered Cases (FR).
        /// </summary>
        public static string FilteredCases {
            get {
                return ResourceManager.GetString("FilteredCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtered Countries (FR).
        /// </summary>
        public static string FilteredCountries {
            get {
                return ResourceManager.GetString("FilteredCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtered Incomplete Work Order Reasons (FR).
        /// </summary>
        public static string FilteredIncompleteWorkOrderReasons {
            get {
                return ResourceManager.GetString("FilteredIncompleteWorkOrderReasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtered Locations (FR).
        /// </summary>
        public static string FilteredLocations {
            get {
                return ResourceManager.GetString("FilteredLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtered Operations (FR).
        /// </summary>
        public static string FilteredOperations {
            get {
                return ResourceManager.GetString("FilteredOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtered Operation Types (FR).
        /// </summary>
        public static string FilteredOperationTypes {
            get {
                return ResourceManager.GetString("FilteredOperationTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtered Sites (FR).
        /// </summary>
        public static string FilteredSites {
            get {
                return ResourceManager.GetString("FilteredSites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtered Stakeholders (FR).
        /// </summary>
        public static string FilteredStakeholders {
            get {
                return ResourceManager.GetString("FilteredStakeholders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le trimestre fiscal a déjà été attribué à l&apos;ordre de travail sélectionné comme partie d&apos;un voyage. Le trimestre fiscal n&apos;a pas été modifié car il ne peut pas être différent des autres ordres de travail de ce voyage..
        /// </summary>
        public static string InvalidFiscalQuarterErrorMsg {
            get {
                return ResourceManager.GetString("InvalidFiscalQuarterErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un ordre de travail peut seulement être réassigné à un membre de votre mode inspectorat..
        /// </summary>
        public static string ReassignWorkOrderErrorMsg {
            get {
                return ResourceManager.GetString("ReassignWorkOrderErrorMsg", resourceCulture);
            }
        }
    }
}
