//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSIS2.WebResources.Webresources.resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WorkOrder_1033 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WorkOrder_1033() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TSIS2.WebResources.Webresources.resx.WorkOrder.1033", typeof(WorkOrder_1033).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing the status to Closed will set the Work Order to Read-Only next time the record is saved, preventing all items within the Work Order from being altered after it is saved. Do you wish to proceed?.
        /// </summary>
        internal static string CloseWorkOrderConfirmationText {
            get {
                return ResourceManager.GetString("CloseWorkOrderConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation - Close Work Order.
        /// </summary>
        internal static string CloseWorkOrderConfirmationTitle {
            get {
                return ResourceManager.GetString("CloseWorkOrderConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtered Activity Type.
        /// </summary>
        internal static string FilteredActivityType {
            get {
                return ResourceManager.GetString("FilteredActivityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtered Asset Categories.
        /// </summary>
        internal static string FilteredAssetCategories {
            get {
                return ResourceManager.GetString("FilteredAssetCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtered Assets.
        /// </summary>
        internal static string FilteredAssets {
            get {
                return ResourceManager.GetString("FilteredAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtered Cases.
        /// </summary>
        internal static string FilteredCases {
            get {
                return ResourceManager.GetString("FilteredCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtered Countries.
        /// </summary>
        internal static string FilteredCountries {
            get {
                return ResourceManager.GetString("FilteredCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtered Locations.
        /// </summary>
        internal static string FilteredLocations {
            get {
                return ResourceManager.GetString("FilteredLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtered Operations.
        /// </summary>
        internal static string FilteredOperations {
            get {
                return ResourceManager.GetString("FilteredOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtered Operation Types.
        /// </summary>
        internal static string FilteredOperationTypes {
            get {
                return ResourceManager.GetString("FilteredOperationTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtered Sites.
        /// </summary>
        internal static string FilteredSites {
            get {
                return ResourceManager.GetString("FilteredSites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtered Stakeholders.
        /// </summary>
        internal static string FilteredStakeholders {
            get {
                return ResourceManager.GetString("FilteredStakeholders", resourceCulture);
            }
        }
    }
}
