//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSIS2.WebResources.Webresources.resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WorkOrder_1033 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WorkOrder_1033() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TSIS2.WebResources.Webresources.resx.WorkOrder.1033", typeof(WorkOrder_1033).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing the status to Cancel will set the Work Order to Read-Only next time the record is saved, preventing all items within the Work Order from being altered after it is saved. Do you wish to proceed?.
        /// </summary>
        internal static string CancelWorkOrderConfirmationText {
            get {
                return ResourceManager.GetString("CancelWorkOrderConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation - Cancel Work Order.
        /// </summary>
        internal static string CancelWorkOrderConfirmationTitle {
            get {
                return ResourceManager.GetString("CancelWorkOrderConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Complete Work Order can&apos;t be canceled..
        /// </summary>
        internal static string CantCancelText {
            get {
                return ResourceManager.GetString("CantCancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing the status to Closed will set the Work Order to Read-Only next time the record is saved, preventing all items within the Work Order from being altered after it is saved. Do you wish to proceed?.
        /// </summary>
        internal static string CloseWorkOrderConfirmationText {
            get {
                return ResourceManager.GetString("CloseWorkOrderConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation - Close Work Order.
        /// </summary>
        internal static string CloseWorkOrderConfirmationTitle {
            get {
                return ResourceManager.GetString("CloseWorkOrderConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All required time tracking fields must be input before the Work order can be closed..
        /// </summary>
        internal static string CloseWOWithoutTimeTrackingFieldsText {
            get {
                return ResourceManager.GetString("CloseWOWithoutTimeTrackingFieldsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required time tracking fields.
        /// </summary>
        internal static string CloseWOWithoutTimeTrackingFieldsTitle {
            get {
                return ResourceManager.GetString("CloseWOWithoutTimeTrackingFieldsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory Service Task must be completed before closing the Work Order..
        /// </summary>
        internal static string CloseWOWithUnCompletedSTText {
            get {
                return ResourceManager.GetString("CloseWOWithUnCompletedSTText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete Service Task.
        /// </summary>
        internal static string CloseWOWithUnCompletedSTTitle {
            get {
                return ResourceManager.GetString("CloseWOWithUnCompletedSTTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtered Activity Type.
        /// </summary>
        internal static string FilteredActivityType {
            get {
                return ResourceManager.GetString("FilteredActivityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtered Asset Categories.
        /// </summary>
        internal static string FilteredAssetCategories {
            get {
                return ResourceManager.GetString("FilteredAssetCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtered Assets.
        /// </summary>
        internal static string FilteredAssets {
            get {
                return ResourceManager.GetString("FilteredAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtered Cases.
        /// </summary>
        internal static string FilteredCases {
            get {
                return ResourceManager.GetString("FilteredCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtered Countries.
        /// </summary>
        internal static string FilteredCountries {
            get {
                return ResourceManager.GetString("FilteredCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtered Incomplete Work Order Reasons.
        /// </summary>
        internal static string FilteredIncompleteWorkOrderReasons {
            get {
                return ResourceManager.GetString("FilteredIncompleteWorkOrderReasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtered Locations.
        /// </summary>
        internal static string FilteredLocations {
            get {
                return ResourceManager.GetString("FilteredLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtered Operations.
        /// </summary>
        internal static string FilteredOperations {
            get {
                return ResourceManager.GetString("FilteredOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtered Operation Types.
        /// </summary>
        internal static string FilteredOperationTypes {
            get {
                return ResourceManager.GetString("FilteredOperationTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtered Sites.
        /// </summary>
        internal static string FilteredSites {
            get {
                return ResourceManager.GetString("FilteredSites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtered Stakeholders.
        /// </summary>
        internal static string FilteredStakeholders {
            get {
                return ResourceManager.GetString("FilteredStakeholders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiscal quarter has already been assigned to the work order selected as part of a trip. Fiscal quarter was not changed as it cannot be different from other work orders in this trip..
        /// </summary>
        internal static string InvalidFiscalQuarterErrorMsg {
            get {
                return ResourceManager.GetString("InvalidFiscalQuarterErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Work Order can only be reassigned to members in your inspectorate..
        /// </summary>
        internal static string ReassignWorkOrderErrorMsg {
            get {
                return ResourceManager.GetString("ReassignWorkOrderErrorMsg", resourceCulture);
            }
        }
    }
}
