declare const enum msdyn_aiagentstatus_msdyn_fallbackreason {
  Intentnotfound = 1,
  Multipleintents = 2,
  Customernotrespondingaftermultipletries = 3,
  Customerrequestssupervisor = 4,
  Customerrejectsproposedsolution = 5,
  Solutionnotfound = 6,
  Intentcoreactionfailed = 7,
  Connectorexceptionoroutage = 8,
  LongrunningactionthreateningSLAorbacklog = 9,
  Manualtakeoverbyagentorsupervisor = 10,
  Stagedisabledinconfiguration = 11,
  Failedtoupdatecasetoactivestatus = 12,
  Failedtocreateanemaildraft = 13,
  Createdanemaildraftwithnorecipients = 14,
  Emailfailedtosend = 15,
  Anunexpectederroroccurred = 16,
  OOFemailresponsefromcustomer = 17,
  Unabletoproceedduetovariousreasons = 18,
  Couldnotsetlanguagecode = 19,
  Guardrailchecksfailed = 20,
}
